### ISSUE TITLE
cogvlm-chat模型本地infer时和demo网址结果有差异，demo结果看起来更加详细

### ISSUE THREAD

**Issue by xiaohuicomeon** [THUDM/CogVLM#100]
感谢大佬们提供的工作。我将cogvlm-chat在本地部署，但是发现如题的问题，想请教一下如何能够完整复现web demo的结果。

图片: 
![cap_1](https://github.com/THUDM/CogVLM/assets/37732267/3ade00e0-15b4-4989-a710-d15326ec8886)

shell:
显卡：1 * A100
python3 cli_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16 --temperature 0.1 --top_k 1 --top_p=0.4

prompt:
Describe the image.

local:  
**The image depicts a man working on the side of an outside wall, possibly sanding or plastering it. He is wearing a blue shirt and appears to be in the process of finishing up his task.**

demo:
**The image showcases an older man, wearing a blue polo shirt, actively working on a house exterior. He is using a trowel to apply a substance to the wall, and he holds a brush in his other hand. The house has multiple windows, and the exterior is painted in a beige or light brown color. The man appears to be on a wooden platform or scaffolding.**

最后再次感谢各位。

**Comment by mactavish91** [comment]
demo里使用了新版的checkpoint，但是release的版本还是旧版的，最近2天将会更新

**Comment by zRzRzRzRzRzRzR** [comment]
现在已经更新，可以尝试一下，另外，我们提供openai的接口，可以尝试接一下？
