### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by fazlicodes** [THUDM/CogVLM#103]
I get the error:
"Timeout! Please wait a few minutes and retry."

**Comment by mactavish91** [comment]
Our system has been affected by a cyber attack. We will resolve this issue as soon as possible during our next working day.

**Comment by JiaweiMorris** [comment]
> Our system has been affected by a cyber attack. We will resolve this issue as soon as possible during our next working day.

周一恢复后今天又出现这个问题了

**Comment by 1049451037** [comment]
我试了一下没问题，是不是你本地网络配置有问题

**Comment by JiaweiMorris** [comment]
> 我试了一下没问题，是不是你本地网络配置有问题

可能是gradio的问题？我刷新了一下网页又正常了，而前一秒在之前的对话中就是一直回复Timeout
