### ISSUE TITLE
生成的文本感觉并没有生成完毕，但提前终止了

### ISSUE THREAD

**Issue by AnnaYang2020** [THUDM/CogVLM#105]
with torch.no_grad():
        response, history, cache_image = chat(
            image_file, 
            model, 
            text_processor_infer,
            image_processor,
            "Describe the image in detail.", 
            history=[],
            max_length=5000, 
            top_p=0.4, 
            temperature=0.8,
            top_k=1,
            invalid_slices=text_processor_infer.invalid_slices,
            no_prompt=False
            )

生成的文本：This photo is a cartoon depicting four different seasons. Below the picture, there are four illustrations in a row, with each one showing a person wearing headphones and having various emotions during sunny or rainy weather. The bottom left illustration shows a man in a purple shirt feeling sad while listening to music on his

不只这一个，许多其他图片也发生了这个问题，max_length好像只与输入文本的长短有关，请问这应该如何解决，是需要调什么参数吗？

**Comment by 1049451037** [comment]
@iyuge2 这里是模型本身的问题吗？我觉得参数配置好像没什么问题。

**Comment by iyuge2** [comment]
@AnnaYang2020 方便提供一下图片文件吗？我们看能否复现一下。不过，模型结果确实有小概率会这样

**Comment by AnnaYang2020** [comment]
非常感谢，图片如下：
![535](https://github.com/THUDM/CogVLM/assets/67533702/06516fa7-4573-43d6-9183-9ad43a27b645)

**Comment by iyuge2** [comment]
@AnnaYang2020 Hi，我在本地成功复现了您汇报的结果。很感谢您汇报这个问题，这个问题与参数关系不大，我们在后面会进一步分析。您可以尝试更换一个Prompt进行提问，比如“Please describe this image.“

prompt：Describe the image in detail.
answer：This photo is a cartoon depicting four different seasons. Below the picture, there are four illustrations in a row, with each one showing a person wearing headphones and having various emotions during sunny or rainy weather. The bottom left illustration shows a man feeling sad while listening to music on his phone in

**prompt：Please describe this image.**
answer：The image is a cartoon depicting four different stages of weather. It features a man in the center, with his headphones plugged into his ears.

The first stage shows him wearing sunny clothes and enjoying good weather; he has a smile on his face. In the second stage, it appears to be raining, as the man's clothing changes to more somber colors, and there are rainbow-colored clouds around him. He now looks sad or displeased.

In the third stage, the weather becomes cloudy, and the man is dressed in darker attire. There is no visible rain but still an overcast atmosphere. His facial expression remains unhappy.

Finally, in the fourth stage, the sky clears up, and the man is once again smiling while wearing brightly colored clothes. This time, there is a happy sun in the background, indicating clear skies and pleasant weather.

近期，我们也会发布一个新的 cogvlm-chat版本，欢迎您持续关注，谢谢！
