### ISSUE TITLE
中英双语模型开源了吗

### ISSUE THREAD

**Issue by www-dayin** [THUDM/CogVLM#107]
看项目代码仓中的readme文档中介绍中英双语版本的CogVLM开源了，但是没有找到下载链接，是还需要一段时间是吗？

**Comment by WenmuZhou** [comment]
同问

**Comment by LianghuiGuo** [comment]
同问

**Comment by greataml** [comment]
同问

**Comment by www-dayin** [comment]
不好意思昨晚眼花啦，理解错了，是模型在智谱清言应用中上线了，而不是开源啦，是我理解的问题不好意思，估计应该会在智谱清言上运行一段时间，调整模型性能后再开源。

**Comment by zRzRzRzRzRzRzR** [comment]
还没有开源，后续有开源计划将会第一时间更新
