### ISSUE TITLE
Timeout! Please wait a few minutes and retry.

### ISSUE THREAD

**Issue by gapjialin** [THUDM/CogVLM#108]
When deploying the project locally, when uploading images for communication on the Gradio webpage, the message 'Time out! Please wait a few minutes and retry' appears.

**Comment by gapjialin** [comment]
用项目里提供的demo，也是出现该问题

**Comment by mactavish91** [comment]
![image](https://github.com/THUDM/CogVLM/assets/58135925/db47c9bb-7f5f-427f-82d3-f7c6f066898e)
网页版本应该是可以正常使用的

**Comment by AlbertShenC** [comment]
> 用项目里提供的demo，也是出现该问题

我之前遇到过类似问题，原因是系统字体导致的，这一行代码读取了系统字体，如果服务器上没有对应设置，返回值就为空，从而导致报错：https://github.com/THUDM/CogVLM/blob/b80161407524235dc8226a68d3a8a75a237e6fa3/utils/parser.py#L19

我的解决方案是上传了一个字体到服务器上，然后自己手动指定了字体路径：

`# font_path = sorted(matplotlib.font_manager.findSystemFonts(fontpaths=None, fontext='ttf'))[0]
    font_path = './font/SIMSUN.TTC'`

**Comment by gapjialin** [comment]
![微信图片编辑_20231120150654](https://github.com/THUDM/CogVLM/assets/107861107/ac2f90be-7f8f-40a9-b44d-821878f137f6)

**Comment by gapjialin** [comment]
![微信图片编辑_20231120150654](https://github.com/THUDM/CogVLM/assets/107861107/df394115-99c3-43ed-8a3e-a2d67620e4ce)

**Comment by gapjialin** [comment]
> ![微信图片编辑_20231120150654](https://user-images.githubusercontent.com/107861107/284164219-df394115-99c3-43ed-8a3e-a2d67620e4ce.jpg)

这是cogVLM Github提供网页端demo，上周还可以正常测试，这周无论是在服务器上部署还是cogVLM Github提供网页端demo，都显示同样的问题，求大神解答

**Comment by gapjialin** [comment]
> ![image](https://user-images.githubusercontent.com/58135925/284154351-db47c9bb-7f5f-427f-82d3-f7c6f066898e.png) 网页版本应该是可以正常使用的
我的就还是有问题，换了一台电脑也不行

**Comment by gapjialin** [comment]
> > 用项目里提供的demo，也是出现该问题
> 
> 我之前遇到过类似问题，原因是系统字体导致的，这一行代码读取了系统字体，如果服务器上没有对应设置，返回值就为空，从而导致报错：
> 
> https://github.com/THUDM/CogVLM/blob/b80161407524235dc8226a68d3a8a75a237e6fa3/utils/parser.py#L19
> 
> 我的解决方案是上传了一个字体到服务器上，然后自己手动指定了字体路径：
> 
> ```
> # font_path = sorted(matplotlib.font_manager.findSystemFonts(fontpaths=None, fontext='ttf'))[0]
> font_path = './font/SIMSUN.TTC'
> ```
我试了该方法，还是不行，最终还是Timeout

**Comment by gapjialin** [comment]
> 关掉系统的代理，比如clash或者shadowsocks。
代理也关了，还是timeout，头大

**Comment by 1049451037** [comment]
那就换个浏览器

**Comment by gapjialin** [comment]
> 那就换个浏览器

换了浏览器也没解决，不知道哪里出了问题，撞墙了
