### ISSUE TITLE
使用2*RTX 3090部署，报GPU资源不足，第一张卡显存用完了，但第二张卡并没使用

### ISSUE THREAD

**Issue by chdaner** [THUDM/CogVLM#109]
![微信图片_20231120142141](https://github.com/THUDM/CogVLM/assets/30647473/504f3a13-1302-4000-92cb-e6a502ec45a1)
![微信图片_20231120142146](https://github.com/THUDM/CogVLM/assets/30647473/0a359243-bc8b-4de4-8d46-31cc00702364)

**Comment by 1049451037** [comment]
因为你并没有按照readme的要求启动多卡程序。

**Comment by chdaner** [comment]
torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16

有按照这种方式运行，第二张显卡启用了，但程序生成了两个不同的PID，这是合理的吗？而且后面还是报错了，走不下去了

**Comment by 1049451037** [comment]
合理。

报什么错。

**Comment by chdaner** [comment]
![微信图片_20231120155403](https://github.com/THUDM/CogVLM/assets/30647473/e41f1cfa-b81f-4a2f-ab2a-bed9998da740)
上图是报错的信息

**Comment by 1049451037** [comment]
可能是内存不够，给主板多插几条内存条吧。至少内存要能装下模型。

**Comment by chdaner** [comment]
https://blog.csdn.net/engchina/article/details/134250905
按这个一步步部署的

**Comment by chdaner** [comment]
但运行的时候内存还没吃完，内存是58G

**Comment by 1049451037** [comment]
那就不太清楚了。你上面贴的命令是cli_demo，不太清楚为什么报错显示的是web_demo。
