### ISSUE TITLE
 which checkpoint is the model for unified the versions of chat and VQA

### ISSUE THREAD

**Issue by jsxapril** [THUDM/CogVLM#113]
Thank for your great work.
In the new readme, it shows "cogvlm-chat-v1.1 The model supports multiple rounds of chat and vqa simultaneously, with different prompts.‘’ and run demo using following code:
python cli_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --bf16
python cli_demo.py --from_pretrained cogvlm-chat-v1.1 --version vqa --english --bf16

But I have trouble in automatically downloading model with SAT, so can you supply the address from huggingface?
Thank you very much.

**Comment by 1049451037** [comment]
README is all you need.

**Comment by jsxapril** [comment]
maybe [THUDM](https://huggingface.co/THUDM)

[cogvlm-chat-hf](https://huggingface.co/THUDM/cogvlm-chat-hf)?
I guass

**Comment by 1049451037** [comment]
<img width="861" alt="image" src="https://github.com/THUDM/CogVLM/assets/15194939/3a127513-bb8d-4756-ac9c-cc53f0fd3750">

**Comment by jsxapril** [comment]
> > maybe [THUDM] ([https://huggingface.co/THUDM)[cogvlm-chat-hf](https://huggingface.co/THUDM/cogvlm-chat-hf%5D(https://huggingface.co/THUDM)%5Bcogvlm-chat-hf%5D(https://huggingface.co/THUDM/cogvlm-chat-hf))? I guass
> 
> Yes, that's the right one.

Thank you very much!

**Comment by jsxapril** [comment]
But I find " "_name_or_path": "cogvlm-chat-v1.1"  "in the file "cogvlm-chat-hf/config.json" , is that means this is the right checkpoints? 
Thank you for your apply

**Comment by 1049451037** [comment]
There are two versions in huggingface.

1. Pure huggingface version: https://huggingface.co/THUDM/cogvlm-chat-hf. This version doesn't depend on sat, and you can load it with huggingface.
2. SAT huggingface version: https://huggingface.co/THUDM/CogVLM. This is just a download mirror in case you cannot download automatically with SAT. It contains the models to be loaded by SAT instead of huggingface.

**Comment by jsxapril** [comment]
It is very helpful, thank you again.

**Comment by 1049451037** [comment]
The SAT huggingface version is also uploaded now.
