### ISSUE TITLE
Can you create embeddings of an image for image to image search (instance retrieval)?

### ISSUE THREAD

**Issue by ChaosSamKo** [THUDM/CogVLM#114]
Thank you for this amazing contribution.

If it is possible, would you be so kind and share either some code to create the embedding or give a general guideline?

**Comment by 1049451037** [comment]
VLM is not designed to produce embedding for an image. I think you can try some ViT encoders like CLIP-VIT, EVA-ViT, etc.

Maybe VLM can do some further re-ranking after retrieval.
