### ISSUE TITLE
测试caption任务时会出现还没说完就截断了

### ISSUE THREAD

**Issue by Pe4nutZz** [THUDM/CogVLM#115]
This picture shows a pair of camels standing in a desert area at sunset. The sky is filled with warm hues of orange and red, creating a dramatic background for the camels. The camels are standing side by side, with one camel on the left and the other on the right. The camel on the left has</s>

**Comment by mactavish91** [comment]
Hello, do you update the checkpoint?

**Comment by Pe4nutZz** [comment]
ok. i try it on.

**Comment by Pe4nutZz** [comment]
> 暂时还不支持

thanks
