### ISSUE TITLE
Support for FP16

### ISSUE THREAD

**Issue by wlw208dzy** [THUDM/CogVLM#116]
感谢您的出色工作，我们想在V100的卡上做一些训练和测试工作，但是V100不支持BF16，如果想用FP16的话，是不是只需要在test_config.json文件中将BF16的enabled值设为False，并将FP16的enabled值设为True，如下所示：
    "bf16": {
      "enabled": false
    },
    "fp16": {
      "enabled": true
    },
请问是否还有其他地方需要修改，我们按照上述修改后，训练在初始化阶段就提前终止了

**Comment by 1049451037** [comment]
```
"fp16": {
      "enabled": true,
      "loss_scale": 0,
      "loss_scale_window": 400,
      "hysteresis": 2,
      "min_loss_scale": 1
    }
```

**Comment by wlw208dzy** [comment]
谢谢您的回答，但是我修改后还是会在训练初始化后就直接退出，报了如下错误：
[2023-11-22 01:32:03,615] [INFO] [checkpointing.py:529:forward] Activation Checkpointing Information
[2023-11-22 01:32:03,616] [INFO] [checkpointing.py:530:forward] ----Partition Activations False, CPU CHECKPOINTING False
[2023-11-22 01:32:03,616] [INFO] [checkpointing.py:531:forward] ----contiguous Memory Checkpointing False with 6 total layers
[2023-11-22 01:32:03,616] [INFO] [checkpointing.py:533:forward] ----Synchronization False
[2023-11-22 01:32:03,616] [INFO] [checkpointing.py:534:forward] ----Profiling time in checkpointing False
[2023-11-22 01:32:05,353] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 16219
[2023-11-22 01:32:05,356] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 16220
[2023-11-22 01:32:05,357] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 16221
[2023-11-22 01:32:05,359] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 16222

**Comment by 1049451037** [comment]
应该是其他问题，bf16只是存储格式，加载参数的时候会转成你的模型格式。

尝试调小batch size呢？是不是显存不够了：

https://github.com/THUDM/CogVLM/blob/2d85b29ddcf4028e138641d9e72920762177627d/scripts/test_config_bf16.json#L2

**Comment by wlw208dzy** [comment]
感觉也不是显存的问题，我调小batchsize到原来的一半了，还是会在初始化的时候提前退出，把FP16关了是可以跑的，一打开就有问题

**Comment by 1049451037** [comment]
inference正常吗？比如运行cli_demo.py

**Comment by wlw208dzy** [comment]
会有浮点格式的问题：Floating point exception (core dumped)

**Comment by 1049451037** [comment]
可以尝试把这里的try except给注释掉来获取更详细的报错信息：

https://github.com/THUDM/CogVLM/blob/2d85b29ddcf4028e138641d9e72920762177627d/cli_demo.py#L108-L126

**Comment by wlw208dzy** [comment]
还是同样的报错信息

**Comment by 1049451037** [comment]
我知道是同样的报错，但是应该会更详细吧，至少可以知道在哪一行报的错。

**Comment by wlw208dzy** [comment]
跟踪进去后，发现是执行到chat.py中的这个地方【116-122】报错：
    output = filling_sequence(
        model, seq,=
        batch_size=1,
        get_masks_and_position_ids=get_func,
        strategy=strategy,
        **inputs
    )[0] # drop memory

**Comment by 1049451037** [comment]
emm...能提供详细一些的报错截图之类的吗，不然我也看不出来什么错误

**Comment by lTloser** [comment]
我在a100-40g也遇到了这个问题，执行跑cli_demo.py --from_pretrained cogvlm-chat-v1.1 --local_tokenizer lmsys/vicuna-7b-v1.5 --version chat --english --fp16， 也卡在filling_sequence这个错误，print(e)的话是没有输出信息的。  具体是在mixin.py 的247行执行mixin_self.rotary_emb时直接闪退了，没有输出错误

**Comment by 1049451037** [comment]
把try except关掉，就不需要print(e)了。具体来说，把：

```python
try:
   xxx
except:
  print(e)
```

改成

```python
xxx
```

就会报错详细的信息。

**Comment by lTloser** [comment]
我这里用a100的bf16推理没有问题， 但我用a100的fp16或者v100的fp16时，不管是关了try-except还是在内部try-except都无法获取详细的报错信息，都是在执行mixin_self.rotary_emb这一行直接退出

**Comment by 1049451037** [comment]
直接退出也得有个报错吧……没有报错我也没办法debug呀

**Comment by Sweezy27** [comment]
想问下这个问题有解决吗? 用V100 fp16，也是报Floating point exception (core dumped)

**Comment by 1049451037** [comment]
可以看一下这个issue：https://github.com/pytorch/pytorch/issues/9465

尝试升级cudnn，因为没有更多的信息，也暂时没有更好的办法。

**Comment by 1049451037** [comment]
好像是xformers版本有问题，我本地可以work的xformerd的版本是0.0.23+e1b9711.d20231013，torch版本是2.1.0+cu118，可以尝试一下。

**Comment by supersteve2001** [comment]
请问针对V100的该问题有解决吗：
Floating point exception （core dumped）

**Comment by supersteve2001** [comment]
> 好像是xformers版本有问题，我本地可以工作的xformerd的版本是0.0.23+e1b9711.d20231013，torch版本是2.1.0+cu118，可以尝试一下。

It works! 关于Floating point exception （core dumped）的问题在fp16下通过采用如上xformers配置及对应依赖可以成功推理
