### ISSUE TITLE
how to do inference with two 24G GPU?

### ISSUE THREAD

**Issue by Youngon** [THUDM/CogVLM#119]
I want to do inference with two 24G GPU，is there any demo use cli_demo.py &  torch.distributed.launch or DataParallel?

**Comment by 1049451037** [comment]
There is clarification in readme:

```
torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --bf16
```

Also, you have another option for now by using `huggingface` and `accelerate`:

https://huggingface.co/THUDM/cogvlm-chat-hf

**Comment by Youngon** [comment]
I have use "torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --bf16" for inference, and either web_demo or cli_demo gets stuck in deadlock. I will try another way, 3Q

**Comment by 1049451037** [comment]
Ensure to use the latest GitHub code https://github.com/THUDM/CogVLM

**Comment by 1049451037** [comment]
Maybe this issue can solve your deadlock problem: https://github.com/THUDM/CogVLM/issues/35
