### ISSUE TITLE
About pretraining and finetune data

### ISSUE THREAD

**Issue by KooSung** [THUDM/CogVLM#120]
1. Data
Will you release the pre-training data and finetune data or the data processing code mentioned in the paper?

- pretraining data

![image](https://github.com/THUDM/CogVLM/assets/34935911/e221818e-299f-4b5f-a1c9-abd1625f7c4c)

- finetune data

![image](https://github.com/THUDM/CogVLM/assets/34935911/e140080c-0bf8-411f-85c0-caae4206038a)

2. Pretraining code
Will you release the pretraining code and scripts?

Thanks

**Comment by Sleepychord** [comment]
Sorry, we will not release the pretrained data because it is huge and very expensive to serve (also some commercial reasons), but they are public so that you can download it on your own. 
We are planning to open-source the corrected LLAVA for SFT if the CogVLM paper is accepted by ICLR.
