### ISSUE TITLE
Multi-gpu inference with huggingface accelerate

### ISSUE THREAD

**Issue by tianyyiii** [THUDM/CogVLM#122]
Hi, thanks for your great work!
I am trying to use two A5000 for inference from huggingface transformer, however, when I run the inference, I get the error, 
".cache/huggingface/modules/transformers_modules/THUDM/cogvlm-chat-hf/b873b639095c57e3778ad9cf3043d9f29f43bf9c/visual.py", line 83, in forward
    output = mlp_input + mlp_output
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:5 and cuda:6!".
Can you share the device_map of huggingface accelerate or provide a example code on how to load the model on 2 gpus with huggingface transformer.

**Comment by 1049451037** [comment]
There is example snippets in huggingface readme.

https://huggingface.co/THUDM/cogvlm-chat-hf

**Comment by tianyyiii** [comment]
It worked. Thank you!

**Comment by tkone2018** [comment]
@tianyyiii @1049451037 我是多卡遇到跟你一样的情况，这该如何解决呀，谢谢

**Comment by tkone2018** [comment]
我就是按照huggingface上做的，但是我的不work

**Comment by tkone2018** [comment]
也是用torchrun命令去启动脚本吗
