### ISSUE TITLE
本地连续问答CUDA报错

### ISSUE THREAD

**Issue by XingTian1994** [THUDM/CogVLM#124]
我再一张80G显存的A100显卡服务器上部署了模型，当问答进行2或3次后就会发生如下报错：
'''error message CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.'''
似乎是GPU显存越界？但运行时显存只占用了72G~76G,这个问题有什么解决办法吗？

**Comment by 1049451037** [comment]
运行的命令前面加入`CUDA_LAUNCH_BLOCKING=1`可以看更详细的报错。

**Comment by zRzRzRzRzRzRzR** [comment]
index越界吗，看一下是有没有特定关键词或者token
