### ISSUE TITLE
refcoco测试结果不匹配

### ISSUE THREAD

**Issue by binwang777** [THUDM/CogVLM#127]
我使用了https://huggingface.co/THUDM/cogvlm-grounding-generalist-hf的模型来测试refcoco的val数据集，测试结果如下：
![image](https://github.com/THUDM/CogVLM/assets/32870325/3fa6d10f-8382-4c76-b2f1-c08d8661ee5e)
我怀疑，1 我的generate函数的参数可能不正确，参数如下
![image](https://github.com/THUDM/CogVLM/assets/32870325/5608f0fd-c0bd-4b93-af2c-7fe75d263fea)
2 我使用prompt可能不正确，我的query形式如下：
![image](https://github.com/THUDM/CogVLM/assets/32870325/102dc90d-ea65-440c-9f05-4d64d512705c)
希望作者能够解答一下我的困惑，感谢。

**Comment by 1049451037** [comment]
因为模型可能会输出多个框，而refcoco所有结果都是只有一个框，所以需要把cogvlm的输出merge成一个框（取min和max）。

另外IOU只要>0.5就算是正确的。

关于prompt的话，我不太清楚你使用的inference脚本是啥，我们应该没有用到`<img></img>`这种prompt。

**Comment by binwang777** [comment]
使用这一句：Can you provide a description of the image and include the coordinates [[x0,y0,x1,y1]] for each mentioned object?
来统一测试refcoco，然后再把cogvlm的输出merge成一个框（取min和max）？请问是这样吗

**Comment by 1049451037** [comment]
我测试的时候是从shikra_template里random.choice的。

**Comment by binwang777** [comment]
感谢回复，我现在重新测试一下

**Comment by binwang777** [comment]
hi，我使用shikra_template['caption2box']里random.choice生成prompt，再插入refcoco的expr进行测试。我观察结果，使用caption2box的prompt，生成的box只有一个，但是为了保险起见，我依然把cogvlm的输出merge成一个框（取min和max）。但是测试分数依然无法匹配，依然是只有82的分数。以下是我的测试代码。`
tokenizer = LlamaTokenizer.from_pretrained('/image-text-match/zerotest/CogVlm/vicuna-7b-v1.5')

model = AutoModelForCausalLM.from_pretrained(
    '/hbox2dir/cogvlm-grounding-generalist-hf',
    torch_dtype=torch.bfloat16,
    trust_remote_code=True
).to('cuda').eval()


def do_test(path,query=None):
    if query:
        prompt_template = random.choice(shikra_template["caption2box"])
        query = prompt_template.replace('<expr>',query)
    else:
        query = 'Can you provide a description of the image and include the coordinates [[x0,y0,x1,y1]] for each mentioned object?'
    
    image = Image.open(path).convert('RGB')
    
    inputs = model.build_conversation_input_ids(tokenizer, query=query, images=[image])
    inputs = {
        'input_ids': inputs['input_ids'].unsqueeze(0).to('cuda'),
        'token_type_ids': inputs['token_type_ids'].unsqueeze(0).to('cuda'),
        'attention_mask': inputs['attention_mask'].unsqueeze(0).to('cuda'),
        'images': [[inputs['images'][0].to('cuda').to(torch.bfloat16)]],
    }
    gen_kwargs = {"max_length": 2048, "do_sample": True}

    with torch.no_grad():
        outputs = model.generate(**inputs, **gen_kwargs)
        outputs = outputs[:, inputs['input_ids'].shape[1]:]
        answer1 = tokenizer.decode(outputs[0])

        ans = answer1.replace('</s>', '')
        respones = ans.strip()

        return respones,query`

**Comment by binwang777** [comment]
hi，我使用shikra_template['caption2box']里random.choice生成prompt，再插入refcoco的expr进行测试。我观察结果，使用caption2box的prompt，生成的box只有一个，但是为了保险起见，我依然把cogvlm的输出merge成一个框（取min和max）。但是测试分数依然无法匹配，依然是只有82的分数。以下是我的测试代码。

`
tokenizer = LlamaTokenizer.from_pretrained('/image-text-match/zerotest/CogVlm/vicuna-7b-v1.5')

model = AutoModelForCausalLM.from_pretrained(
'/hbox2dir/cogvlm-grounding-generalist-hf',
torch_dtype=torch.bfloat16,
trust_remote_code=True
).to('cuda').eval()

def do_test(path,query=None):
if query:
prompt_template = random.choice(shikra_template["caption2box"])
query = prompt_template.replace('',query)
else:
query = 'Can you provide a description of the image and include the coordinates [[x0,y0,x1,y1]] for each mentioned object?'

image = Image.open(path).convert('RGB')

inputs = model.build_conversation_input_ids(tokenizer, query=query, images=[image])
inputs = {
    'input_ids': inputs['input_ids'].unsqueeze(0).to('cuda'),
    'token_type_ids': inputs['token_type_ids'].unsqueeze(0).to('cuda'),
    'attention_mask': inputs['attention_mask'].unsqueeze(0).to('cuda'),
    'images': [[inputs['images'][0].to('cuda').to(torch.bfloat16)]],
}
gen_kwargs = {"max_length": 2048, "do_sample": True}

with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    answer1 = tokenizer.decode(outputs[0])

    ans = answer1.replace('</s>', '')
    respones = ans.strip()

    return respones,query
`

**Comment by binwang777** [comment]
hi，我使用shikra_template['caption2box']里random.choice生成prompt，再插入refcoco的expr进行测试。我观察结果，使用caption2box的prompt，生成的box只有一个，但是为了保险起见，我依然把cogvlm的输出merge成一个框（取min和max）。但是测试分数依然无法匹配，依然是只有82的分数。以下是我的测试代码。

![image](https://github.com/THUDM/CogVLM/assets/32870325/fe682c68-8a62-4fec-a2be-0a1e4694e98d)

**Comment by 1049451037** [comment]
inference的代码感觉没啥问题，可是我看不到你的评测代码……

**Comment by binwang777** [comment]
评测代码是这样：
![image](https://github.com/THUDM/CogVLM/assets/32870325/63e794ba-f5fd-4523-92fb-0193d89a5a7d)
其中get_parsed_response函数是使用parser.py中的逻辑，我检查过，多数框是正确的。
![image](https://github.com/THUDM/CogVLM/assets/32870325/a87c4fc9-d6e4-4b5e-81bc-efe42f2c42dc)

**Comment by binwang777** [comment]
以及我发现prompt前面加上<img><Image></img>，结果会稍好一点，所以我怀疑是prompt的问题

**Comment by binwang777** [comment]
以及我发现prompt前面加上“<img><Image></img>”，结果会稍好一点。所以我怀疑分数对不齐是prompt的问题。

**Comment by binwang777** [comment]
以及我发现prompt前面加上
![image](https://github.com/THUDM/CogVLM/assets/32870325/af67381a-2efe-4e2c-9a11-a1b550855f81)
，结果会稍好一点。所以我怀疑分数对不齐是prompt的问题。

**Comment by 1049451037** [comment]
代码贴的还是不全，get_parsed_response是怎么做的呢？

**Comment by 1049451037** [comment]
哦对了，还有就是generation的参数选择很重要。我在测试的时候是没有do_sample=True的，而且top_k=1，也就是取最大概率的采样。

**Comment by binwang777** [comment]
hi，能我借鉴一下你评测refcoco的文件吗，我的邮箱是1290114075@qq.com

**Comment by 1049451037** [comment]
我是用的sat版本的模型评测的，huggingface的貌似有一些误差，正在调试。模型评测是一个完整的评测平台，可能没办法share，后续可能会考虑开源。我这边也重新跑一下评测，然后告知您。

**Comment by 1049451037** [comment]
我这边重新跑了一下，refcoco-val评测结果是92.41，和论文结果一致。

这是refcoco评测的部分代码，可以参考：

```python
import torch
from torchvision.ops.boxes import box_area

def box_iou(boxes1, boxes2):
    if type(boxes1) == list:
        boxes1 = torch.tensor(boxes1)
    if type(boxes2) == list:
        boxes2 = torch.tensor(boxes2)
    area1 = box_area(boxes1)
    area2 = box_area(boxes2)

    lt = torch.max(boxes1[:, None, :2], boxes2[:, :2])  # [N,M,2]
    rb = torch.min(boxes1[:, None, 2:], boxes2[:, 2:])  # [N,M,2]

    wh = (rb - lt).clamp(min=0)  # [N,M,2]
    inter = wh[:, :, 0] * wh[:, :, 1]  # [N,M]

    union = area1[:, None] + area2 - inter

    iou = inter / union
    return iou

def get_one_box(boxes):
    xmin = min([x[0] for x in boxes])
    ymin = min([x[1] for x in boxes])
    xmax = max([x[2] for x in boxes])
    ymax = max([x[3] for x in boxes])
    return [xmin, ymin, xmax, ymax]

class RefCoCoTask(BaseTask):
    def __init__(self, task_cfg,  **kw_args):
        self.task_name = 'RefCOCO'
        super().__init__(task_cfg,  **kw_args)

    def text_to_box(self, box_text):
        pattern = r"\[\[(.*?)\]\]"
        positions = re.findall(pattern, box_text)
        boxes = []
        for pos in positions:
            try:
                th_box = [[int(y) for y in x.split(',')] for x in pos.split(';') if x.replace(',', '').isdigit()]
                valid_box = [x for x in th_box if len(x) == 4]
                if not valid_box:
                    continue
                boxes.append([get_one_box(valid_box)])
            except:
                pass
        if len(boxes) == 0:
            return [[0.0, 0.0, 0.0, 0.0]]
        return boxes[0]
```

需要注意的是，我们模型的框的格式是[000, 999]，对应0.000~0.999，也就是归一化的坐标，因此和原始的refcoco box进行对应需要进行一下变换。

**Comment by binwang777** [comment]
你好，请问是使用了
![image](https://github.com/THUDM/CogVLM/assets/32870325/d69e8969-636b-4ed0-a807-3e5064079e0d)
输出的结果吗。

**Comment by 1049451037** [comment]
可以通过修改`gen_kwargs`来调整参数减小随机性，比如`gen_kwargs = {"max_length": 2048, "do_sample": False, "top_k": 1}`。

**Comment by 1049451037** [comment]
您好，经过调试我们发现，是因为我们在最后一阶段微调里加入了图像的变换，导致模型具有一些关于图像压缩的bias。

把图像做如下变换，应该就可以复现论文的评测结果了：

```python
        def get_new_image(img):
            import io
            img = img.convert('RGB')
            img_bytes = io.BytesIO()
            img.save(img_bytes, format="jpeg")
            return Image.open(img_bytes)
image = Image.open(path)
new_image = get_new_image(image)
```

感谢您提出的宝贵issue，我们会在后续grounding训练里加入数据增强来提高模型鲁棒性！

**Comment by binwang777** [comment]
超级精细的排查，通过你的指引，我成功复现了论文中的结果。出色的工作。
![image](https://github.com/THUDM/CogVLM/assets/32870325/a6687255-cef2-41cf-8d9a-9ba2e34dbf59)

**Comment by binwang777** [comment]
成功解决

**Comment by 1049451037** [comment]
我们更新了cogvlm-grounding-v1.1版本，新版在训练时加入了图像的数据增强，评测应该会稳定很多！
