### ISSUE TITLE
ChatGLM针对一个问题一次回复多个答案

### ISSUE THREAD

**Issue by Paloma-Gao** [THUDM/CogVLM#128]
ChatGPT可以通过参数n来设置一次回答的条数，那ChatGLM部分怎么控制呢，目前我找到的方法是设计prompt提示，但是更想知道模型在调用参数时有没有相关的借口设置。感谢～

**Comment by 1049451037** [comment]
文本生成的时候有一些随机采样参数可以调整：

https://github.com/THUDM/CogVLM/blob/c7a1176611d4a4995dd0b5bb833a33b481dbeb98/cli_demo.py#L16-L19

**Comment by zRzRzRzRzRzRzR** [comment]
如果是chatglm的LLM模型的问题可以来chatglm仓库提问
