### ISSUE TITLE
请问可以替换模型中的视觉模型或者LLM模型吗？

### ISSUE THREAD

**Issue by zxc351200** [THUDM/CogVLM#129]
请问可以替换模型中的视觉模型或者LLM模型吗？
比如把LLM模型替换为Llama2，
把视觉ViT替换成QWen-VL的视觉ViT？

方便的话，能提供一下相应的代码或者思路吗？谢谢～

**Comment by 1049451037** [comment]
LLM本身就是llama2不必替换。ViT如果不考虑模型并行等特性，可以直接替换就好了，只要接口对接上。

**Comment by AIJIA000** [comment]
> 请问可以替换模型中的视觉模型或者LLM模型吗？ 比如把LLM模型替换为Llama2， 把视觉ViT替换成QWen-VL的视觉ViT？
> 
> 方便的话，能提供一下相应的代码或者思路吗？谢谢～

请问你的意思是指LLM和vision模块是分开的？我想应该是在训练以前做的事情吧？

**Comment by zRzRzRzRzRzRzR** [comment]
理论可行，但是这会有巨大的成本，我们不建议这么做，我们尽量在未来推出方便热插拔的模型，感谢你的理解与支持
