### ISSUE TITLE
Something about Image resolution

### ISSUE THREAD

**Issue by liuhaogeng** [THUDM/CogVLM#132]
想请教一下，你们在把图像的分辨率调大的时候，双线性插值得到的新的position embedding有没有训练那

**Comment by mactavish91** [comment]
有训练

**Comment by 1049451037** [comment]
是否训练取决于你的可训练参数配置里有没有position embedding

**Comment by liuhaogeng** [comment]
不知道我的理解有没有错误，我看论文整个训练可以分为三个阶段，第一阶段是224的预训练，然后后面把res调成了490（这个阶段vit应该是打开了？），然后ift阶段除了vit其他部分全部训练，不知道是否正确，抱歉没有来的及仔细研读你们的代码，问了比较naive的问题
