### ISSUE TITLE
abnormal valid loss  when modify dataset processor module to adapt vqa task

### ISSUE THREAD

**Issue by linpeikun16** [THUDM/CogVLM#133]
to adapt vqa task, i modify dataset processor module, but the valid loss is abnormal, What should I focus on? 
![image](https://github.com/THUDM/CogVLM/assets/90983011/3d032237-2ecd-4ad8-8ecd-e42aa717036b)

**Comment by mactavish91** [comment]
When the labels of the validation set are empty, this situation may occur. You need to confirm that the labels are passed in and participate in the computation.
