### ISSUE TITLE
关于Grounding数据的标注流程

### ISSUE THREAD

**Issue by Weiyun1025** [THUDM/CogVLM#135]
你们在文中提到使用了spaCy抽取caption中的noun phrases，但是我发现对于`In this image, a dog is drinking`这样的句子，spaCy会把`image`这种不指代图中任何物体的名词也抽取出来，请问你们是怎么对noun phrase进行的过滤？

**Comment by jasonnoy** [comment]
weiyun你好，对于像你提出的这个case，因为无法确定类似image的noun是图中存在的物体，所以在提取noun chunk的时候，我们把这种phrase保留，交给GLIP去判断置信度，从而达到筛选过滤的目的。

**Comment by Weiyun1025** [comment]
> weiyun你好，对于像你提出的这个case，因为无法确定类似image的noun是否是图中存在的物体，所以在提取noun chunk的时候，我们把这种phrase保留，交给GLIP去判断置信度，从而达到筛选过滤的目的。

收到，感谢回复！
