### ISSUE TITLE
Questions about the new model version

### ISSUE THREAD

**Issue by sxu1997** [THUDM/CogVLM#136]
Hi, thanks for your great work.
I downloaded the model version updated after 2023.11.20, but the format is different from before. Could you provide the same format as the previous that satisfies the scripts for finetune and eval.

**Comment by mactavish91** [comment]
The structure of the model didn't change; we only made slight modifications to the chat version's prompt to accommodate various inputs. When using the older version of the model, you can simply use the original prompt.

**Comment by mactavish91** [comment]
huggingface上的版本是为了适配huggingface的api，对于sat模型，使用
```python cli_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --bf16```
会自动下载新版本模型
