### ISSUE TITLE
Image question-answer finetuning with cogvlm

### ISSUE THREAD

**Issue by YongLD** [THUDM/CogVLM#139]
Thanks for you amazing job!! As the title said, How can I finetuning with the image - QA pair:
```shell
###Question: What is color of the car?
###Answer: blue.
```

Is there any advise or demo here?

**Comment by mactavish91** [comment]
You can employ the ItemDataset class in utils/dataset.py to construct your own dataset, and utilize [finetune_demo.py](https://github.com/THUDM/CogVLM/blob/main/finetune_demo.py) to fine-tune the model. Further details can be found in the readme.md.

**Comment by mactavish91** [comment]
Sure, but you need to download the sat version of the 224 resolution model instead of the hf version when running [finetune_demo.py](https://github.com/THUDM/CogVLM/blob/main/finetune_demo.py).

**Comment by YongLD** [comment]
OK, Thanks a lot
