### ISSUE TITLE
compare between two images in terms of beauty, color, etc

### ISSUE THREAD

**Issue by xinsir6** [THUDM/CogVLM#141]
I have a problem when use cogvlm to process multi images in the same time, such as,  give the model 2 or more images, and ask it to answer questions about the images, like which one do you like better? The web demo and chat can't solve this problem, so could you provide a special scripts to do this?

**Comment by zRzRzRzRzRzRzR** [comment]
Sorry, our model currently can only contain one image per complete conversation (including history). This is a problem with model performance that cannot be solved in the code. We will accelerate updates to meet the needs of multiple image recognition and analysis. thank you for your support

**Comment by zRzRzRzRzRzRzR** [comment]
Thank you for your support, we will speed up the update
