### ISSUE TITLE
cogvlm使用lora时如何从checkpoint生成merged_lora呢？

### ISSUE THREAD

**Issue by xuxuxuchen** [THUDM/CogVLM#142]
比如微调lora跑800次迭代时，现在的代码仅在第800次迭代输出merged_lora_490，如果存储了第400次的checkpoint，如何从第400次的checkpoint得到merged_lora_490呢？

**Comment by zRzRzRzRzRzRzR** [comment]
我们会在一周内更新[技术文档](https://lslfd0slxc.feishu.cn/wiki/WvQbwIJ9tiPAxGk8ywDck6yfnof),可以关注一下
