### ISSUE TITLE
how can i deploy the web_demo.py in 2 A10-GPU

### ISSUE THREAD

**Issue by winboyer** [THUDM/CogVLM#145]
I deploy the cli_demo.py as "torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --bf16 --local_tokenizer /home/ubuntu/models/vicuna-7b-v1.5", it works

but wen i deploy the web_demo.py as "torchrun --standalone --nnodes=1 --nproc-per-node=2  web_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --bf16 --local_tokenizer /home/ubuntu/models/vicuna-7b-v1.5", it doesn't work well

always have no answer !

how can i fix it?

**Comment by Sleepychord** [comment]
could you provide more details, like your environment and error message?

**Comment by winboyer** [comment]
> could you provide more details, like your environment and error message?

i start it with no error
![image](https://github.com/THUDM/CogVLM/assets/10265383/01202703-50e1-4a59-b761-a85327b7b52a)

the gpus' usage like this
![image](https://github.com/THUDM/CogVLM/assets/10265383/d6059b57-209d-4627-bd56-be5275e2d323)

the post inference without no answer like this 
<img width="1279" alt="image" src="https://github.com/THUDM/CogVLM/assets/10265383/4438a506-5960-480e-bfdf-21a1914a6f8b">
even with an hour gone, it still processing. i don't know why

**Comment by zRzRzRzRzRzRzR** [comment]
try update the latest demo or use streamlit demo
