### ISSUE TITLE
Pretrained Text Encoder

### ISSUE THREAD

**Issue by Ezra-Yu** [THUDM/CogVLM#146]
Which is your Pretrained Text Encoder? 

<img width="847" alt="image" src="https://github.com/THUDM/CogVLM/assets/18586273/b46e8371-6360-4132-a89c-2de4d6b4d4f9">

1. lmsys/vicuna-7b-v1.5
2. lmsys/vicuna-7b-v1.5-16k
3. lmsys/vicuna-7b-v1.5-32k

**Comment by YongLD** [comment]
Text encoder

**Comment by Ezra-Yu** [comment]
> Text encoder

I am sorry. What text encoder?

**Comment by mactavish91** [comment]
We use lmsys/vicuna-7b-v1.5.
