### ISSUE TITLE
Out of memory error for inference on  2 * RTX 3090(24G)

### ISSUE THREAD

**Issue by CarolineBukk** [THUDM/CogVLM#147]
I tried to load the model using the code in the readme:

tokenizer = LlamaTokenizer.from_pretrained('lmsys/vicuna-7b-v1.5')
model = AutoModelForCausalLM.from_pretrained(
    'path/to/model',
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True
).to('cuda').eval()

I could not get it to use both gpu:s without adding the argument load_in_8bit=True. However when I try to do the inference with 
outputs = model.generate(**inputs, **gen_kwargs) I get an out of memory error. 

Is there any tricks to divide the work better between the different gpu:s?
Could load_in_8bit=True cause this issue, and in that case is there another way to make the computer use both gpu:s before running out of memory on the first one?
I am using 2 * RTX 3090(24G) and I run the code using torchrun  --nnodes=1 --nproc-per-node=2

**Comment by mactavish91** [comment]
Try this [method](https://huggingface.co/THUDM/cogvlm-chat-hf/discussions/2#655ca4de93ac084b7d802358)
