### ISSUE TITLE
请问后期会对windows版本进行支持么

### ISSUE THREAD

**Issue by jacksinofn** [THUDM/CogVLM#151]

**Comment by SoYuCry** [comment]
但是安装库的时候，win不兼容诶

**Comment by SoYuCry** [comment]
但是安装库的时候，win不兼容诶

**Comment by zRzRzRzRzRzRzR** [comment]
现在是支持windows的，你在哪里遇到了不兼容

**Comment by SoYuCry** [comment]
我无法成功安装 sat 库，提示的错误显示没有 triton 这个 module，参阅下面的链接发现该库的 windows 版本没有 release

https://github.com/invoke-ai/InvokeAI/issues/2611

> 现在是支持windows的，你在哪里遇到了不兼容

**Comment by 1049451037** [comment]
huggingface的版本是不依赖triton的：https://huggingface.co/THUDM/cogvlm-chat-hf
