### ISSUE TITLE
支持使用 float16 进行推理吗？

### ISSUE THREAD

**Issue by Etpoem** [THUDM/CogVLM#154]
当前手上只有4张 GTX 1080Ti，此显卡不支持 bfloat16 数据格式，直接将数据类型转换为 float16 可以运行，但是结果和demo相差甚远，想请用有没有什么办法可以调整吗？

**Comment by 1049451037** [comment]
支持吧，我本地试了一下没什么问题。直接把运行的命令从--bf16换成--fp16就行。不知道您是怎么转换的？

**Comment by Etpoem** [comment]
我一开始使用的是 https://modelscope.cn/models/ZhipuAI/cogvlm-chat/summary 这边的推理代码，直接将 torch_dtype 更改为 torch.float16, 得出的结果就乱起八糟的，后来我试了一下本代码仓库直接使用 pytorch 进行推理，指定 --fp16，结果就正确了，我怀疑可能和accelerate这个库有关
