### ISSUE TITLE
请问如何制作自己的数据集呢？

### ISSUE THREAD

**Issue by SoYuCry** [THUDM/CogVLM#155]
1、请问如何制作自己的数据集（比如医疗图像）呢，直接制作图片和图片描述就可以吗？

2、我注意到 utils/template.py 中有许多问题模版，请问如何利用他们呢？直接在推理时加入吗，还是在 fintune 时也需要加入这些 prompt 呢？

<img width="994" alt="image" src="https://github.com/THUDM/CogVLM/assets/87529679/c8260e7f-1f60-4333-9b8d-3f06bcb4d810">

**Comment by zRzRzRzRzRzRzR** [comment]
我们在未来一周内会在技术文档](https://lslfd0slxc.feishu.cn/wiki/WvQbwIJ9tiPAxGk8ywDck6yfnof)开设cogagent专栏，尽请关注
