### ISSUE TITLE
Does VLLM support CogVLM inference?

### ISSUE THREAD

**Issue by WangErXiao** [THUDM/CogVLM#156]
Does VLLM support CogVLM inference? I want to accelerate inference

**Comment by zRzRzRzRzRzRzR** [comment]
not yet

**Comment by elesun2018** [comment]
Does VLLM support CogVLM inference? I want to accelerate inference

**Comment by elesun2018** [comment]
请问现在是否支持vllm加速
如何才能支持VLLM加速，谢谢  sss
