### ISSUE TITLE
Do you consider support for llama.cpp and K-type quantization ? Would allow to run this on a 4070

### ISSUE THREAD

**Issue by cmp-nct** [THUDM/CogVLM#157]
This is, by a far extend, the best visual model I've seen. A huge step forward.

The one thing I am missing, as with many releases, is to consider the CPP framework (ggml/llama.cpp).
There is llava support built in but your model would need ViT quantization and the visual-expert inference.

Supporting that framework would open it to the masses and a wide range of smaller hardware devices.

**Comment by mactavish91** [comment]
Thank you for your kind words and thoughtful feedback. We appreciate your suggestion about the CPP framework. It would indeed widen our model's accessibility, especially on smaller devices. We will take your valuable input into consideration in further developments.

**Comment by 1049451037** [comment]
We now support 4-bit quantization now! See README for more details. You can do inference with just 11 GB GPU memory.
