### ISSUE TITLE
进行图片推理时报 error message seqlen_ro must be >= seqlen 错误

### ISSUE THREAD

**Issue by ZoeyLuchen** [THUDM/CogVLM#159]
![微信截图_20231207115748](https://github.com/THUDM/CogVLM/assets/20450789/fd88b9df-24dc-48dc-afb1-04622af3e04f)

**Comment by 1049451037** [comment]
运行的代码是？

**Comment by ZoeyLuchen** [comment]
CUDA_VISIBLE_DEVICES=0 python web_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16 --local_tokenizer /data/root/.sat_models/lmsys/vicuna-7b-v1.5

**Comment by ZoeyLuchen** [comment]
按上面的步骤重新安装后，还是出现相同的错误

**Comment by 1049451037** [comment]
--from_pretrained cogvlm-chat-v1.1
