### ISSUE TITLE
what is difference between this weights?

### ISSUE THREAD

**Issue by WeiXuanLi-1024** [THUDM/CogVLM#16]
![e2094298b3887663c69d69826024904](https://github.com/THUDM/CogVLM/assets/24350444/060a6f26-9b9d-4f1b-8379-c4b3b1956572)

**Comment by 1049451037** [comment]
Recent large (visual-)language models usually trained with two stages.

* The first stage: training with large scale noisy data.
* The second stage: training with small scale high quality data.

The weights obtained after first stage is called `base`. Based on `base`, we can train with some other data for downstream tasks, such as chat, grounding, etc.

**Comment by WeiXuanLi-1024** [comment]
ok，one more question,the "cogvlm-grounding-base" and "cogvlm-grounding-generalist"  use the image resolution is 224*224 ?

**Comment by 1049451037** [comment]
No. It's 490x490.

**Comment by LutaoChu** [comment]
How is `base490` model trained? Is it trained with small high quality data? 
 What resolution is `cogvlm-chat` trained using?
