### ISSUE TITLE
使用 torchrun --standalone --nnodes=1 --nproc-per-node=4 在多显卡上运行web_demo.py。无法返回推理结果

### ISSUE THREAD

**Issue by ZoeyLuchen** [THUDM/CogVLM#161]
我目前有4张A100 40GB 显存的算力卡。

当运行 python web_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --bf16 --local_tokenizer /data/root/.sat_models/lmsys/vicuna-7b-v1.5 使用一张卡运行时，可正常得到推理结果。

当使用 torchrun --standalone --nnodes=1 --nproc-per-node=4 web_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --bf16 --local_tokenizer /data/root/.sat_models/lmsys/vicuna-7b-v1.5 命令使用多张算力卡运行时，无法正常得到推理结果。

运行结果截图如下：
![错误2](https://github.com/THUDM/CogVLM/assets/20450789/c939d9b3-49e0-4187-a9c0-404b2d90e45c)
![错误3](https://github.com/THUDM/CogVLM/assets/20450789/66f38dc9-4f0b-4da0-bad7-b44bb3e923b4)

**Comment by AgentNext** [comment]
一样的问题

**Comment by 1049451037** [comment]
web_demo暂不支持多卡只能用cli_demo跑多卡并行。

**Comment by 1049451037** [comment]
刚刚给web demo加了量化功能，可以用：

```
python web_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --fp16 --quant 8 --local_tokenizer /data/root/.sat_models/lmsys/vicuna-7b-v1.5
```

单卡运行。

**Comment by winboyer** [comment]
> 刚刚给web demo加了量化功能，可以用：
> 
> ```
> python web_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --fp16 --quant 8 --local_tokenizer /data/root/.sat_models/lmsys/vicuna-7b-v1.5
> ```
> 
> 单卡运行。

可以运行，但是返回的结果基本不相关，量化之后的模型应该不能直接接lmsys/vicuna-7b-v1.5吧？

**Comment by 1049451037** [comment]
请安装最新版sat：

```
pip install SwissArmyTransformer -U
```
