### ISSUE TITLE
报错：TypeError: 'NoneType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by SoYuCry** [THUDM/CogVLM#163]
(LLAMA) E:\CogVLM-main>D:/anaconda/envs/LLAMA/python.exe /CogVLM-main/temp.py
Traceback (most recent call last):
  File "e:\CogVLM-main\temp.py", line 100, in <module>
    input_data = build_conversation_input_ids(
  File "e:\CogVLM-main\temp.py", line 82, in build_conversation_input_ids
    'input_ids': torch.tensor(input_ids, dtype=torch.long),
TypeError: 'NoneType' object cannot be interpreted as an integer

经过 Debug 我发现这里给 input_ids 加了很多 None，导致了报错
![image](https://github.com/THUDM/CogVLM/assets/87529679/9e778b59-dc55-4c28-85e2-fd3481134b02)

**Comment by 1049451037** [comment]
说明加载错tokenizer了，tokenizer.pad_token_id应该是0。应该加载vicuda-7b-v1.5的tokenizer。

**Comment by Jenqyang** [comment]
我也遇到了这个错误，最后我发现是需要下载三个文件，只下载tokenizer.model就会出现这个错误
![image](https://github.com/THUDM/CogVLM/assets/85558380/30e318d9-bd82-45b8-abae-b805e65bd11e)
