### ISSUE TITLE
The returned coordinates of the target in the image do not actually match the corresponding coordinates in the image.

### ISSUE THREAD

**Issue by OnlinePage** [THUDM/CogVLM#165]
Hi , i have been exploring CogVLM , and its really powerful at detection and describing things. I was trying to detect and return the x, y cords  of things from the image for example,

as can be seen below i asked for return x, y coordinates of text **New Issue**,  as suggested i used grounding too. Now the returned result is really amazing with perfectly round boxes.

However the returned coordinates does not corresponds to the same in the image.

![image](https://github.com/THUDM/CogVLM/assets/61045650/fcccee03-79cc-4d1a-8f14-c5c38e5e731f)

The returned result is [[881,448,975,521]]
now if I check for same coordinates (marked with red lines) in the image , it does not corresponds , neither the center of given rectangle [[881,448,975,521]] i.e.  (928, 484.5).

![image](https://github.com/THUDM/CogVLM/assets/61045650/3d903787-2e27-452f-a914-7224c958b50c)

**May i know what's the correct way to extract the correct coordinate from the detection which corresponds to the image  coordinates as well as size.🤔**

**Comment by 1049451037** [comment]
Maybe here for reference? https://github.com/THUDM/CogVLM/issues/20

**Comment by Sleepychord** [comment]
@OnlinePage . The number in [[ ]] is a relative coordinations, which is between 000 to 999. You can use int(x_or_y)/1000*real_height_or_width to get the real coordinations.
