### ISSUE TITLE
Performance gap between CogVLM with 4-bit quantization and the CogVLM

### ISSUE THREAD

**Issue by xiujiesong** [THUDM/CogVLM#167]
Hi, 

Thanks for your great work. Noticing that CogVLM supports 4-bit quantization now and i am wondering the performance of CogVLM (4-bit quantization). Is there a large gap between CogVLM (4-bit quantization) and CogVLM?

**Comment by Sleepychord** [comment]
The gap is not large, but we have not run quantitive evaluation yet. Will reply if there is one~

**Comment by xiujiesong** [comment]
Thanks for your reply :)
