### ISSUE TITLE
How can i run the model on RTX 2080 Ti gpu 

### ISSUE THREAD

**Issue by abdulmeral** [THUDM/CogVLM#168]
can you help about it?
i stuck...
i am getting this error

NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 1226, 16, 112) (torch.bfloat16)
     key         : shape=(1, 1226, 16, 112) (torch.bfloat16)
     value       : shape=(1, 1226, 16, 112) (torch.bfloat16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`decoderF` is not supported because:
    attn_bias type is <class 'NoneType'>
    bf16 is only supported on A100+ GPUs
`flshattF@0.0.0` is not supported because:
    requires device with capability > (8, 0) but your GPU has capability (7, 5) (too old)
    bf16 is only supported on A100+ GPUs
    operator wasn't built - see `python -m xformers.info` for more info
`tritonflashattF` is not supported because:
    requires device with capability > (8, 0) but your GPU has capability (7, 5) (too old)
    bf16 is only supported on A100+ GPUs
    operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
    requires GPU with sm80 minimum compute capacity, e.g., A100/H100/L4
`cutlassF` is not supported because:
    bf16 is only supported on A100+ GPUs
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    dtype=torch.bfloat16 (supported: {torch.float32})
    has custom scale
    bf16 is only supported on A100+ GPUs
    unsupported embed per head: 112

**Comment by Murplugg** [comment]
Which file did you edit?

**Comment by xiujiesong** [comment]
I encountered this problem yesterday. It seems like an issue cased by the version of xformer. May be you can try to downgrade the version of xformer, like:

pip install xformers==0.0.16

**Comment by abdulmeral** [comment]
@Murplugg i didnt change files. i tried to implement this:https://huggingface.co/THUDM/cogvlm-chat-hf/discussions/2#655ca4de93ac084b7d802358
and got this error.
xformers       0.0.23+cu118
torch             2.1.1+cu118          
torchaudio    0.11.0                
torchinfo       1.8.0                    
torchvision    0.12.0+cu113

**Comment by abdulmeral** [comment]
can i run the model on cpu?

**Comment by zRzRzRzRzRzRzR** [comment]
Yes you can. but it will be very slow and it will cost near 80G of memory in loading, almost 40G of memory in running

**Comment by 1049451037** [comment]
Maybe huggingface version does not need that much, 35G is enough.

```python
tokenizer = LlamaTokenizer.from_pretrained('vicuna-7b-v1.5')
    model = AutoModelForCausalLM.from_pretrained(
        'THUDM/cogvlm-chat-hf',
        load_in_4bit=True,
        low_cpu_mem_usage=True,
        trust_remote_code=True,
    ).eval()
query = 'Describe this image in details.'
image = Image.open('image-path').convert('RGB')
inputs = model.build_conversation_input_ids(tokenizer, query=query, history=[], images=[image])  # chat mode
inputs = {
    'input_ids': inputs['input_ids'].unsqueeze(0).to('cuda'),
    'token_type_ids': inputs['token_type_ids'].unsqueeze(0).to('cuda'),
    'attention_mask': inputs['attention_mask'].unsqueeze(0).to('cuda'),
    'images': [[inputs['images'][0].to('cuda').to(torch.float16)]],
}
gen_kwargs = {"max_length": 2048, "do_sample": False}

with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0]))
```

**Comment by xiujiesong** [comment]
Actually when I tried to deploy CogVLM on 4 GTX2080Ti, I encountered the similar problem. However, when i deploy CogVLM(4-bit quantization), everything is fine. i am wondering if it is because torch.bfloat16 is not supported? 

NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 1226, 16, 112) (torch.bfloat16)
     key         : shape=(1, 1226, 16, 112) (torch.bfloat16)
     value       : shape=(1, 1226, 16, 112) (torch.bfloat16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`cutlassF` is not supported because:
    bf16 is only supported on A100+ GPUs
`flshattF` is not supported because:
    bf16 is only supported on A100+ GPUs
`tritonflashattF` is not supported because:
    bf16 is only supported on A100+ GPUs
    requires A100 GPU
`smallkF` is not supported because:
    dtype=torch.bfloat16 (supported: {torch.float32})
    max(query.shape[-1] != value.shape[-1]) > 32
    has custom scale
    bf16 is only supported on A100+ GPUs
    unsupported embed per head: 112

**Comment by lzhhha** [comment]
> Actually when I tried to deploy CogVLM on 4 GTX2080Ti, I encountered the similar problem. However, when i deploy CogVLM(4-bit quantization), everything is fine. i am wondering if it is because torch.bfloat16 is not supported?
> 
> NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs: query : shape=(1, 1226, 16, 112) (torch.bfloat16) key : shape=(1, 1226, 16, 112) (torch.bfloat16) value : shape=(1, 1226, 16, 112) (torch.bfloat16) attn_bias : <class 'NoneType'> p : 0.0 `cutlassF` is not supported because: bf16 is only supported on A100+ GPUs `flshattF` is not supported because: bf16 is only supported on A100+ GPUs `tritonflashattF` is not supported because: bf16 is only supported on A100+ GPUs requires A100 GPU `smallkF` is not supported because: dtype=torch.bfloat16 (supported: {torch.float32}) max(query.shape[-1] != value.shape[-1]) > 32 has custom scale bf16 is only supported on A100+ GPUs unsupported embed per head: 112

+1

**Comment by Enchner** [comment]
> Try `float16` instead of `bfloat16`

successful
