### ISSUE TITLE
如何进行全量微调呢

### ISSUE THREAD

**Issue by FZGgithub** [THUDM/CogVLM#169]
如果我想要基于自己的数据进行全量微调，该如何操作呢

**Comment by 1049451037** [comment]
把enable设置成空[]：

https://github.com/THUDM/CogVLM/blob/8ce747175588415a410a37d2010891b9c79ec6d2/finetune_demo.py#L13-L36

**Comment by FZGgithub** [comment]
好的，感谢!

**Comment by 1049451037** [comment]
https://github.com/THUDM/CogVLM/blob/8ce747175588415a410a37d2010891b9c79ec6d2/finetune_demo.py#L13-L36

替换为：

```python
def disable_untrainable_params(self):
    total_trainable = 0
    disable = []
    for n, p in self.named_parameters():
        flag = False
        for e in enable:
                if e.lower() in n.lower():
                    flag = True
                    break
        if flag:
            p.requires_grad_(False)
        else:
            total_trainable += p.numel()
            print_rank0(n)
    print_rank0("***** Total trainable parameters: "+str(total_trainable)+" *****")
```

**Comment by annopackage** [comment]
hi, thanks for your great work. Does the code support pre-train stage using image-text pair data?

**Comment by 1049451037** [comment]
Do you mean initializing a model without from_pretrained but randomly initialized?
