### ISSUE TITLE
Commercially available?

### ISSUE THREAD

**Issue by lj163ucas** [THUDM/CogVLM#17]
The current weighting is Vicuna-7B-v1.5, so the whole code and model should follow the commercial terms of llama2, right?  I am more concerned about whether the weight of the future open source bilingual model can be kept commercially available.  Thank you

**Comment by lj163ucas** [comment]
Commerciability can be explained in detail in the warehouse with License and Notice documents.

**Comment by 1049451037** [comment]
cc @Sleepychord

**Comment by Sleepychord** [comment]
The CogVLM-17B is commercially available, and you can check the LICENSE now.
