### ISSUE TITLE
Is it necessary that Every time I use Image in prompt

### ISSUE THREAD

**Issue by purnasai** [THUDM/CogVLM#170]
I am trying to use this Model as text only sometimes like Laama model and both image+text in its prompt sometimes as VLM Model. 

I only see example of using it for VLM with Image+text in its every prompt.
```
query = 'Describe this image'
image = Image.open(requests.get('https://github.com/THUDM/CogVLM/blob/main/examples/1.png?raw=true', stream=True).raw).convert('RGB')
inputs = model.build_conversation_input_ids(tokenizer, query=query, history=[], images=[image])  # chat mode
inputs = {
    'input_ids': inputs['input_ids'].unsqueeze(0).to('cuda'),
    'token_type_ids': inputs['token_type_ids'].unsqueeze(0).to('cuda'),
    'attention_mask': inputs['attention_mask'].unsqueeze(0).to('cuda'),
    'images': [[inputs['images'][0].to('cuda').to(torch.bfloat16)]],
}
```
#### Question:
How to use it like Laama model with only text and optionally images if user needs. And In my testing this Model with only Text like 
- write for loop to find odd numbers in python.
- who is the president of united states.
the model has not performed well compared to Laama or mistral...!
Any Idea why..!

Thank you in advance.

**Comment by purnasai** [comment]
Hi, just hoping in to check any answers...! Thank you

**Comment by kq-chen** [comment]
The base model used for cog-vlm is vicuna-7b-v1.5. To utilize the pure text mode, it's important to prepend the vicuna-7b-v1.5 prompt to your text. For example:

```python
template = "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: {} ASSISTANT:"

input_sample1 = model.build_conversation_input_ids(
    tokenizer,
    images=[],
    query=template.format(['hello']),
    history=[], 
    )
input_sample2 = model.build_conversation_input_ids(
    tokenizer,
    images=[],
    query=template.format(['who is the president of united states']),
    history=[], 
    )
```

You should observe model outputs similar to:

```python
[
    'Hello! How can I assist you today?</s>', 
    'As of my knowledge cutoff in September 2021, the President of the United States was Joe Biden. However, please note that my training data only goes up to that date, and there is a possibility that there might have been a change in leadership since then.</s>'
]
```

It's important to note that the LLM of cogvlm-base has not been trained. cogvlm-grounding, built on the cogvlm-base, has had its LLM part trained using LoRA. cogvlm-chat, also based on cogvlm-base, its LLM part has been fully trained. Therefore, even if we add the vicuna-7b-v1.5 prompt, the results from the chat version might slightly differ.

Furthermore, when not using the vicuna chat template, it should display capabilities similar to llama2-base. This can be observed with cogvlm-base. cogvlm-grounding showed minor repetitions, while cogvlm-chat, as shown in the issue, produced some gibberish output. This may be related to the absence of system prompts during the training of cogvlm-chat/grounding.
