### ISSUE TITLE
执行--quant 4的模型，出现Floating point exception (core dumped)

### ISSUE THREAD

**Issue by duchenzhuang** [THUDM/CogVLM#172]
<img width="1409" alt="image" src="https://github.com/THUDM/CogVLM/assets/54940144/1182c6df-52a8-417f-90b4-fafbe8a92fa8">

报错如上。SAT是用的最新版本0.4.9的。显卡是80G A100，pytorch的版本是1.13.1, cuda version是11.7

如果需要任何其它的信息，请告诉我哈！

**Comment by duchenzhuang** [comment]
<img width="643" alt="image" src="https://github.com/THUDM/CogVLM/assets/54940144/e024e3aa-ad17-46c1-b655-9311688d4e51">

116的try-except已经注释，但好像还是同样的报错。

**Comment by duchenzhuang** [comment]
我看了其它几个issue好像也有类似的问题，但是似乎都没有好的解决方法？我的微信号是duchenzhuang，人也物理的在清华科技园，可以现场debug...等待作者联系。。

**Comment by Sleepychord** [comment]
用huggingface版本呢？

**Comment by zRzRzRzRzRzRzR** [comment]
明天我到公司测一下hf的int4

**Comment by duchenzhuang** [comment]
> 明天我到公司测一下hf的int4

hello，可以请问一下测试结果怎么样吗？我这边因为用的学校服务器，从huggingface下载东西有点费劲，需要从别的地方先下载，然后再传上去。。所以我还没测huggingface。

**Comment by duchenzhuang** [comment]
<img width="858" alt="image" src="https://github.com/THUDM/CogVLM/assets/54940144/79d0f7b0-af2a-4874-a307-f303de687447">
hf的例子是可以正常运行的。
另外请问一下，quantize之后，性能比正常的精度要降多少呢？

**Comment by zRzRzRzRzRzRzR** [comment]
hf int4是正常的
性能掉了不少，但是能正常使用

**Comment by elesun2018** [comment]
请问SAT模型支持int4 int8推理了吗
