### ISSUE TITLE
我试了各种中文的prompt，但是好像都不太正确

### ISSUE THREAD

**Issue by zky001** [THUDM/CogVLM#173]
![2c44000a454eb3a08c4577d0fbb9ca6](https://github.com/THUDM/CogVLM/assets/9131265/ffbb566b-a848-4de1-b01a-f1b2b9121ae0)
![f781895564f3d2b7bb83edd73040dc7](https://github.com/THUDM/CogVLM/assets/9131265/a1ad6472-8fd5-4add-8ba8-1a6f610e6ed4)

**Comment by 1049451037** [comment]
We don't support Chinese in open-source versions yet.

**Comment by zRzRzRzRzRzRzR** [comment]
已经更新，请按照模板进行提问
