### ISSUE TITLE
Download the latest checkpoints such as cogvlm-chat-v1.1

### ISSUE THREAD

**Issue by wlw208dzy** [THUDM/CogVLM#175]
请问cogvlm-chat-v1.1等最新模型下载的地址是哪里，谢谢！

**Comment by 1049451037** [comment]
SAT的版本运行代码会自动下载。huggingface的版本已经更新v1.1了：https://huggingface.co/THUDM/cogvlm-chat-hf

**Comment by wlw208dzy** [comment]
谢谢
