### ISSUE TITLE
Is there any way I can finetune CogVLM on a 2GPU 3090 32GB?

### ISSUE THREAD

**Issue by TuanAnhNguyen14111998** [THUDM/CogVLM#176]

**Comment by 1049451037** [comment]
Maybe you can try: https://github.com/huggingface/peft for huggingface version of cogvlm.

**Comment by zky001** [comment]
<img width="988" alt="image" src="https://github.com/THUDM/CogVLM/assets/9131265/177fc898-6032-48d8-a336-a308cc4c8059">
I have a try and make lora gpu blow 43G
