### ISSUE TITLE
限制生成长度

### ISSUE THREAD

**Issue by MetaDreamer3d** [THUDM/CogVLM#177]
您好，请问如何控制生成信息的长度，并且保证内容的完整性？
比如我想得到77个单词以内的描述，必须是完整的内容描述（不能截断）

**Comment by 1049451037** [comment]
可以尝试这样：

<img width="1254" alt="image" src="https://github.com/THUDM/CogVLM/assets/15194939/0737cffd-41e3-44f2-ab41-2f5aff45eb7e">

**Comment by MetaDreamer3d** [comment]
按照您的方法，还是超字数了

**Comment by zRzRzRzRzRzRzR** [comment]
Output length 设置 是有效的，请更新我们最新代码并使用本地部署 web ui
