### ISSUE TITLE
The outputs seem like unrelative with that image

### ISSUE THREAD

**Issue by xiaoxiaoxiang-Wang** [THUDM/CogVLM#178]
I repalced the "xops.memory_efficient_attention" with official "scaled_dot_product" because my old version drive of gpu. but It seems the output is not correct and all same basically when I changed the image.
for example
```
Please enter the image path or URL (press Enter for plain text conversation): https://github.com/THUDM/CogVLM/blob/main/examples/3.jpg?raw=true
User: describe this image
Model: This image appears to be a screenshot of a webpage. The webpage seems to be related to travel or tourism, as there are sections titled 'Explore' and 'Trip Inspiration'. There are also various icons and buttons, such as social media sharing options and a search bar.
```

**Comment by 1049451037** [comment]
When you replace a function, you have to determine the input and output of the two function are exactly same first.
