### ISSUE TITLE
how can i merge THUDM/cogvlm-grounding-generalist-hf 8 models into 1 model

### ISSUE THREAD

**Issue by winboyer** [THUDM/CogVLM#179]
i want to know how to merge the 8 models
![image](https://github.com/THUDM/CogVLM/assets/10265383/b9ad118a-1080-46bb-9a1c-4c76c22a0a4b)
can u share the merge model codes?

**Comment by zRzRzRzRzRzRzR** [comment]
读入的时候就合并了，如果你需要，你就重新在用torch保存一次模型就行
