### ISSUE TITLE
Fix web_demo.py

### ISSUE THREAD

**Issue by miandai** [THUDM/CogVLM#18]
![image](https://github.com/THUDM/CogVLM/assets/4371622/f81ceb47-0550-4be7-ad42-9eaf1c9a3e36)

Suggest adding a line of code "torch.no_grad()" before chat(...) line, or It will occupy a large amount of gpu memory as model train process.

**Comment by 1049451037** [comment]
torch.no_grad is fixed.

About 70GB memory problem, we are working on optimizing it.
