### ISSUE TITLE
Using quant in web demo leads to very severe hallucinations

### ISSUE THREAD

**Issue by Labmem009** [THUDM/CogVLM#180]
I  run with 
CUDA_VISIBLE_DEVICES=2 python web_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --fp16 --quant 4
but the result is:
![991ae6702de368dcd510021d2f5459c7](https://github.com/THUDM/CogVLM/assets/26025264/6e5a0988-315c-44b7-9858-28aa64fbc6b4)
Anything wrong with my usage? I also tried quant 8, there are similar hallucinations.

**Comment by 1049451037** [comment]
Sorry, I cannot reproduce your result. Will cli_demo in your environment produce the same thing?

Here is what I run:

```bash
python cli_demo.py --from_pretrained /share/official_pretrains/sat_home/cogvlm-chat-v1.1 --version chat --english --fp16 --quant 4
```

Here is my output:

<img width="1196" alt="image" src="https://github.com/THUDM/CogVLM/assets/15194939/57eec2f0-44ed-45e4-afbb-d13325e00a38">

**Comment by Labmem009** [comment]
I fixed my problem by 
`pip install SwissArmyTransformer -U`
Thanks for your help!
BTW, using web_demo with --stream_chat cannot get stream output on web. Actually it's stream output in the backend, but the web still waits until the whole answer is decoded, how can I fix it?

**Comment by 1049451037** [comment]
web demo doesn't support streaming yet.

**Comment by zRzRzRzRzRzRzR** [comment]
已经制作了具有流式输出的web demo 请关注我们的仓库并更新
