### ISSUE TITLE
Slow inference on GPU with WSL2/Windows

### ISSUE THREAD

**Issue by thojmr** [THUDM/CogVLM#181]
**Problem**: inference is slow, around 3.0 tokens/second, when it should be around 20.0 tokens/second (based on other's results 3090)

I suspect this slowness its because I'm running on WSL2, but the problem exists when running on both WSL2 and Windows 10.  I have no issues running models like Stable Diffusion, LLM's, and image classifiers, so it seems specific to CogVML. It happens with both HuggingFace and SAT versions.

What I see is the GPU consistently around 30-50% usage and a single CPU core maxing at 100% for most of the duration of inference. GPU VRAM is around 15GB at 4bit which seems correct. 

If anyone has any ideas, let me know.

<br>

I verified that CUDA/torch/bitsandbytes are all installed correctly and working:		
```
Torch is correctly set up:
  is_bitsandbytes_available() -> True
  torch.cuda.current_device() -> 0
  torch.cuda.get_device_name(0) -> NVIDIA GeForce RTX 3090
  torch.cuda.is_available()  -> True

Bitsandbytesandbytes status:
    python3 -m bitsandbytes -> SUCCESS!

All model layers are on gpu:
  for n, p in model.named_parameters():
	  print(f"{n}: {p.device}")
	
  model.vision.linear_proj.dense_h_to_4h.weight: cuda:0
  model.vision.linear_proj.gate_proj.weight: cuda:0	
  model.vision.linear_proj.dense_4h_to_h.weight: cuda:0
  etc...

Software:
  - Python version: 3.10.7
  - PyTorch version (GPU?): 2.1.0+cu121 (True)
  - CUDA 12.1
```

<br>

Minimal code (copied from provided, but added timing):
```py
import torch, time
from transformers import AutoModelForCausalLM, LlamaTokenizer, is_bitsandbytes_available
from PIL import Image

local_path = "./cogvlm-chat-hf"
img_path = "./images/1.png"

tokenizer = LlamaTokenizer.from_pretrained('lmsys/vicuna-7b-v1.5')
model = AutoModelForCausalLM.from_pretrained(
    local_path,
    load_in_4bit=True,
    trust_remote_code=True,
).eval()

query = 'Describe this image in details.'
image = Image.open(img_path).convert('RGB')
inputs = model.build_conversation_input_ids(tokenizer, query=query, history=[], images=[image])
inputs = {
    'input_ids': inputs['input_ids'].unsqueeze(0).to('cuda'),
    'token_type_ids': inputs['token_type_ids'].unsqueeze(0).to('cuda'),
    'attention_mask': inputs['attention_mask'].unsqueeze(0).to('cuda'),
    'images': [[inputs['images'][0].to('cuda').to(torch.float16)]],
}
gen_kwargs = {"max_length": 2048, "do_sample": False}

with torch.no_grad():
    start = time.time()
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    end = time.time()
    print(f"{len(outputs[0])/(end - start)} tokens/sec")
    print(f"took {(end - start)} sec")
    print(tokenizer.decode(outputs[0]))
```

**Comment by BBC-Esq** [comment]
Nevermind, after much struggle I got a script to work on Windows...but it doesn't use Triton, which, apparently, is only for Linux currently.  Although, if you go to their Github it seems they're working on a Windows build...
![image](https://github.com/THUDM/CogVLM/assets/108230321/c6164bc2-bd79-41c4-9374-59f0de33b3e7)
Any knowledge about this would be much appreciated.

**Comment by thojmr** [comment]
Windows:
- No Triton
- custom bitsandbytes build from `python -m pip install bitsandbytes==0.39.0 --prefer-binary --extra-index-url=https://jllllll.github.io/bitsandbytes-windows-webui`

WSL2-Ubuntu:
-Triton and Bitsandbytes as per normal

The script was able to do inference without Triton on Windows, so I didn't worry about it too much.  I was mostly just interested in debugging my issue on another OS anyway.  Not sure about flash attention, last time I tried I was not on the right CUDA version and kinda forgot about it, lol

**Comment by 1049451037** [comment]
Perhaps it's a problem of `bitsandbytes-windows-webui`, since 4-bit inference time is determined by bitsandbytes.

**Comment by thojmr** [comment]
I use normal bitsandbytes on WSL2, and the problem still occurs there too.  the windows version was temporary just to see if the same issue happened on Windows.

**Comment by BBC-Esq** [comment]
What type of slowdown are you talking about to see if I'm experiencing the same thing?  I add in my script the time to process each image (yes, mine does batch) as well as total time.  What times are you getting so we can compare?  I don't experience any slowdown on Windows that I know of...

**Comment by thojmr** [comment]
Your tokens/second should be well above the 3 t/s I am getting.  See my example above for the calculation.  Should be  seeing around 20 tokens/second at batch 1  on a 3090.

**Comment by BBC-Esq** [comment]
I'm calculating mine in seconds unfortuntely...and it takes about 18 seconds on my 4090...

**Comment by thojmr** [comment]
`print(f"{len(outputs[0])/(end - start)} tokens/sec")`  the formula is above, but 20-30 seconds per prompt is about what I get too

**Comment by BBC-Esq** [comment]
Running on my 4090 is put it at 12.26 tokens/second, just fyi.  DM me on discord if you want to swap scripts or share more data.  This was batch processing 9 files.

**Comment by thojmr** [comment]
For the sake of an equal comparison, could you run it at batch 1?  If that's still high enough then that will be enough to determine if this is a me problem or not.

**Comment by BBC-Esq** [comment]
One file took 11.73 seconds and 11.51 tokens/second.

**Comment by BBC-Esq** [comment]
Also, maybe a stupid suggestion, but make sure and cast the model to bfloat16 with pytorch since that's what it's originally in...

**Comment by BBC-Esq** [comment]
```torch_dtype=torch.bfloat16,```

AND

```'images': [[inputs['images'][0].to('cuda').to(torch.bfloat16)]],```

**Comment by thojmr** [comment]
Unfortunately swapping to bf16 doesn't make much difference. 3-4 tokens/s.  

Since you don't appear to suffer the same slowness Its more likely something related to my machine/setup.  I'm using the provided examples and suggested pip packages. So there's not much else I can think of.

**Comment by 1049451037** [comment]
So if this is the problem of WSL2 or Windows, since you said "it should be around 20.0 tokens/second (based on other's results 3090)". If ubuntu is OK, it's not a problem that I can solve...

**Comment by 1049451037** [comment]
I just realized another point. You should set bnb_4bit_compute_type=torch.float16 when loading model:

```python
model = AutoModelForCausalLM.from_pretrained(
    local_path,
    load_in_4bit=True,
    bnb_4bit_compute_type=torch.float16,
    trust_remote_code=True,
).eval()
```

**Comment by thojmr** [comment]
> If ubuntu is OK, it's not a problem that I can solve...
Yea, that might be the case, I'm really just looking to see if anyone else has the same issue, or for suggestions.

I will try bnb_4bit_compute_type.

I've also been tinkering with qwen-vl a bit and they are a similar sized model to this one, but they use AutoGPTQ instead of bitsandbytes, and I get the expected 20+ tokens/second with that setup.  So I do suspect that it is some interaction with my setup + bitsandbytes that is the problem.

**Comment by thojmr** [comment]
Similar  results with `bnb_4bit_compute_type`.   And I tried with a number of older/newer bitsandbytes versions.
```py
nf4_config = BitsAndBytesConfig(
   load_in_4bit=True,
   bnb_4bit_quant_type="nf4",
   bnb_4bit_use_double_quant=True,
   bnb_4bit_compute_dtype=torch.bfloat16
)

...
quantization_config=nf4_config,
```

**Comment by BBC-Esq** [comment]
> So if this is the problem of WSL2 or Windows, since you said "it should be around 20.0 tokens/second (based on other's results 3090)". If ubuntu is OK, it's not a problem that I can solve...
I'm not sure why you'd think it's be 20...I'm on a 4090 on Windows with a 13900k and getting 12 maybe 13 tokens/second.

**Comment by thojmr** [comment]
Ah, the 20 token/second metric was from someone on linux machine, so that's more of  an upper bound goal. Your number is probably more realistic for windows, but still a long shot from my 3 tokens/second.

**Comment by thojmr** [comment]
I managed to get up to 6 tokens/second by swapping `bnb_4bit_quant_type="nf4"` to `bnb_4bit_quant_type="fp4"` on Windows, but that's probably as good as it's going to get.

I'll leave this ticket open for a short time to see if anyone else has the same slowness issue.

**Comment by FurkanGozukara** [comment]
anyone made it work with 8 bit loading? 4 bit working but not 8 bit with same code

https://github.com/THUDM/CogVLM/issues/369

**Comment by BBC-Esq** [comment]
Yes, but not using straight bitsandbytes but rather through the transformers library.

**Comment by FurkanGozukara** [comment]
> Yes, but not using straight bitsandbytes but rather through the transformers library.

do you have any idea why my code works in 4 bit but not in 8 bit?

can you share your relevant code?

**Comment by BBC-Esq** [comment]
Actually, I'm not sure you're getting optimal results in 4-bit even...Anyways, here are links to two scripts of mine that use cogvlm-chat-hf, which, please note, are different than the model you're using...cogagent, whihc I've never used.

Generally, you'll find that I use bfloat if it's loaded in 4-bit and float16 if in 8-bit.  I don't provide an option to load in its native size because it would be too slow on consumer hardware.

I'd be curious if you find the solution please keep me posted:

[https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/blob/main/src/loader_images.py](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/blob/main/src/loader_images.py)

[https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/blob/main/src/vision_cogvlm_module.py](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/blob/main/src/vision_cogvlm_module.py)

**Comment by FurkanGozukara** [comment]
> Actually, I'm not sure you're getting optimal results in 4-bit even...I originally cast the model into bfloat16 if I'm using 4-bit...Anyways, here are links to two scripts of mine that use cogvlm-chat-hf, which, please note, are different than the model you're using...cogagent, whihc I've never used.
> 
> Generally, you'll find that I use bfloat if it's loaded in 4-bit and float16 if in 8-bit. I don't provide an option to load in its native size because it would be too slow on consumer hardware.
> 
> I'd be curious if you find the solution please keep me posted:
> 
> https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/blob/main/src/loader_images.py
> 
> https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/blob/main/src/vision_cogvlm_module.py

thanks a lot

i checked and your code is exactly same as mine :/ doesnt make sense

**Comment by BBC-Esq** [comment]
I'd doublecheck that because I thought I saw some differences...Anyways, wish I had time to help you troubleshoot but feel free to review any and all scripts on my repository if they're helpful.  Thanks.

**Comment by FurkanGozukara** [comment]
> I'd doublecheck that because I thought I saw some differences...Anyways, wish I had time to help you troubleshoot but feel free to review any and all scripts on my repository if they're helpful. Thanks.

it is. i double checked i am pretty sure

only difference i had is         if 'cross_images' in input_by_model and input_by_model['cross_images']:
            inputs['cross_images'] = [[input_by_model['cross_images'][0].to(DEVICE).to(torch_type)]]

now i am going to test cogvlm-chat-hf because that is the only difference we have

**Comment by BBC-Esq** [comment]
Yes, when I originally created my scripts I thought I determined that you SHOULD NOT use cogagent...that's a different type of model than for interacting with images like question answering and stuff...

**Comment by FurkanGozukara** [comment]
> Yes, when I originally created my scripts I thought I determined that you SHOULD NOT use cogagent...that's a different type of model than for interacting with images like question answering and stuff...

I want to use as captioning. which model you suggest ? like lets you will train stable diffusion you want image captions

**Comment by BBC-Esq** [comment]
Plus, I just noticed that you're not even using the "chat" version of "cogagent"...but again, I don't think you should be using cogagent period...

[https://huggingface.co/THUDM/cogagent-chat-hf](https://huggingface.co/THUDM/cogagent-chat-hf)

**Comment by BBC-Esq** [comment]
> > Yes, when I originally created my scripts I thought I determined that you SHOULD NOT use cogagent...that's a different type of model than for interacting with images like question answering and stuff...
> 
> I want to use as captioning. which model you suggest ? like lets you will train stable diffusion you want image captions

My program located at [https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio) used cog and others to create captions for images, and I'm using the model I already mentioned...don't even remember why I didn't use cogagent but I think it's because it doesn't do that or isn't the best option...research it.

**Comment by FurkanGozukara** [comment]
> > > Yes, when I originally created my scripts I thought I determined that you SHOULD NOT use cogagent...that's a different type of model than for interacting with images like question answering and stuff...
> > 
> > 
> > I want to use as captioning. which model you suggest ? like lets you will train stable diffusion you want image captions
> 
> My program located at https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio uses cog and others to create captions for images, and I'm using the model I already mentioned...don't even remember why I didn't use cogagent but I think it's because it doesn't do that or isn't the best option...research it.

So you suggest this model?

cogvlm-chat-hf

Downloading right now

**Comment by FurkanGozukara** [comment]
cogvlm-chat-hf worked in 8 bit same code

**Comment by FurkanGozukara** [comment]
@BBC-Esq why do you prefer fp16 for 4-bit and bf16 for 8-bit?

any explanation of this?

also for 16 bit which one you suggest? thank you so much

**Comment by BBC-Esq** [comment]
Glad I could help.  What do you mean by "for 16 bit?"  Are you you saying you want to run cogvlm-chat-hf in 16-bit mode?

**Comment by FurkanGozukara** [comment]
> Glad I could help. What do you mean by "for 16 bit?" Are you you saying you want to run cogvlm-chat-hf in 16-bit mode?

yes in 16 bit mode. not load in 4 bit or not load in 8 bit

**Comment by BBC-Esq** [comment]
You wouldn't use bitsandbytes at all.  You'd need to specify float17, remove the remove the load in 8-bit/4-bit parameters entirely...and also add back the ".to(device)" with "device" being however your syntax defines the device.  Again, look at my script ```loader_images.py``` where I provide different model creations depending on whether bitsandbytes is being used, but here's one relevant portion:

```
class loader_llava:
    def initialize_model_and_tokenizer(self, config):
        chosen_model = config['vision']['chosen_model']
        chosen_size = config['vision']['chosen_size']
        chosen_quant = config['vision']['chosen_quant']
        
        model_id = ""
        if chosen_model == 'llava' and chosen_size == '7b':
            model_id = "llava-hf/llava-1.5-7b-hf"
        elif chosen_model == 'bakllava':
            model_id = "llava-hf/bakLlava-v1-hf"
        elif chosen_model == 'llava' and chosen_size == '13b':
            model_id = "llava-hf/llava-1.5-13b-hf"

        print(f"Selected model: {chosen_model}")
        print(f"Selected size: {chosen_size}")
        print(f"Selected quant: {chosen_quant}")

        device = get_best_device()
        print(f"Using device: {device}")

        if chosen_model == 'llava' and chosen_quant == 'float16':
            model = LlavaForConditionalGeneration.from_pretrained(
                model_id,
                torch_dtype=torch.float16,
                low_cpu_mem_usage=True,
                resume_download=True
            ).to(device)
        elif chosen_model == 'llava' and chosen_quant == '8-bit':
            model = LlavaForConditionalGeneration.from_pretrained(
                model_id,
                torch_dtype=torch.float16,
                low_cpu_mem_usage=True,
                load_in_8bit=True,
                resume_download=True
            )
        elif chosen_model == 'llava' and chosen_quant == '4-bit':
            model = LlavaForConditionalGeneration.from_pretrained(
                model_id,
                torch_dtype=torch.float32,
                low_cpu_mem_usage=True,
                load_in_4bit=True,
                resume_download=True
            )
        elif chosen_model == 'bakllava' and chosen_quant == 'float16':
            model = LlavaForConditionalGeneration.from_pretrained(
                model_id,
                torch_dtype=torch.float16,
                low_cpu_mem_usage=True,
                resume_download=True
            ).to(device)
        elif chosen_model == 'bakllava' and chosen_quant == '8-bit':
            model = LlavaForConditionalGeneration.from_pretrained(
                model_id,
                torch_dtype=torch.float16,
                low_cpu_mem_usage=True,
                load_in_8bit=True,
                resume_download=True
            )
        elif chosen_model == 'bakllava' and chosen_quant == '4-bit':
            model = LlavaForConditionalGeneration.from_pretrained(
                model_id,
                torch_dtype=torch.float32,
                low_cpu_mem_usage=True,
                load_in_4bit=True,
                resume_download=True
            )
```

You'll notice that I remove the load 8/4 bit and add the ".to(device)."  The latter is necessary because when using bitsandbytes it automatically moves it to the device whereas if you do straight float16/bfloat16 it doesn't...

**Comment by FurkanGozukara** [comment]
@BBC-Esq thanks

but what I was asking is different

in 4bit you use float16 and in 8bit you use bfloat16 

why different?

![image](https://github.com/THUDM/CogVLM/assets/19240467/d4a66e91-372a-42aa-b1eb-929ccc8da446)


and for 16bit which one you prefer float16 or bfloat16?

**Comment by BBC-Esq** [comment]
Going off of memory, but I think that it depends on how the original model was created...and I looked at the examples posted on the huggingface repo, which use float/bfloat...so that's my recollection.  I think it's something like...bitsandbytes 4-bit always requires the original format (e.g. float32 or bfloat16 or however the model was created), but 8-bit ALWAYS requires float16.  But again, going off of memory.  Also, there are other bitsandbytes parmeters that I'm not familiar with so my script is a very basic implementation.

Read the examples on huggingface first I believe.  I believe the model was originally created in bfloat16...but not all hardware (e.g. cpu) are optimized let alone will work with bfloat 16...so you might be forced to use float16 anyways.  Here's a good matrix in the context of another library I like:

[https://opennmt.net/CTranslate2/quantization.html#implicit-type-conversion-on-load](https://opennmt.net/CTranslate2/quantization.html#implicit-type-conversion-on-load)

**Comment by FurkanGozukara** [comment]
> Going off of memory, but I think that it depends on how the original model was created...and I looked at the examples posted on the huggingface repo, which use float/bfloat...so that's my recollection. I think it's something like...bitsandbytes 4-bit always requires the original format (e.g. float32 or bfloat16 or however the model was created), but 8-bit ALWAYS requires float16. But again, going off of memory. Also, there are other bitsandbytes parmeters that I'm not familiar with so my script is a very basic implementation.
> 
> Read the examples on huggingface first I believe. I believe the model was originally created in bfloat16...but not all hardware (e.g. cpu) are optimized let alone will work with bfloat 16...so you might be forced to use float16 anyways. Here's a good matrix in the context of another library I like:
> 
> https://opennmt.net/CTranslate2/quantization.html#implicit-type-conversion-on-load

thanks a lot

i also asked here : https://github.com/TimDettmers/bitsandbytes/issues/1030
