### ISSUE TITLE
How do i use grounding enabled with 🤗 transformer inference code using cogvlm-chat-hf?

### ISSUE THREAD

**Issue by OnlinePage** [THUDM/CogVLM#182]
Hi,
i was trying run model with give 🤗transformer inference code at https://github.com/THUDM/CogVLM#-transformers

When I queried with : "locate the nose of the cat in the image in [[x0,y0,x1,y1]]"
The output: "The nose of the cat is located at [[x0,y0,x1,y1]]."

i want to utilize the grounding for target detection and locating.
however the code only accepts two params , image and query!
i want to fully utilize it in same way as it being show on gradio app or 🤗 space as below.

![image](https://github.com/THUDM/CogVLM/assets/61045650/2debc7ee-c968-492f-ae04-383ce34a3329)

can u just share what are correct inference params for others , especially for grounding enabled inference?

**Comment by 1049451037** [comment]
I think here is what you need: https://huggingface.co/THUDM/cogvlm-grounding-generalist-hf
