### ISSUE TITLE
some questions about trainable parameters during fine-tuning

### ISSUE THREAD

**Issue by VittorioDong** [THUDM/CogVLM#189]
感谢您出色的工作，我正在2张A100上微调cogvlm-base-224，目前有两个疑问：
1. 我按照readme中给出的微调示例设置可训练参数（只训练专家模块），请问为什么训练的时候日志打印Total trainable parameters显示262M，但是论文中说明的可训练参数是6.6B呢
2. 如果我想要微调MLP Adapter和视觉专家模块（也就是论文中网络架构图的紫色部分），disable_untrainable_params函数应该如何设置
期待您的回复！
<img width="1190" alt="160e9a7f4ed2e67238065af29" src="https://github.com/THUDM/CogVLM/assets/106992802/f49f2f0b-f0a8-4203-b561-29b189fff1c5">

![11056d70db0a8b86cebaa2d12](https://github.com/THUDM/CogVLM/assets/106992802/9c42d418-9124-410a-9d3c-0b9181dfdb9e)

<img width="728" alt="bdc2e0d4e79dade22c51299de" src="https://github.com/THUDM/CogVLM/assets/106992802/aa1a86a1-9752-48ef-9264-76db81c10439">
<img width="1174" alt="13ae7ec9e61dded8beac3d565" src="https://github.com/THUDM/CogVLM/assets/106992802/1d858ac2-4b7c-4414-b5fb-de3e1fbb3dc4">

**Comment by mactavish91** [comment]
```
def disable_untrainable_params(self):
    enable = ['vit', 'linear_proj', 'mlp.vision', 'rotary.vision', 'eoi', 'boi']
    for n, p in self.named_parameters():
        flag = False
        for e in enable:
            if type(e) is tuple and e[0] in n.lower() and e[1] in n.lower():
                flag = True
                break
            elif type(e) is not tuple and e.lower() in n.lower():
                flag = True
                break

        if not flag:
            p.requires_grad_(False)
        else:
            p.requires_grad_(True)
            print_rank0(n)
            if 'vit' in n:
                p.lr_scale = 0.1
```
你好，可以通过以上设置训练vit和expert的参数

**Comment by chensongcan** [comment]
> ```
> def disable_untrainable_params(self):
>     enable = ['vit', 'linear_proj', 'mlp.vision', 'rotary.vision', 'eoi', 'boi']
>     for n, p in self.named_parameters():
>         flag = False
>         for e in enable:
>             if type(e) is tuple and e[0] in n.lower() and e[1] in n.lower():
>                 flag = True
>                 break
>             elif type(e) is not tuple and e.lower() in n.lower():
>                 flag = True
>                 break
> 
>         if not flag:
>             p.requires_grad_(False)
>         else:
>             p.requires_grad_(True)
>             print_rank0(n)
>             if 'vit' in n:
>                 p.lr_scale = 0.1
> ```
> 
> 你好，可以通过以上设置训练vit和expert的参数

你好，只训练语言模型是enable=["encoder"]吗
