### ISSUE TITLE
Set the output length when inference

### ISSUE THREAD

**Issue by lzhhha** [THUDM/CogVLM#193]
Thank you for your very good work，but I set [max_new_tokens] parameter when reasoning, but the output will be truncated, not output complete sentences，【max_length】parameter is the same，is there a way to solve this？

**Comment by zRzRzRzRzRzRzR** [comment]
最新的仓库的本地demo支持这个功能，你可以使用本地部署并在`composite_demo`运行后可视化的设置

**Comment by lzhhha** [comment]
您好，感谢您的回复，我在跑composite_demo/cli_demo_hf.py时，model.generate() 中的 “max_length”参数应该怎么设置才会让输出的文本长度满足要求呢，如：想让输出文本长度最长为40   当尝试了很多设置但总是会出现文本太长或输出被截断的现象

**Comment by GondorFu** [comment]
> 您好，感谢您的回复，我在跑composite_demo/cli_demo_hf.py时，model.generate() 中的 “max_length”参数应该怎么设置才会让输出的文本长度满足要求呢，如：想让输出文本长度最长为40 当尝试了很多设置但总是会出现文本太长或输出被截断的现象

请问这个问题你解决了吗？我也遇到输出长文本的时候结果被截断的问题，不知道是哪个参数控制的
