### ISSUE TITLE
关于输出文本长度

### ISSUE THREAD

**Issue by lzhhha** [THUDM/CogVLM#198]
我在跑composite_demo/cli_demo_hf.py时，model.generate() 中的 “max_length”参数应该怎么设置才会让输出的文本长度满足要求呢，如：想让输出文本长度最长为40 当尝试了很多设置但总是会出现文本太长或输出被截断的现象

**Comment by lzhhha** [comment]
另外设置“max_new_tokens”参数也没有用，仍然会截断

**Comment by zRzRzRzRzRzRzR** [comment]
这个参数就是用来截断的，没办法控制模型输出长度，只能到了固定字数后自动截断
