### ISSUE TITLE
请问如何构造自己的微调数据集？

### ISSUE THREAD

**Issue by ChingKwanCheung** [THUDM/CogVLM#205]
比如具体的数据格式（json, jsonl）？以什么格式写入图片、问题和标签？类似chatglm3的这种微调文档？https://github.com/THUDM/ChatGLM3/tree/main/finetune_chatmodel_demo

**Comment by zky001** [comment]
![微信图片_20231218150137](https://github.com/THUDM/CogVLM/assets/9131265/33f4bea0-9d60-483a-b09c-8a42c3531f45)
<img width="615" alt="微信图片_20231218150150" src="https://github.com/THUDM/CogVLM/assets/9131265/e5cb7381-95a0-4335-81a5-9dabf42caf0c">
我按照预测验证码类似的格式，搞了一个分类数据集，文件名是图片类别的label，跑了一下没啥效果还可以，和直接分类的小模型比打平了，主要还是看有啥业务需求吧，自己玩的话现有的代码稍微修改一下就行。

**Comment by ChingKwanCheung** [comment]
> ![微信图片_20231218150137](https://private-user-images.githubusercontent.com/9131265/291176538-33f4bea0-9d60-483a-b09c-8a42c3531f45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTQyNTksIm5iZiI6MTcwMjg5Mzk1OSwicGF0aCI6Ii85MTMxMjY1LzI5MTE3NjUzOC0zM2Y0YmVhMC05ZDYwLTQ4M2EtYjA5Yy04YTQyYzM1MzFmNDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMTAwNTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzc0MjZhMGRhMzgyYjdlZjkwMzIxMzdlYjExNzA0Y2ZmNGEzYmMwYWU4Yzc5NzI5Nzc0Mzc2YWNkOGYyYjdjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c-cJWdLKUJfoew9AnQpuDFL0mabZFe3O1YbVyds5bic) <img alt="微信图片_20231218150150" width="615" src="https://private-user-images.githubusercontent.com/9131265/291176550-e5cb7381-95a0-4335-81a5-9dabf42caf0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTQyNTksIm5iZiI6MTcwMjg5Mzk1OSwicGF0aCI6Ii85MTMxMjY1LzI5MTE3NjU1MC1lNWNiNzM4MS05NWEwLTQzMzUtODFhNS05ZGFiZjQyY2FmMGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMTAwNTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTgyYzFlYmZjMjIzMDdhZTg0NGIzNGMzZTZjMWU3YzQ3NmY4MzMwY2RhMWQ2ZjE5NTg5N2NjNDhiNzcyOTkyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YAQ2QE5iUdAQIL-ybk-RRv0J8NUBCJbKeIdM1RquHzY"> 我按照预测验证码类似的格式，搞了一个分类数据集，文件名是图片类别的label，跑了一下没啥效果还可以，和直接分类的小模型比打平了，主要还是看有啥业务需求吧，自己玩的话现有的代码稍微修改一下就行。

请问能分享一下数据集的样例吗？

**Comment by zRzRzRzRzRzRzR** [comment]
我们将会在技术文档公开一个比较合理和简单的 对话格式数据集永用于微调，敬请期待

**Comment by ChingKwanCheung** [comment]
> 我们将会在技术文档公开一个比较合理和简单的 对话格式数据集永用于微调，敬请期待

我看到了readme中关于验证码数据集的示例，请问如何在微调数据集中构造输入（prompt）呢？验证码数据集中我看到只有图片和对应的label

**Comment by zky001** [comment]
> > 我们将会在技术文档公开一个比较合理和简单的 对话格式数据集永用于微调，敬请期待
> 
> 我看到了readme中关于验证码数据集的示例，请问如何在微调数据集中构造输入（prompt）呢？验证码数据集中我看到只有图片和对应的label

代码中都有，prompt中直接是验证码。就可以
