### ISSUE TITLE
How to reproduce your MM-Vet score?

### ISSUE THREAD

**Issue by TideDra** [THUDM/CogVLM#206]
MM-Vet [leaderboard](https://paperswithcode.com/sota/visual-question-answering-on-mm-vet) shows CogVLM(vicuna-7b) achieves 52.8 scores. How do you get this score and which checkpoint is used?  Can you release the evaluation script? I evaluate CogVLM-chat and its mm-vet score is only 40.7. Here is my evaluation script:
```python
import torch
from PIL import Image
from transformers import AutoModelForCausalLM, LlamaTokenizer
import os
import json
from tqdm import tqdm
DATAROOT = "/data/gozhang/code/LLaVA/playground/data/eval/mm-vet"

with open(os.path.join(DATAROOT,'mm-vet.json'),'r') as f:
    data = json.load(f)


tokenizer = LlamaTokenizer.from_pretrained('/data/gozhang/code/LLaVA/ckpts/vicuna-7b-v1.5')
model = AutoModelForCausalLM.from_pretrained(
    '/data/gozhang/code/LLaVA/ckpts/cogvlm-chat-hf',
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True
).to('cuda').eval()

results = {}
# vqa example
bar = tqdm(total=len(data))
for k,v in data.items():
    query = v['question']
    img_path = os.path.join(DATAROOT,"images",v['imagename'])
    image = Image.open(img_path).convert('RGB')
    inputs = model.build_conversation_input_ids(tokenizer, query=query, history=[], images=[image])  # chat mode
    inputs = {
        'input_ids': inputs['input_ids'].unsqueeze(0).to('cuda'),
        'token_type_ids': inputs['token_type_ids'].unsqueeze(0).to('cuda'),
        'attention_mask': inputs['attention_mask'].unsqueeze(0).to('cuda'),
        'images': [[inputs['images'][0].to('cuda').to(torch.bfloat16)]],
    }
    gen_kwargs = {"max_length": 2048, "do_sample": False}

    with torch.no_grad():
        outputs = model.generate(**inputs, **gen_kwargs)
        outputs = outputs[:, inputs['input_ids'].shape[1]:]
        response=tokenizer.decode(outputs[0])
        results[k] = response
    bar.update(1)
with open('cogvlm-chat-hf.json','w') as f:
    json.dump(results,f,indent=4)
```

**Comment by zky001** [comment]
> MM-Vet [leaderboard](https://paperswithcode.com/sota/visual-question-answering-on-mm-vet) shows CogVLM(vicuna-7b) achieves 52.8 scores. How do you get this score and which checkpoint is used? Can you release the evaluation script? I evaluate CogVLM-chat and its mm-vet score is only 40.7. Here is my evaluation script:
> 
> ```python
> import torch
> from PIL import Image
> from transformers import AutoModelForCausalLM, LlamaTokenizer
> import os
> import json
> from tqdm import tqdm
> DATAROOT = "/data/gozhang/code/LLaVA/playground/data/eval/mm-vet"
> 
> with open(os.path.join(DATAROOT,'mm-vet.json'),'r') as f:
>     data = json.load(f)
> 
> 
> tokenizer = LlamaTokenizer.from_pretrained('/data/gozhang/code/LLaVA/ckpts/vicuna-7b-v1.5')
> model = AutoModelForCausalLM.from_pretrained(
>     '/data/gozhang/code/LLaVA/ckpts/cogvlm-chat-hf',
>     torch_dtype=torch.bfloat16,
>     low_cpu_mem_usage=True,
>     trust_remote_code=True
> ).to('cuda').eval()
> 
> results = {}
> # vqa example
> bar = tqdm(total=len(data))
> for k,v in data.items():
>     query = v['question']
>     img_path = os.path.join(DATAROOT,"images",v['imagename'])
>     image = Image.open(img_path).convert('RGB')
>     inputs = model.build_conversation_input_ids(tokenizer, query=query, history=[], images=[image])  # chat mode
>     inputs = {
>         'input_ids': inputs['input_ids'].unsqueeze(0).to('cuda'),
>         'token_type_ids': inputs['token_type_ids'].unsqueeze(0).to('cuda'),
>         'attention_mask': inputs['attention_mask'].unsqueeze(0).to('cuda'),
>         'images': [[inputs['images'][0].to('cuda').to(torch.bfloat16)]],
>     }
>     gen_kwargs = {"max_length": 2048, "do_sample": False}
> 
>     with torch.no_grad():
>         outputs = model.generate(**inputs, **gen_kwargs)
>         outputs = outputs[:, inputs['input_ids'].shape[1]:]
>         response=tokenizer.decode(outputs[0])
>         results[k] = response
>     bar.update(1)
> with open('cogvlm-chat-hf.json','w') as f:
>     json.dump(results,f,indent=4)
> ```

应该是有tricks吧，我之前试了也是四十多分

**Comment by 1049451037** [comment]
There is no tricks in our model. We got 51.7 evaluation score with your evaluation script (just copied, paste).

My hypothesis is that you downloaded wrong checkpoint. Our chat model is chat-v1.1 now. You should re-download if you downloaded v1.0.
