### ISSUE TITLE
微调后的模型无法被cli_demo.py加载

### ISSUE THREAD

**Issue by npzl** [THUDM/CogVLM#208]
### System Info / 系統信息

微调后的模型无法被cli_demo.py加载，报错参数缺失

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

微调后输出模型。调用merge_model.py得到merge_model_224。     
python cli_demo.py --from_pretrained ./checkpoints/merged_model_224  --version base --bf16 报**推理模型参数确实**的错：    

![image](https://github.com/THUDM/CogVLM/assets/40789804/f8465b89-00b3-4563-964f-045dff4d2c65)     

### Expected behavior / 期待表现

请问怎么修改呢？

**Comment by 1049451037** [comment]
可以参照这里：https://github.com/THUDM/CogVLM/issues/117

因为你也没有提供更多信息，我也没办法帮你更多了。

**Comment by npzl** [comment]
> 可以参照这里：#117
> 
> 因为你也没有提供更多信息，我也没办法帮你更多了。
非常感谢。
我刚刚改成sat.model.AutoModel.from_pretrained这种方式加载后就能跑了呢。
