### ISSUE TITLE
Question about evaluation CogAgent with Mind2Web

### ISSUE THREAD

**Issue by zhangliang-04** [THUDM/CogVLM#217]
Dear author,
Thank you for the excellent work and opensourcing! 
I find that to accomplish a task on the web, the demo and cases in the papers show that CogAgent generates a bounding box coordinate for each step. However, the annotation of Mind2Web seems to select one of the DOM elements on the page. So I wonder how do you evaluate CogAgent to get the scores in the paper?

**Comment by 1049451037** [comment]
mind2web also provides bounding boxes for DOM elements in their raw data.

**Comment by zhangliang-04** [comment]
So in my understanding, you changed the elements of the original options with bounding box coordinates and then treated the task as multiple choices as Mind2Web? **OR** considered it correct if attains IoU with annotation greater than a threshold?

**Comment by 1049451037** [comment]
multiple choices, just replacing the text option to coordinates option.

**Comment by SiyuanHuang95** [comment]
@zhangliang-04 Hi, I am curious about the multi-modal version of the Mind2Web, since I remembered that it is the pure-text web explorer in their original paper. Did they also have released the MM version?

**Comment by 1049451037** [comment]
The raw dump of data contains the web page screenshot and the DOM bounding boxes.

**Comment by SiyuanHuang95** [comment]
Thanks for your information. 

BTW do you have a plan to release your constructed datasets? @1049451037
