### ISSUE TITLE
CogVLM的HF的4bit版本，如何进行纯文本交互？

### ISSUE THREAD

**Issue by duchenzhuang** [THUDM/CogVLM#218]
### System Info / 系統信息

cuda 12.2, torch 2.1.2，各种包基本都是最新的版本。

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我尝试用如下代码，让CogVLM进行纯文本的对话，query:"Do you know Tsinghua University?"，回复又慢又奇怪:"nobody 10000000...0000"。
但是如果我随便加一个图片的话，在继续用这个文本query，回复就比较正常了:"Yes, Tsinghua University is a prestigious public research university located in Beijing, China. It is one of the oldest and most selective institutions of higher education in China and is often ranked among the top universities globally.</s>"

代码如下:
<img width="858" alt="image" src="https://github.com/THUDM/CogVLM/assets/54940144/1782ffd2-9017-4d9d-83ee-498133eaa157">

import torch
import requests
from PIL import Image
from transformers import AutoModelForCausalLM, LlamaTokenizer

tokenizer = LlamaTokenizer.from_pretrained('lmsys/vicuna-7b-v1.5')
model = AutoModelForCausalLM.from_pretrained(
        'THUDM/cogvlm-chat-hf',
        load_in_4bit=True,
        trust_remote_code=True,
    ).eval()
query = 'Do you know Tsinghua University?'

inputs = model.build_conversation_input_ids(tokenizer, query=query, history=[])  # chat mode
inputs = {
    'input_ids': inputs['input_ids'].unsqueeze(0).to('cuda'),
    'token_type_ids': inputs['token_type_ids'].unsqueeze(0).to('cuda'),
    'attention_mask': inputs['attention_mask'].unsqueeze(0).to('cuda'),
}
gen_kwargs = {"max_length": 2048, "do_sample": False}
with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0]))

### Expected behavior / 期待表现

CogVLM可以进行纯文本对话，不需要非得加一个图片的输入。

**Comment by 1049451037** [comment]
参考这个issue：https://github.com/THUDM/CogVLM/issues/170

cogvlm可以支持纯文本对话，但是需要用另一套prompt。

**Comment by duchenzhuang** [comment]
> 参考这个issue：#170
> 
> cogvlm可以支持纯文本对话，但是需要用另一套prompt。

感谢如此神速的回复，我马上试一下然后反馈。

**Comment by duchenzhuang** [comment]
@1049451037 感谢！已经解决！
