### ISSUE TITLE
Cloud you please provide hardware requirement with different model？

### ISSUE THREAD

**Issue by vergil-ong** [THUDM/CogVLM#22]
I have only one 3090 GPU, and 32GB memory

**Comment by 1049451037** [comment]
The 490 version models require 2 3090 at least. Maybe you can try the 224 version. However, 224 version does not have chat model.

**Comment by vergil-ong** [comment]
so I cannot use base version to caption the image？

**Comment by 1049451037** [comment]
Maybe you can use ptuning to fine-tune a 224 version for captioning. Although 224 version base can do captioning, it's output is not that detailed and not interactive (but you can also try).

**Comment by 1049451037** [comment]
No, you can't. The checkpoint weight file is already 34GB.

**Comment by vergil-ong** [comment]
OK Thank you
