### ISSUE TITLE
CogAgent的multi-head cross-attention

### ISSUE THREAD

**Issue by binwang777** [THUDM/CogVLM#220]
hi，非常有趣实用的高分辨率解决方案。
我查看了mixin.py的代码，但是好像还没有变化。CogAgentModel使用的还是旧的LlamaVisionExpertAttnMixin吗，请问哪里可以找到multi-head cross-attention的相关代码呢。

**Comment by 1049451037** [comment]
cross attention是sat内置的forward：

https://github.com/THUDM/SwissArmyTransformer/blob/22c0810866cc7e2bfef6420454ea7021adbcf01f/sat/transformer_defaults.py#L154-L229

**Comment by binwang777** [comment]
感谢你的解答

**Comment by binwang777** [comment]
感谢您的回复
