### ISSUE TITLE
如何使用该模型做图像识别呢

### ISSUE THREAD

**Issue by Eric-wei** [THUDM/CogVLM#222]
### Feature request  / 功能建议

我们有这样的一个场景，在我们的生产流水线上，每天都会有成千上万个产品进行生产，其中有个环节是我们会对一个零部件进行拍照检测，通过和我们的标准照片对比来判定是否合格，想请问下这个模型通过生产产品与标准样品对比后识别出产品的不良率吗？

### Motivation / 动机

null

### Your contribution / 您的贡献

null

**Comment by zRzRzRzRzRzRzR** [comment]
这个是可以的，不过是否可以考虑使用yolov5等传统CNN方案作为识别 （合格，不合格）等判别方式（推理速度快），然后配合我们的Agent能力来做自动总结，归档（这部分传统小模型做不了）
