### ISSUE TITLE
请问训练数据开源了么

### ISSUE THREAD

**Issue by JohnTang93** [THUDM/CogVLM#223]
### Feature request  / 功能建议

请问有计划开源训练数据么，方便学术界follow

### Motivation / 动机

请问有计划开源训练数据么，方便学术界follow

### Your contribution / 您的贡献

请问有计划开源训练数据么，方便学术界follow

**Comment by zRzRzRzRzRzRzR** [comment]
会开放部分数据用于微调演示，完整数据尚未有相关计划
