### ISSUE TITLE
8卡24G 4090 finetune CogAgent-chat、CogVLM-base-490都报错OOM

### ISSUE THREAD

**Issue by zhenshen-mla** [THUDM/CogVLM#224]
### System Info / 系統信息

8卡24G 4090 finetune CogAgent-chat、CogVLM-base-490都报错OOM，看文档中8卡3090就可以支持finetune的呀

### Who can help? / 谁可以帮助到您？

null

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

null

### Expected behavior / 期待表现

null

**Comment by strawsyz** [comment]
我试了4*A100也不够用。batch size设为1也没用。
4*A100 is also not enough.

**Comment by Guodashen222** [comment]
我使用8张h100微调 agent也是这个问题，只有把batch从4改为1才可以

**Comment by 1049451037** [comment]
微调占用的显存与微调的参数量有关系，提供的脚本默认微调了几乎全参数，可以减少参数量来省显存：

https://github.com/THUDM/CogVLM/blob/390b7c6aad7381597cce4403f7d05c1874369a84/finetune_demo/finetune_cogagent_demo.py#L17

**Comment by zRzRzRzRzRzRzR** [comment]
更多的微调问题，可以移步 #270 进行讨论

**Comment by ghost** [comment]
> 微调占用的显存与微调的参数量有关系，提供的脚本默认微调了几乎全参数，可以减少参数量来省显存：
> 
> https://github.com/THUDM/CogVLM/blob/390b7c6aad7381597cce4403f7d05c1874369a84/finetune_demo/finetune_cogagent_demo.py#L17

请问CogAgent的lora微调是用的数据并行还是模型并行呢？用2*8V100（32G）共16张卡，batch size为1也会out of memory。
