### ISSUE TITLE
Base模型没有输出

### ISSUE THREAD

**Issue by linxid** [THUDM/CogVLM#226]
### System Info / 系統信息

系统信息：
Driver Version: 470.182.03 
CUDA Version: 11.4
python Version：3.11
Torch Version：2.0.1
Transformers：4.36.2

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

直接对cogvlm对图片进行推理。不同prompt会出现输出为空的情况。测试的图片包括自然场景和文档场景。
```shell
python basic_demo/cli_demo_hf.py --from_pretrained ./pre-trained/CogVLM/cogvlm-base-490-hf --local_tokenizer ./pre-trained/vicuna/vicuna-7b-v1.5 --bf16
```
Base模型的Prompt是什么，能否实现OCR任务。OCR任务是否需要用CogAgent模型。

### Expected behavior / 期待表现

什么样的prompt能复现base模型在论文中的性能。

**Comment by 1049451037** [comment]
base模型的prompt为空，且只能做image caption。

因为语言模型参数没有训练，所以也可以做纯文本对话。

**Comment by linxid** [comment]
感谢您的回复，几个问题想请教下。
1. `THUDM/cogvlm-base-490-hf` 这个weight是二阶段训练之后的模型吗？
2. 论文几个vqa数据集上的精度，是base模型的精度？如何复现论文中VQA的性能呢。
<img width="849" alt="image" src="https://github.com/THUDM/CogVLM/assets/16094085/aba9b26e-80e4-40a4-9270-96a776fe0483">
3. 模型`CogAgent-vqa`，prompt需要特殊设计吗。ocr任务和输出markdown任务的prompt是什么。我看到论文里面使用的是这个。

<img width="331" alt="image" src="https://github.com/THUDM/CogVLM/assets/16094085/b0a1f60f-3871-4c8f-9cb6-f8a10cbfa3da">

**Comment by 1049451037** [comment]
vqa需要使用cogvlm-chat-hf来复现，

inputs = model.build_conversation_input_ids(tokenizer, query=query, history=[], images=[image], template_version='vqa')

**Comment by linxid** [comment]
感谢回复。用cogagent来做ocr和生成markdown格式的标注，cogagent-vqa性能更好吗。然后，文档rendering，ocr，markdown，以及grounding，vqa任务，几个任务的prompt是什么呢。
