### ISSUE TITLE
CogAgent-Agent Weights Release?

### ISSUE THREAD

**Issue by Jiayi-Pan** [THUDM/CogVLM#227]
### Feature request  / 功能建议

Thank you for releasing this impressive project! 

However, on GitHub, I noticed that you released the two variants, "cogagent-chat" and "cogagent-vqa," whereas the Streamlit demo features "cogagent-chat" and "cogagent-agent." I'm curious if "cogagent-vqa" and "cogagent-chat" are the same. If not, do you plan to release the weights for "cogagent-agent"?

### Motivation / 动机

N/A

### Your contribution / 您的贡献

N/A

**Comment by zRzRzRzRzRzRzR** [comment]
cogagent is cogagent chat model with agent template task the model is same.Use template to activate model agent capability
