### ISSUE TITLE
CogAgent/CogVLM支持中文微调吗？请问后续有计划开源中文版/双语版吗？感谢！

### ISSUE THREAD

**Issue by LianghuiGuo** [THUDM/CogVLM#229]
### Feature request  / 功能建议

CogAgent/CogVLM支持中文微调吗？请问后续有计划开源中文版/双语版吗？感谢！

### Motivation / 动机

关于中文微调的疑问

### Your contribution / 您的贡献

关于中文微调的疑问

**Comment by zRzRzRzRzRzRzR** [comment]
我们会开放微调代码，但是暂时还没有开中文版本
