### ISSUE TITLE
4 bit quantization version available?

### ISSUE THREAD

**Issue by hugh-min** [THUDM/CogVLM#23]
RT

**Comment by sanbuphy** [comment]
+1

**Comment by Sleepychord** [comment]
Unfortunately, In our attempt, the 4-bit quantization works in NLP models (GLM, Llama etc) fails in ViTs (a huge loss TAT). This is still a research problem and we will look into it.

**Comment by 1049451037** [comment]
We now support 4-bit quantization now! See README for more details.
