### ISSUE TITLE
Fail to reproduce the result on MM-Vet

### ISSUE THREAD

**Issue by yu-rp** [THUDM/CogVLM#230]
Hi CogVLM Team,

Thank you for dedicating yourselves to such interesting work and generously sharing your valuable findings and models. I am indeed inspired and am trying to explore a little bit more on the shoulder of CogVLM.

I have attempted to reproduce your results on MM-Vet but have encountered some challenges.

**Changes** 

* I modified the `cli_demo.py` to read the images and questions from MM-Vet, instead of from command line input. 
* I set `temperature` to 1e-3.
* The prompt I used is  "Generate a short and concise response to the following image text pair. " + [Question]

**Result**

* The result I got is 49.8, whereas it was reported to be 52.8.

**Enquiry**

Could you please guide how to accurately reproduce your results?

Best

**Comment by mactavish91** [comment]
The prompt has some influence on the results. You don't need to use "Generate a short and concise response to the following image text pair." Instead, just input the original question, as some questions in the mm-vet dataset require longer responses.

Additionally, using beam search will yield higher scores.
```
strategy = BeamSearchStrategy(temperature=0.8, top_p=0.95, top_k=5, end_tokens=[tokenizer.eos_token_id],
                              num_beams=5, consider_end=True)
```

**Comment by zRzRzRzRzRzRzR** [comment]
for more reputation, can discuss in #273
