### ISSUE TITLE
Fail to output the bounding boxes of the objects

### ISSUE THREAD

**Issue by yu-rp** [THUDM/CogVLM#231]
Hi CogVLM Team,

Thank you for your fascinating work and for sharing your repo. I'm inspired and eager to build upon CogVLM's achievements.

As mentioned in the paper, Referring Expression Comprehension is used as one of the pretraining tasks. Therefore, I assumed that CogVLM could somehow preserve the ability to output the bounding boxes of objects. I prompted CogVLM with the following:

> Question: Where is the _object_?
> Answer: [[x0, y0, x1, y1]]

However, CogVLM failed to generate a valid bounding box. I have also tried several different types of prompts, but the issue persisted. Have you attempted to prompt CogVLM to generate bounding boxes? How can I achieve that?

Here are some examples illustrating my unsuccessful attempts.
![image](https://github.com/THUDM/CogVLM/assets/43113840/e310cb10-39bd-482e-893f-db8a3dfafa95)
![image](https://github.com/THUDM/CogVLM/assets/43113840/2154d18c-4f8c-4e09-ba87-208e262d9a9a)

Best

**Comment by 1049451037** [comment]
Ensure to choose the "Grounding" option bottom left corner.

![image](https://github.com/THUDM/CogVLM/assets/15194939/42fa18ac-f0bf-4bb5-b46b-7e86b3d0ea64)

**Comment by yu-rp** [comment]
Thank you for your instruction. Could you share how I can do this if I use the CLI scripts locally?

**Comment by 1049451037** [comment]
`--from_pretrained cogvlm-grounding-generalist-hf` if you use hf version

or

`--from_pretrained cogvlm-grounding-generalist-v1.1` if you use sat version

**Comment by yu-rp** [comment]
Thank you for your response. 

1. So this means what I only need to do is change the `--from_pretrained` parameter. Do I also need to use the prompts listed in the [Task Prompts](https://github.com/THUDM/CogVLM/tree/main?tab=readme-ov-file#task-prompts) section? Here is a screenshot of that part.

 ![image](https://github.com/THUDM/CogVLM/assets/43113840/4011293b-44a1-4bd3-848b-0e6bd48460f4)

2. Can I still do multiround chat with the model if I use `cogvlm-grounding-generalist-v1.1`?  For instance, continue exploring the image through multiple rounds of conversation. In some rounds, I may ask grounding-related questions, but in others, the questions may not involve grounding.

**Comment by 1049451037** [comment]
No. cogvlm-grounding-generalist-v1.1 cannot do multi-round chat. And you should set `--version base` if you use this checkpoint.

**Comment by yu-rp** [comment]
Thank you for your prompt response.

Do I also need to change the prompt I used? For example, using the prompts listed in the [Task Prompts](https://github.com/THUDM/CogVLM/tree/main?tab=readme-ov-file#task-prompts) section.

**Comment by 1049451037** [comment]
Yes.

**Comment by yu-rp** [comment]
Thank you for your kind assistance and explanations. I think I have all the information I need for now.
