### ISSUE TITLE
多图问答

### ISSUE THREAD

**Issue by jyC23333** [THUDM/CogVLM#234]
请问现在的模型是否支持多图问答？ @1049451037 

比如类似few-shot：
image1+question1+answer1 + image2+question2+answer2 + image3+question3 ---> answer3

如果想按照多图问答进行 finetune，需要怎么实现？

**Comment by 1049451037** [comment]
不支持，暂未实现，需要您自己实现一下。

**Comment by jyC23333** [comment]
@1049451037  明白，请问下我大概需要修改哪部分代码，能更快实现，有一些建议吗？

**Comment by zRzRzRzRzRzRzR** [comment]
现在的openai api 和composite demo都是 支持的，但是代价是你每次传入一个新的图，老的数据都会丢失（历史和图片）

**Comment by jyC23333** [comment]
@1049451037 @zRzRzRzRzRzRzR 
感谢，但是如果多张图像进行few-shot的话应该需要额外的训练吧？

```finetune_demo/finetune_cogvlm_demo.py```
这边的训练代码怎样进行适配呢？
