### ISSUE TITLE
Finetune Demo instructions inaccurate and missing pip packages 

### ISSUE THREAD

**Issue by z3ugma** [THUDM/CogVLM#237]
### System Info / 系統信息

Ubuntu 20.04.6 LTS
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
Python 3.11.7
torch.__version__'2.1.2+cu121'
deepspeed.__version__ '0.12.6'

### Who can help? / 谁可以帮助到您？

@1049451037 

it's a README and finetune problem 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. Git clone the CogVLM repo as stated 
2. `pip install -r requirements.txt` 
3. Download the Captcha `archive.zip` and unzip to a folder called `archive` at the root level of the CogVLM git directory on your system 
3. Using the instructions in README.md, try to follow them by doing: 

python utils/split_dataset.py 

this works fine. 

Then do `bash finetune_demo/finetune_cogvlm_lora.sh` 

## Error 1 - the `finetune_cogvlm_lora.sh` script points to the wrong file 

The script points to `finetune_cogvlm_demo.py` but that file is now nested inside of the `finetune_demo` folder. You need to add the folder path to the last line of the bash script: 
```
run_cmd="${OPTIONS_NCCL} ${OPTIONS_SAT} deepspeed --master_port 16666 --hostfile ${HOST_FILE_PATH} finetune_demo/finetune_cogvlm_demo.py ${gpt_options}"
```

## Error 2 - Several packages missing including complicated Apex
On initialization you need to pip install many things that are not in the requirements.txt 

Specifically, bitsandbytes, scipy, jsonlines, and nvidia apex which is not the same as doing pip install apex - that's a different package. 

```
pip install bitsandbytes scipy jsonlines
python -m spacy download en
git clone https://github.com/NVIDIA/apex.git && cd apex
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./

``` 
## Error 3 - quits with   FileNotFoundError: [Errno 2] No such file or directory: 'test_config_bf16.json'
Is this a relative import error too? 

### Expected behavior / 期待表现

Expectation: on a brand new Ubuntu 20.04 with fresh Python 3.11 mamba environment, I can run the finetune demo exactly as described in the README and have it work on the first try.

**Comment by 1049451037** [comment]
You can `cd finetune_demo`. Then run `bash finetune_cogvlm_lora.sh`.

**Comment by z3ugma** [comment]
Ok, that solves for error 1 and error 3, but that's what the instructions say (yet) for other visitors to the repo. 

and for error 2 - the requirements file still does not have all the required packages to run the finetune

**Comment by zRzRzRzRzRzRzR** [comment]
any finetune problem can discussion in #270 for community support  because we could not reproduce
