### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by ageorgios** [THUDM/CogVLM#239]
### Feature request  / 功能建议

Is Mac Suported? (Apple Sillicon)

### Motivation / 动机

run locally on Macs

### Your contribution / 您的贡献

https://github.com/ml-explore/mlx

**Comment by 1049451037** [comment]
Yes, just change `decive='cuda'` to `device='mps'`.

**Comment by zRzRzRzRzRzRzR** [comment]
It is only support mps not mlx ，you can replace pytorch backend as mps

**Comment by WillCMcC** [comment]
@ageorgios @zRzRzRzRzRzRzR are you able to get this running on mps? I am running into issues with memory_efficient_attention

**Comment by davidospinap** [comment]
@WillCMcC did you manage to make this run? getting the same error with memory

**Comment by sharedcare** [comment]
@WillCMcC I think it is a problem with xformers, you can replace this function with [memory-efficient-attention-pytorch](https://github.com/lucidrains/memory-efficient-attention-pytorch).
