### ISSUE TITLE
Cannot load finetuned CogAgent checkpoints & cannot save merged LoRA checkpoints

### ISSUE THREAD

**Issue by theo-pencisalo** [THUDM/CogVLM#240]
### System Info / 系統信息

cuda version: 11.8
HuggingFace `transformers` library version: 4.35.2
SwissArmyTransformer version: 0.4.8
Python version: 3.10.13
Operating system: Ubuntu 22.04.3 LTS

### Who can help? / 谁可以帮助到您？

@1049451037 

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

My modifications:
1. Added `py_parser.add_argument('--use_qlora', action="store_true", default=True)` in finetune_demo.py
2. Added some comments in finetune_demo.py
Step 1: Finetune the SAT model with QLoRA. 
Step 2: Try to merge LoRA with:
```python
if args.use_lora:
        model.get_mixin("lora").merge_lora()
        model.get_mixin("eva").vit_model.get_mixin("lora").merge_lora()
        args.use_lora = False
        args.save = "/storage/merged_lora_cogagent"
        from sat.training.model_io import save_checkpoint
        save_checkpoint(1, model, None, None, args)
```
Based on issue #142.
This is the trace back:
```
[2023-xx-xx xx:xx:xx,xxx] [INFO] [RANK 0] Saving Model...
INFO:sat:[RANK 0] Saving Model...
Traceback (most recent call last):
  File "/home/user/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 294, in <module>
    save_checkpoint(1, model, None, None, args)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/sat/training/model_io.py", line 117, in save_checkpoint
    save_ds_checkpoint(iteration, model, lr_scheduler, args)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/sat/training/model_io.py", line 159, in save_ds_checkpoint
    save_ds_checkpoint_no_optim(model, args.save, str(iteration), client_state=sd)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/sat/training/model_io.py", line 169, in save_ds_checkpoint_no_optim
    model._create_checkpoint_file(save_dir, tag, False)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'FineTuneTrainCogAgentModel' object has no attribute '_create_checkpoint_file'
```

I opened the implementation of CogAgent in `util.models`, and then looked into `SwissArmyTransformer`'s Llama2(LLaMA) implementation. It seems that there isn't a `_create_checkpoint_file()` anywhere. The strange thing is, during the finetuning run the same command could save the model without any problem.
Additionally, I encountered the same missing key problem as reported in issue #208 when trying to load finetuned LoRA models, even after added 
```python
model.get_mixin("lora").merge_lora()
model.get_mixin("eva").vit_model.get_mixin("lora").merge_lora()
``` 
immediately after the loading of the model. Since there is already one issue, I didn't open another issue, but only briefly mention it here. My guess is that the high resolution vision encoder LoRA may not get merged properly, since issue #142 is older than the release of CogAgent. However, 

### Expected behavior / 期待表现

The LoRA should be merged into the model and saved to a file. Alternatively, the LoRA should be merged into the model when preparing the model for inference.

**Comment by 1049451037** [comment]
Please ensure `args.deepspeed = None` and `args.mode = 'inference'`, because only deepspeed model has the `_create_checkpoint_file` function, which occurs at training stage.

**Comment by theo-pencisalo** [comment]
Thank you for the response! I can merge LoRA and save model without a problem now!
