### ISSUE TITLE
在预测时可以batch输入吗？

### ISSUE THREAD

**Issue by Sun-light-W** [THUDM/CogVLM#243]
### Feature request  / 功能建议

请问在预测时可以batch输入吗，eg.输入q1+img1、q2+img2,输出output1、output2

### Motivation / 动机

null

### Your contribution / 您的贡献

null

**Comment by 1049451037** [comment]
hf支持

**Comment by zRzRzRzRzRzRzR** [comment]
hf代码中支持batch输入的

**Comment by Sun-light-W** [comment]
已看到，谢谢~

**Comment by trouble-maker007** [comment]
@Sun-light-W @zRzRzRzRzRzRzR Is Is there an example of input that I can refer to? I can't find the corresponding code. Thank you.
