### ISSUE TITLE
Error shows on the GUI

### ISSUE THREAD

**Issue by hanswang1** [THUDM/CogVLM#244]
### System Info / 系統信息

A100(40G) 
PyTorch 2.1.2 + CUDA 11.8

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![cogvlm-error](https://github.com/THUDM/CogVLM/assets/6904705/68a44023-84d8-41ca-a00c-50f1e0df3d63)
![cogvlm-backend](https://github.com/THUDM/CogVLM/assets/6904705/33c75b66-23e4-4b4f-9b43-52b380013734)

An error shows on GUI and no tips from the back end.

### Expected behavior / 期待表现

The GUI runs smoothly.

**Comment by zRzRzRzRzRzRzR** [comment]
maybe can try streamlit demo

**Comment by Gae-Zhang** [comment]
> maybe can try streamlit demo

请问demo现在还可以正常运行吗，不知道为什么，无论我怎么调整输入，输出总是error
![捕获](https://github.com/THUDM/CogVLM/assets/55022685/22d986e5-c57e-4670-ad68-f33841674d64)

**Comment by ImmNaruto** [comment]
相同的问题，int4量化版本跑cogagent的web_demo，控制台无任何报错但是GUI显示error

**Comment by ImmNaruto** [comment]
试下高版本的gradio,亲测3.42.0可以
