### ISSUE TITLE
batch输入速度没有提升

### ISSUE THREAD

**Issue by Sun-light-W** [THUDM/CogVLM#247]
### Feature request  / 功能建议

用3张A10卡部署，使用hf版，batch输入多个input和input逐个输入，推理所需的总时间差不多，而且batch输入耗时波动不稳定，是显存不够的原因吗

### Motivation / 动机

null

### Your contribution / 您的贡献

null

**Comment by 1049451037** [comment]
batch输入是否有提升取决于不同样本生成的长度的方差。如果方差很大，有的很长有的很短，那用batch反而会降低速度。

**Comment by Sun-light-W** [comment]
用的时候感觉受最长输出的影响，果然是这样，感谢大佬~
