### ISSUE TITLE
the format of coordinate

### ISSUE THREAD

**Issue by peiliu0408** [THUDM/CogVLM#25]
As mentioned in papers and web_demo scripts, the coordinates of each box are presented in the format [[bin_1_x, bin_1_y, bin2_x, bin_2_y]]. whether each bin representing a three-digit number?

Furthermore, are there any additional special tokens employed when handling tasks related to coordinates?

**Comment by 1049451037** [comment]
Yes, each bin represents a three-digit number, which is the proportion of the width or height * 1000.

There is no special tokens for coordinates.

**Comment by peiliu0408** [comment]
thanks for your kind reply. 
I am curious if only Ref3 and visual7w, coordinate related datasets, are being used? for its awesome performing on RefCoCo test split.

**Comment by 1049451037** [comment]
We use Flickr30k Entities, Ref3, Visual7W and GC_genome. These training sets can all be found in [shikra dataset](https://github.com/shikras/shikra/blob/main/docs/data.md)

**Comment by peiliu0408** [comment]
thanks  a lot. I have another question about coordinate representation.  if one ref phrase corresponding multiple coords, just concat all of these coord strings together, like [[coord_1]][[coord_2]] ?

**Comment by 1049451037** [comment]
It's [[coord_1;coord_2]]. You can refer to `utils/parser.py`.

**Comment by njucckevin** [comment]
> For grounding-base, we use clay1b and laion40m, which introduced in paper.
> 
> For grounding-generalist, we use Flickr30k Entities, Ref3, Visual7W and GC_genome based on grounding-base. These training sets can all be found in [shikra dataset](https://github.com/shikras/shikra/blob/main/docs/data.md).

@1049451037 Hi, what is the clay1b dataset? I can't find it in the paper. thanks~
