### ISSUE TITLE
Quantised models (4, 8)

### ISSUE THREAD

**Issue by ageorgios** [THUDM/CogVLM#250]
### Feature request  / 功能建议

Need already quantised models for MacOS users where bitsandbytes is not supported

### Motivation / 动机

bitsandbytes is not supported on MacOS

### Your contribution / 您的贡献

https://github.com/ml-explore/mlx

**Comment by 1049451037** [comment]
Quantized models rely on bitsandbytes for hf version, not only in memory, but also computation when running forward pass.

**Comment by zRzRzRzRzRzRzR** [comment]
mark
