### ISSUE TITLE
如何多卡int推理

### ISSUE THREAD

**Issue by Sun-light-W** [THUDM/CogVLM#251]
### Feature request  / 功能建议

我使用多卡进行batch推理，出于优化推理速度和显存占用，我想使用int4推理，但是在.from_pretrained中加入load_in_4bit=True,后，运行时会自动把模型加载的gpu上，而不是先加载到cpu，然后通过device_map分配到gpu上，导致程序无法正常运行，如下：
with init_empty_weights():
    model = AutoModelForCausalLM.from_pretrained(
                '/home/work/code/model/cogvlm-chat-hf',
                torch_dtype=torch.bfloat16,
                load_in_4bit=True,
                low_cpu_mem_usage=True,
                trust_remote_code=True,
            )

device_map = infer_auto_device_map(model, max_memory={1:'12GiB',2:'12GiB',4:'12GiB',5:'15GiB'}, no_split_module_classes=['CogVLMDecoderLayer', 'TransformerLayer'])
model = load_checkpoint_and_dispatch(
    model,
    '/home/model/cogvlm-chat-hf',   # typical, '~/.cache/huggingface/hub/models--THUDM--cogvlm-chat-hf/snapshots/balabala'
    device_map=device_map,
)
model = model.eval()

### Motivation / 动机

null

### Your contribution / 您的贡献

null

**Comment by 1049451037** [comment]
Try `device_map="auto"`. 

```python
model = AutoModelForCausalLM.from_pretrained(
    '/home/work/code/model/cogvlm-chat-hf',
    torch_dtype=torch.bfloat16,
    load_in_4bit=True,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    device_map="auto"
    )
```

**Comment by Sun-light-W** [comment]
报错如下，这个错误经常出现，之前调整显存分配会解决
Traceback (most recent call last):
  File "inference_batch.py", line 55, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/work/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/home/work/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3396, in from_pretrained
    max_memory = get_balanced_memory(
  File "/home/work/.local/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 771, in get_balanced_memory
    max_memory = get_max_memory(max_memory)
  File "/home/work/.local/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 643, in get_max_memory
    _ = torch.tensor([0], device=i)
RuntimeError: CUDA error: uncorrectable ECC error encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by 1049451037** [comment]
那就试一下：

```python
model = AutoModelForCausalLM.from_pretrained(
    '/home/work/code/model/cogvlm-chat-hf',
    torch_dtype=torch.bfloat16,
    load_in_4bit=True,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    device_map= infer_auto_device_map(model, max_memory={1:'12GiB',2:'12GiB',4:'12GiB',5:'15GiB'}, no_split_module_classes=['CogVLMDecoderLayer', 'TransformerLayer'])
    )
```

**Comment by Sun-light-W** [comment]
这个试过，会自动全加载到第一张卡上

**Comment by Sun-light-W** [comment]
device_map="auto"的方式是有效的，通过调整使用的gpu，os.environ["CUDA_VISIBLE_DEVICES"] = "2,3,4,5"，最终可以跑通了~

**Comment by chopin1998** [comment]
> device_map="auto"的方式是有效的，通过调整使用的gpu，os.environ["CUDA_VISIBLE_DEVICES"] = "2,3,4,5"，最终可以跑通了~

您好， 这样确实可以加载模型， 但是依然无法推理呀，，，

在
```
 with torch.no_grad():
    ...:             outputs = model.generate(**inputs, **gen_kwargs)
    ...:             outputs = outputs[:, inputs['input_ids'].shape[1]:]
    ...:             response = tokenizer.decode(outputs[0])
    ...:             response = response.split("</s>")[0]
    ...:             print("\nCog:", response)
```
这里会产生错误
`/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in _wrapped_call_impl(self, *args, **kwargs)
   1516             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517         else:
-> 1518             return self._call_impl(*args, **kwargs)
   1519 
   1520     def _call_impl(self, *args, **kwargs):

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in _call_impl(self, *args, **kwargs)
   1525                 or _global_backward_pre_hooks or _global_backward_hooks
   1526                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527             return forward_call(*args, **kwargs)
   1528 
   1529         try:

~/.cache/huggingface/modules/transformers_modules/cogagent-chat-hf/visual.py in forward(self, images)
    133         boi = self.boi.expand(x.shape[0], -1, -1)
    134         eoi = self.eoi.expand(x.shape[0], -1, -1)
--> 135         x = torch.cat((boi, x, eoi), dim=1)
    136         return x

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:3! (when checking argument for argument tensors in method wrapper_CUDA_cat)

`

**Comment by 1049451037** [comment]
刚刚修复了这个bug，可以pull一下最新的huggingface代码试试。

**Comment by linxid** [comment]
batch推理是否有示例的脚本，数据集部分应该如何 输入
