### ISSUE TITLE
openai_demo runs on multiple graphics cards

### ISSUE THREAD

**Issue by tangxiangyu0313** [THUDM/CogVLM#254]
### Feature request  / 功能建议

Thank you very much for your excellent work, but my single graphics card memory is not enough, can you provide openai_demo running on multiple graphics cards。

### Motivation / 动机

None

### Your contribution / 您的贡献

None

**Comment by xzhxzhxzhxzhxzh** [comment]
Hi, you can find the solution code in their huggingface repository (for cogvlm). That works very well!

**Comment by tangxiangyu0313** [comment]
> Hi, you can find the solution code in their huggingface repository (for cogvlm). That works very well!

OK，I will do it. Thanks for your reply.

**Comment by tangxiangyu0313** [comment]
> Hi, you can find the solution code in their huggingface repository (for cogvlm). That works very well!
I tried to modify openai_api.py according to huggingface repository, but now this problem occurs, what should I do
![image](https://github.com/THUDM/CogVLM/assets/44080864/1eec0afa-3c82-4285-85e2-ecb1954ef3ec)
The code I modified is as follows
`with init_empty_weights():
            model = AutoModelForCausalLM.from_pretrained(
            MODEL_PATH,
            torch_dtype=torch.bfloat16,
            low_cpu_mem_usage=True,
            trust_remote_code=True,
            )
        device_map = infer_auto_device_map(model, max_memory={0:'16GiB',1:'16GiB',2:'16GiB',3:'16GiB','cpu':'16GiB'}, no_split_module_classes=['CogVLMDecoderLayer', 'TransformerLayer'])
        model = load_checkpoint_and_dispatch(
            model,
            MODEL_PATH,   # typical, '~/.cache/huggingface/hub/models--THUDM--cogvlm-chat-hf/snapshots/balabala'
        device_map=device_map,)
        model = model.eval()
        for n, p in model.named_parameters():
            print(f"{n}: {p.device}")`

**Comment by tangxiangyu0313** [comment]
`with init_empty_weights():
            model = AutoModelForCausalLM.from_pretrained(
            MODEL_PATH,
            torch_dtype=torch.bfloat16,
            low_cpu_mem_usage=True,
            trust_remote_code=True,
            )
        device_map = infer_auto_device_map(model, max_memory={0:'16GiB',1:'16GiB',2:'16GiB',3:'16GiB','cpu':'16GiB'}, no_split_module_classes=['CogVLMDecoderLayer', 'TransformerLayer'])
        model = load_checkpoint_and_dispatch(
            model,
            MODEL_PATH,   # typical, '~/.cache/huggingface/hub/models--THUDM--cogvlm-chat-hf/snapshots/balabala'
        device_map=device_map,)
        model = model.eval()
        for n, p in model.named_parameters():
            print(f"{n}: {p.device}")`
            
         我尝试做如上修改，但是出现了报错，请问有什么办法呢？
         
![image](https://github.com/THUDM/CogVLM/assets/44080864/199a541d-8a45-429e-bae1-57c75bb712c4)

**Comment by zRzRzRzRzRzRzR** [comment]
may be you can try with device_map with  "auto" or 4 bit model , openai server just a backend , will not be affect by model loading

**Comment by tangxiangyu0313** [comment]
![image](https://github.com/THUDM/CogVLM/assets/44080864/8d98c7d5-43a5-4e87-99e3-cdf9cd9863dd)
我尝试按照huggingface做修改，但是出现了报错，请问有没有办法解决呢？报错如下：
![image](https://github.com/THUDM/CogVLM/assets/44080864/fc980173-4001-498e-955a-93f6c2ab0009)

**Comment by tangxiangyu0313** [comment]
我尝试按照huggingface做了如下修改，但是出现了报错，我该如何处理？
![image](https://github.com/THUDM/CogVLM/assets/44080864/9249c54b-e85d-4b13-8479-6d015486e282)
![image](https://github.com/THUDM/CogVLM/assets/44080864/f6689b8a-17d4-45b8-9459-f4318c6d723d)

**Comment by tangxiangyu0313** [comment]
> may be you can try with device_map with "auto" or 4 bit model , openai server just a backend , will not be affect by model loading
If I set "device_map" to" auto", the following error occurs

![image](https://github.com/THUDM/CogVLM/assets/44080864/ee608fac-a666-4b51-abba-c906e828ad9a)
![image](https://github.com/THUDM/CogVLM/assets/44080864/3fc9f738-d2c4-4d63-a13e-6e91e9823307)

and When I set "load_in_4bit" to "True", I get the following error
![image](https://github.com/THUDM/CogVLM/assets/44080864/e829dc40-07b4-435d-bfba-d4527661af55)
![image](https://github.com/THUDM/CogVLM/assets/44080864/0c0a5c29-2a4c-40b0-9d8b-8ea62b3c7f3a)

**Comment by tangxiangyu0313** [comment]
I ended up using 2 graphics cards and successfully running open_api.py. If I used more graphics cards (4), it would report the following error. Only using 2 graphics cards is successful.
![image](https://github.com/THUDM/CogVLM/assets/44080864/494154ae-c309-4fde-ba2a-c8e3b36f1fa2)
![image](https://github.com/THUDM/CogVLM/assets/44080864/fd4b0597-842e-4613-b1e2-76b24cb33d37)
