### ISSUE TITLE
加载CogVLM agent模型时提示Some weights of CogAgentForCausalLM were not initialized from the model checkpoint

### ISSUE THREAD

**Issue by ZhuangPeiyu** [THUDM/CogVLM#255]
在运行python cli_demo_hf.py --from_pretrained THUDM/cogvlm-chat-hf --quant 4这段代码加载模型进行推理时，报了Some weights of CogAgentForCausalLM were not initialized from the model checkpoint 自己的模型路径 are newly initialized: ['model.cross_vision.vit.model.blocks.2.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.23.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.6.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.0.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.21.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.10.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.18.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.3.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.14.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.2.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.18.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.11.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.15.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.13.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.5.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.8.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.16.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.20.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.11.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.12.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.9.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.6.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.20.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.21.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.15.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.0.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.10.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.16.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.7.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.23.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.13.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.1.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.1.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.17.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.4.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.5.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.9.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.4.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.19.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.12.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.17.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.14.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.22.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.8.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.3.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.7.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.22.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.19.attn.rope.freqs_cos']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

我的权重是在hugging face上面下载的，这个是否是因为权重中没有包含cross vision的参数？这是否会影响模型的推理性能？

**Comment by 1049451037** [comment]
cogvlm-chat-hf并没有cross attention，你是不是选错模型了。

**Comment by ZhuangPeiyu** [comment]
感谢你的回复。
我下载的权重是CogAgent-chat-hf：https://huggingface.co/THUDM/cogagent-chat-hf/tree/main。
然后调用是这么调：python cli_demo_hf.py --from_pretrained ./CogAgent/checkpoints/ --quant 4。
然后就提示上面的问题。

**Comment by 1049451037** [comment]
没有影响

**Comment by zRzRzRzRzRzRzR** [comment]
这个是不影响的，是警告，可以正常使用

**Comment by ZhuangPeiyu** [comment]
好的，谢谢。

**Comment by hgospodar** [comment]
我也遇到同样的问题，我使用下面的命令行运行模型
`python cli_demo_hf.py --from_pretrained /data1/lhg/cogagent-chat-hf --bf16`
但是出现了下面的警告
`['model.cross_vision.vit.model.blocks.0.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.0.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.1.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.1.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.10.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.10.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.11.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.11.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.12.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.12.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.13.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.13.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.14.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.14.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.15.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.15.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.16.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.16.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.17.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.17.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.18.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.18.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.19.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.19.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.2.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.2.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.20.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.20.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.21.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.21.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.22.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.22.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.23.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.23.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.3.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.3.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.4.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.4.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.5.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.5.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.6.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.6.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.7.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.7.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.8.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.8.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.9.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.9.attn.rope.freqs_sin']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
`
并且出现上面的警告后就**没有其他提示**了，我在源代码中添加了debug输出
```
if args.quant:
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH,
        torch_dtype=torch_type,
        low_cpu_mem_usage=True,
        load_in_4bit=True,
        trust_remote_code=True
    ).eval()
else:
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH,
        torch_dtype=torch_type,
        low_cpu_mem_usage=True,
        load_in_4bit=args.quant is not None,
        trust_remote_code=True,
        device_map='auto',
    ).to(DEVICE).eval()

text_only_template = "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: {} ASSISTANT:"
print("load model success!!")
```
也就是最后一行load model success，但是最后也没有输出这个debug语句，所以这个可能是出了什么问题呢？
