### ISSUE TITLE
Specifications on the output of CogAgent-Agent (grounding)

### ISSUE THREAD

**Issue by Jiayi-Pan** [THUDM/CogVLM#259]
### Feature request  / 功能建议

Thank you for this nice project. I am interested in reproducing your experiment results on the android-in-the-wild (AitW) GUI navigation tasks. And for that, I need a mapping from your model's output to AitW's action space.

I know from the readme that I should be looking for model's output after `Grounded Operation:`, for example, `Grounded Operation:tap [[681,808]]`. However, it's hard to guess the entire action space by simply guessing.

Therefore, I wonder if you can provide a specification on how the action space is exactlly defined and how to parse them into AitW specifications?

### Motivation / 动机

Improve reproducibility

### Your contribution / 您的贡献

N/A

**Comment by zRzRzRzRzRzRzR** [comment]
Based on the format of our current training dataset, we can only produce outputs in a fully linguistic format for now. Therefore, we have formatted the output to achieve the current effect. The notation like tap [[681,808]] actually refers to pressing a specific button. Typically, actions like tap and similar are not very frequent and have a certain repetitiveness. In our future work, we will improve this aspect, aiming to achieve better formatting and standardized outputs.
