### ISSUE TITLE
CogAgent bulding script error when no image is given

### ISSUE THREAD

**Issue by LumenYoung** [THUDM/CogVLM#260]
### System Info / 系統信息

Dear team at THUDM, 

Thanks for your amazing work. I find that the cogagent model have problem when no image is provided. This seems to be a very trival problem but modifying it locally seems not a good idea. 

``` 
 File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogagent-vqa-hf/bb6c74004d38f5cd202654840ed21220c3408336/modeling_cogagent.py", line 973, in build_conversation_input_ids
    'cross_images': cross_images
UnboundLocalError: local variable 'cross_images' referenced before assignment
```

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

The reproduction is simple:

1. load model THUDM/cogagent-vqa-hf
2. run a inference without providing image

### Expected behavior / 期待表现

It should runs successfully without image

**Comment by zRzRzRzRzRzRzR** [comment]
you must input with a image, for multi-round  conversation, need to send the same image every time

**Comment by nnWhisperer** [comment]
Hello, I saw this thread and have a the exact same error, so I wanted to clarify: As far as I understood, the cogagent permits multi turn dialogues as long as you give an image and even if no image exists in the proceeding conversations, the first image must be kept. This behavior is different than GPT-4V, where we can give different images and also allowed for no-images. Hence, I want to ask: could you confirm that it isn't possible use the cogagent for a no-image chat, for example in planning for future actions step, where no image is input to the model? I tried to use it and received the error. Thank you
