### ISSUE TITLE
How to pick out multiple copies of the item.

### ISSUE THREAD

**Issue by husnoo** [THUDM/CogVLM#261]
### System Info / 系統信息

![image](https://github.com/THUDM/CogVLM/assets/2923338/e79ac496-ff1f-4c10-8173-b3e70671c502)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Use the web demo.

### Expected behavior / 期待表现

Multiple items.

**Comment by 1049451037** [comment]
If you use cogvlm-grounding-generalist, you can try hacking it with:

```
Where is all bolt?
```

Then the model says:

```
Where is all bolt? [[596,267,628,324]]
```

Then, you can use the truncated prompt to make it output more:

```
Where is all bolt? [[596,267,628,324;
```

Then the model will say:

```
Where is all bolt? [[596,267,628,324;xxx,xxx,xxx,xxx]]
```

(xxx means another bolt)
