### ISSUE TITLE
Remove xformers as dependency

### ISSUE THREAD

**Issue by nathanodle** [THUDM/CogVLM#262]
### Feature request  / 功能建议

Having xformers as an integral part of the model infrastructure is effectively locking CogVLM to CUDA as xformers only supports CUDA.  How hard is it to remove xformers as a dependency?

### Motivation / 动机

I would like to run CogVLM inference on other hardware platforms like Intel GPUs
In today's environment, it's important to have a choice of hardware and not be locked to a single vendor

### Your contribution / 您的贡献

a

**Comment by 1049451037** [comment]
It's... a bit hard to do that, because different attention implementations may have slight deviation error. We have already tried to replace the attention with normal torch implementation, but the output of model will have error around 1e-1.
