### ISSUE TITLE
六张3090显卡微调报错AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by zhangxilin1** [THUDM/CogVLM#264]
### System Info / 系統信息

pytorch-1.12.1 
 python3.8  
cuda11.6  
ubuntu20.04

### Who can help? / 谁可以帮助到您？

@1049451037 六张3090显卡微调报错AttributeError: 'NoneType' object has no attribute 'split'
![image](https://github.com/THUDM/CogVLM/assets/132734093/13c1915f-1518-4845-bf5e-42aaab630835)
已近进来一部分数据了，然后language文件中的这一行报错没有split方法，这是怎么回事
数据是我们自己的数据集，输入格式就是QA和“promot”
![image](https://github.com/THUDM/CogVLM/assets/132734093/5f6bc651-123d-4061-a213-a6cada60eb95)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

  我把你的文本输入部分修改成我自己的输入
        # text
        json_path = data.replace('.png', '.json')  # 根据图片位置，找到对应的json
        # 读取 JSON 文件内容
        with open(json_path, 'r') as file:
            json_data = json.load(file)
        text_dict = {}
        label = None
        prompt = ''
        uni_key = None
        # 寻找ID为1或者2的条目，因为有的没有id=1
        for entry in json_data:
            if entry["id"] == 1 or entry["id"] == 2:
                text = entry["text"].replace(" ", "")  # 删除空格
                position = [int(round(coord)) for coord in entry["position"]] # 精确到int
                # 结合文本和位置坐标
                label = f"{position}"
                prompt = f"{text}"
                uni_key = position
                break
        print("这是promot")
        print(prompt)
        print("这是label")
        print(label)
        
        text_dict = self.process_text(label, 'position')     

### Expected behavior / 期待表现

split那个报错讲解一下

**Comment by zRzRzRzRzRzRzR** [comment]
那么你的数据集构造部分应该根据我们的内容进行构建，你这个是有对话的，你查看一下process_text是怎么切割的，用pdb调试吧
更多的微调问题可以访问 #270 进行讨论
我们会在不久之后推出hf模型的对话微调
