### ISSUE TITLE
Need help with CogVLM_Grounding

### ISSUE THREAD

**Issue by banzhuan37** [THUDM/CogVLM#266]
### Feature request  / 功能建议

Hi there, really appreciate for the amazing job you guys bring to the community.
Is there any plan for you to update the finetuning of grounding model, for tasks that identify unseen objects.

### Motivation / 动机

Giving model the ability to localize unseen objects

### Your contribution / 您的贡献

code review

**Comment by zRzRzRzRzRzRzR** [comment]
yes we will release finetune demo of huggingface soon，for now you can use sat in fintune demo
