### ISSUE TITLE
Expecting LLaVA-Instruct dataset via mannual annotation

### ISSUE THREAD

**Issue by Yuqifan1117** [THUDM/CogVLM#27]
Very fantastic work! Thank you so much for your open source work!

I am mainly interested in the high-quality **LLaVA-Instruct dataset via manual inspection and annotation** for the SFT in the second stage of training. May I ask if I can obtain this part of training data from you? my email is 1138414330@qq.com.

This will be a great help to me, and I'm looking forward to your early reply!

**Comment by Sleepychord** [comment]
Sorry, we cannot open source the sft data according to the rules of our org.

**Comment by Yuqifan1117** [comment]
I only need the LLaVA-Instruction part for evaluation and personal use, is that OK according to your rules?

**Comment by iyuge2** [comment]
@Yuqifan1117 Hi, you can download the official LLaVA-Instruction from https://github.com/haotian-liu/LLaVA/blob/main/docs/Data.md. The version via manual inspection and annotation is not included in our open source plan.

**Comment by Yuqifan1117** [comment]
Okay thanks! If you have any planned changes in the manually inspection version, please inform me by emall in time! Very thanks!
