### ISSUE TITLE
HF For web_demo with Quant Option?

### ISSUE THREAD

**Issue by chigkim** [THUDM/CogVLM#271]
### Feature request  / 功能建议

It would be great to have web_demo that can load huggingface model with quant option.

### Motivation / 动机

There's cli_demo_hf.py with quant option, but not for web_demo.

### Your contribution / 您的贡献

N/A

**Comment by zRzRzRzRzRzRzR** [comment]
try use tf load-in-4bit, we wrote it in composite demo

**Comment by chigkim** [comment]
Could you put the command and options to use composite_demo in the readme?

I tried `streamlet run composite_demo/main.py` and opened the URL, but nothing shows up other than streamlet in the title of the page.
