### ISSUE TITLE
如何微调可以使得模型拥有定位能力

### ISSUE THREAD

**Issue by zhangxilin1** [THUDM/CogVLM#272]
### System Info / 系統信息

cogvlm的版本cogvlm-grounding-generalist，是用什么样的数据训练出可以提供坐标的能力的，我想自己微调一个定位版本，不知道应该输入什么样的数据

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

无

**Comment by 1049451037** [comment]
就是常规的文本对话数据，在cogvlm-grounding里坐标就是正常的自然语言文本。

**Comment by zRzRzRzRzRzRzR** [comment]
更多的问题可以移步 #270 讨论
