### ISSUE TITLE
Comparison with GPT-4V.

### ISSUE THREAD

**Issue by abrichr** [THUDM/CogVLM#276]
### Feature request  / 功能建议

Hello, congratulations on the excellent work, and thank you for making it open source!

The paper contains no direct comparison with GPT-4V. However, in the README it says:

> CogVLM sometimes captures more detailed content than GPT-4V(ision).

Are you able to provide more details regarding the performance of CogAgent compared to that of GPT4-V? In particular, it would be useful to know how CogAgent compares against Set-of-Mark prompting with GPT4-V: https://arxiv.org/abs/2310.11441

### Motivation / 动机

Completeness

### Your contribution / 您的贡献

N/A

**Comment by Sleepychord** [comment]
Thanks, we will compare our model with GPT-4V in the future. When we release the models. GPT-4V has no accessible API so we did not compare with it.

**Comment by abrichr** [comment]
@Sleepychord thanks for the update!

>  GPT-4V has no accessible API 

It does now: https://gist.github.com/abrichr/259b83b72fe0055d4f27ca9b3d387bc7 😄
