### ISSUE TITLE
VQA model image size 

### ISSUE THREAD

**Issue by aamir-gmail** [THUDM/CogVLM#278]
### Feature request  / 功能建议

In your git hub repo you mentioned the VQA model support higher resolution image of size 1120 px , however in the config file of  your HF repo "THUDM/cogagent-vqa-hf" , the config file says  "image_size": 224
![cog_1](https://github.com/THUDM/CogVLM/assets/37855753/e8dc15b6-082b-4cf1-8514-2570de868473)
![cog_2](https://github.com/THUDM/CogVLM/assets/37855753/28418865-c79a-42a2-9055-06673c11915d)

### Motivation / 动机

I wish to use higher resolution images of size 1120 px

### Your contribution / 您的贡献

I do not have one this was just question .

**Comment by zRzRzRzRzRzRzR** [comment]
"image_size": 224 is the size of the low-resolution channel
"cross_image_size": 1120, medium means high resolution, and in actual use it is 1120

**Comment by aamir-gmail** [comment]
> "image_size": 224 is the size of the low-resolution channel "cross_image_size": 1120, medium means high resolution, and in actual use it is 1120

Thank you .
