### ISSUE TITLE
使CogAgent进行多轮图文对话？

### ISSUE THREAD

**Issue by truebit** [THUDM/CogVLM#279]
### Feature request  / 功能建议

增加多幅图的对话session能力

### Motivation / 动机

目前cli_demo_hf和open_ai_request中的对话都只能进行一轮，即1张图片，多次文字对话。
但是依照https://zhipu-ai.feishu.cn/wiki/Pr7KwjS7WixAL6kBGSecD8MGnEc中的描述，CoAgent可以进行多轮图文对话。这也是UI Agent的正常使用方式。

目前看cli_demo_hf中可以插入多张图片，但是代码中仅插入了一张图片[image]。同理open_ai_request中images也只取了一张图片image_list[-1]。

看[README中的例子](https://github.com/THUDM/CogVLM/tree/main#gui-agent-examples)和[飞书中的例子](https://zhipu-ai.feishu.cn/wiki/Pr7KwjS7WixAL6kBGSecD8MGnEc)，CogAgent都是进行多轮图片+文字的对话实现的。

### Your contribution / 您的贡献

由于无法获知`model.build_conversation_input_ids`中images入参的处理方式，不知道是否可以直接在images参数传入多张图片？目前demo中仅用一张图片的原因是什么？

**Comment by truebit** [comment]
另外看代码中对图像和文字历史处理的方式，图片没有以占位符形式与文字历史进行对应。历史问题与回答是否能被正确解析呢？

**Comment by wenyihong** [comment]
现有的模型仅支持单张图片输入，但可以针对单张图片进行多轮的文本对话。

**Comment by truebit** [comment]
> 现有的模型仅支持单张图片输入，但可以针对单张图片进行多轮的文本对话。

那就是说，操作完成后的新截图，对话也是重新开始的。也就是每次新的图片，都需要人为把之前的历史对话附在当前对话中？

**Comment by wenyihong** [comment]
是的，如果需要使用到之前图片的对话记录，您可能需要修改一下代码

**Comment by truebit** [comment]
> 是的，如果需要使用到之前图片的对话记录，您可能需要修改一下代码

我已经改了，不过不了解`build_conversation_input_ids`中的操作，不知道这样传入的图像是否能被模型正确识别。图像和对话好像没有用占位符之类的形式进行一一匹配，不知道下面这种改法是否有用：

```
 input_by_model = model.build_conversation_input_ids(tokenizer, query=query, history=history,
                                                        images=[image_list[-1]]) # 这里改成image_list
    inputs = {
        'input_ids': input_by_model['input_ids'].unsqueeze(0).to(DEVICE),
        'token_type_ids': input_by_model['token_type_ids'].unsqueeze(0).to(DEVICE),
        'attention_mask': input_by_model['attention_mask'].unsqueeze(0).to(DEVICE),
        'images': [[input_by_model['images'][0].to(DEVICE).to(torch_type)]], # 这里[0]改成list comprehension
    }
    if 'cross_images' in input_by_model and input_by_model['cross_images']:
        inputs['cross_images'] = [[input_by_model['cross_images'][0].to(DEVICE).to(torch_type)]] # 这里[0]改成list comprehension
```

**Comment by zRzRzRzRzRzRzR** [comment]
不是的，因为图像和模型在训练编排的时候就已经是单图了，因为多图的话其实也都会针对第一章传入的图进行操作，在clidemo中一旦插入多个图片前面的历史就作废了

**Comment by truebit** [comment]
> 不是的，因为图像和模型在训练编排的时候就已经是单图了，因为多图的话其实也都会针对第一章传入的图进行操作，在clidemo中一旦插入多个图片前面的历史就作废了

按这个逻辑，我尝试复现[飞书中的例子](https://zhipu-ai.feishu.cn/wiki/Pr7KwjS7WixAL6kBGSecD8MGnEc)，没有成功。
模型好像没有觉察到我已经按它的操作执行了下一步。
我用的open-api.py提供的接口调用的，其中有自动获取history的逻辑。我把每次返回的next action作为assistant的返回输入。
第一步用cli_demo里面的prompt开头并加上模版里面的方式问它task内容，而后每一步都用“I followed your instructions”+模版里面的格式问同一个task。这样的问话方式好像不能连贯
