### ISSUE TITLE
Fine-tuning on Text/Image Input -> Text Output

### ISSUE THREAD

**Issue by mshumer** [THUDM/CogVLM#284]
### Feature request  / 功能建议

I don't see any docs for fine-tuning on text/image inputs -> text outputs, similar to LLaVA or others, for example:
```
[
  {
    "id": "997bb945-628d-4724-b370-b84de974a19f",
    "image": "part-000001/997bb945-628d-4724-b370-b84de974a19f.jpg",
    "conversations": [
      {
        "from": "human",
        "value": "<image>\nWrite a prompt for Stable Diffusion to generate this image."
      },
      {
        "from": "gpt",
        "value": "a beautiful painting of chernobyl by nekro, pascal blanche, john harris, greg rutkowski, sin jong hun, moebius, simon stalenhag. in style of cg art. ray tracing. cel shading. hyper detailed. realistic. ue 5. maya. octane render. "
      },
    ]
  },
  ...
]
```

I saw this issue `https://github.com/THUDM/CogVLM/issues/139` but it would be great to have native support.

### Motivation / 动机

Most use-cases include both text and image inputs, so without this, use-cases are severely limited.

### Your contribution / 您的贡献

N/A

**Comment by wenyihong** [comment]
Thanks for your question! 


In our finetuning demo, we use ItemDataset, which is a very simple dataset demo. https://github.com/THUDM/CogVLM/blob/7db2e88c8c6869b97195ee76212363f1f5d6cfe7/finetune_demo/finetune_cogvlm_demo.py#L219


As illustrated in [\_\_getitem\_\_ func of ItemDataset](https://github.com/THUDM/CogVLM/blob/7db2e88c8c6869b97195ee76212363f1f5d6cfe7/utils/utils/dataset.py#L43C2-L43C2), you can adjust 
1. `img` to your input image
2. `self.process_text({ANSWER}, {QUESTION/PROMPT})` to your answer and question / prompt. 

And thanks for your suggestion, we will provide docs about training dataset in the future.

**Comment by zRzRzRzRzRzRzR** [comment]
if you are using huggingface, try read https://zhipu-ai.feishu.cn/wiki/YInmwPmyii67VRkzU3BchPNzncg for find more information about dataset and we wiill release hf finetune soon
