### ISSUE TITLE
HF Trainer, finetune  for HF format models 

### ISSUE THREAD

**Issue by aamir-gmail** [THUDM/CogVLM#286]
### Feature request  / 功能建议

If possible please provide a HF trainer fine tune script based on  this HF repo "THUDM/cogagent-vqa-hf" ,

### Motivation / 动机

it is easier to train models in hugging face echo system as most of us a familiar with HF tools. 

### Your contribution / 您的贡献

Once I have the HF basic train scripts , I would be happy to do the deep speed integration, QLORA and contribute to train on low resource devices , I have written HF based custom trainers  in the past for low resource devices. Also provide integration with weights and biases (W&B)

**Comment by zRzRzRzRzRzRzR** [comment]
we will provide a peft finetune simple demo for hf model soon
