### ISSUE TITLE
How many GPUs are required for fine-tuning CogAgent on the example scenario?

### ISSUE THREAD

**Issue by mshumer** [THUDM/CogVLM#289]
### System Info / 系統信息

See above -- using 8x A100s and it's OOMing.

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Using the example scripts, with the Agent model.

### Expected behavior / 期待表现

not... OOM?

**Comment by zRzRzRzRzRzRzR** [comment]
OOM 是因为单张卡加载了太多的batch，你的batch调低试试？

**Comment by mshumer** [comment]
How can I do this?
