### ISSUE TITLE
"Sorry, I can't analyze the content of the current image for you. "

### ISSUE THREAD

**Issue by wizardlancet** [THUDM/CogVLM#29]
When I was attempting to conduct a multi-modal test on a healthcare-related dataset, the online demo responded as follows:
"Sorry, I am unable to analyze the content of the current image for you. However, feel free to ask me other questions, and I will do my best to assist you. Thank you for your understanding!"

Is there any moderation or monitoring of inputs and outputs related to the healthcare field?

**Comment by iyuge2** [comment]
Is this the output result on the web demo?

**Comment by iyuge2** [comment]
@wizardlancet hi，
for safety reason, we added security rules on the web demo, which are not set for the healthcare field. It is possible that your question / image / model's response triggered one of these rules, leading to this result.

**Comment by wizardlancet** [comment]
@iyuge2 
Okay, since I couldn't find it in the web_demo.py or any other file, I raised this issue. Thank you for your response. If I want to proceed with my testing, would it be more appropriate to directly load the model from the code?

**Comment by iyuge2** [comment]
@wizardlancet Yep~
The built-in security controls in the ckpt are weaker. I guess it won't cause the same problem for your testing.
