### ISSUE TITLE
CogVLM always return Timeout

### ISSUE THREAD

**Issue by hanswang1** [THUDM/CogVLM#291]
### System Info / 系統信息

![image](https://github.com/THUDM/CogVLM/assets/6904705/097fed67-274d-49a5-bbc2-4f83464eee3e)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

CogVLM always return 
![image](https://github.com/THUDM/CogVLM/assets/6904705/ad6447ed-32a1-4eb9-b132-51964f25453b)
![image](https://github.com/THUDM/CogVLM/assets/6904705/b4277ab6-4c6d-4eef-9a40-dbad9298ce4f)
![image](https://github.com/THUDM/CogVLM/assets/6904705/cb4a5fe3-1729-423e-b7d8-234ec80bcfd2)

### Expected behavior / 期待表现

The model can reply correct answer instead of "Timeout! Please wait a few minutes and retry."

**Comment by darkacorn** [comment]
you gotta read the error messages my friend .. :)

**Comment by hanswang1** [comment]
> you gotta read the error messages my friend .. :)

I already reinstalled xformers, and if I install apex, the core will be dumped.
So which error message should I pay attention to?

![image](https://github.com/THUDM/CogVLM/assets/6904705/952c6614-ef4b-4fd5-aa94-e18f6f3919e4)

**Comment by hanswang1** [comment]
I reinstall xformers by: pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu118
And it seems the issue is gone now.
