### ISSUE TITLE
modelscope 下载文件 在运行 web_domo.py 的时候没有 model_config.json 文件

### ISSUE THREAD

**Issue by DaBaiTuu** [THUDM/CogVLM#295]
### System Info / 系統信息

无关

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

由于 网络问题 不能直接使用 sat 的 下载流程，因此手动下载 modelscope 的 文件 ，
除了能 在 hf 的环境示例下运行 ，在运行 web demo 的文件时，由于 范例给出的 from_pretrained()函数是 sat 库的，因此在拿来导入 modelscope 下载的模型时 不适配 需要导入 model_config.json 这是没有的，我手动改为 由 transformers 的 from_pretrained 方式 有有些其他错误，所以烦请在 web_demo 里对 modelscope 下载 模型 给予适配，亦或给出改动建议，多谢

### Expected behavior / 期待表现

web_demo 里对 modelscope 下载 模型 给予适配，亦或给出改动建议

**Comment by zRzRzRzRzRzRzR** [comment]
啊，不是纯对hf适配的吗

**Comment by DaBaiTuu** [comment]
> 啊，不是纯对hf适配的吗

modelscope 确实 纯对 hf 适配的，但只适用于 cli_demo_hf那个py文件，
web_domo.py 里是对 sat 适配的，
由于下载原因我只能手动去下载modelscope 的文件，
因此我想要运行的webdemo的时候就有 “未有model_config.json” 的报错

**Comment by zRzRzRzRzRzRzR** [comment]
你试试hf的webdemo？
有一个streamlit的呀 完整demo

**Comment by DaBaiTuu** [comment]
> 你试试hf的webdemo？ 有一个streamlit的呀 完整demo

哦哦，你说的是composite_domo 文件夹吧，我确实没注意到，我只看了Readme 里的basicdomo，
然后
我试了一下，手动改了一下你的脚本加了load_in_4bit=True,，因为我显存不够：

`model = AutoModelForCausalLM.from_pretrained(
                        model_info['path'],
                        torch_dtype=torch_type,
                        low_cpu_mem_usage=True,
                        load_in_4bit=True,
                        trust_remote_code=True,
                    ).eval()                  `

出现了错误：
Please 'pip install apex'
Loading checkpoint shards: 100%|██████████| 8/8 [00:17<00:00,  2.24s/it]
Some weights of CogAgentForCausalLM were not initialized from the model checkpoint at /home/dongsongb/PYTHON-```
PROJ/openai/CogAgent/ZhipuAI/cogagent-vqa/ and are newly initialized: ['model.cross_vision.vit.model.blocks.15.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.19.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.11.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.22.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.4.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.2.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.15.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.20.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.18.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.1.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.7.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.3.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.11.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.20.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.9.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.6.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.3.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.10.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.0.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.10.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.4.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.23.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.21.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.8.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.5.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.13.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.1.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.5.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.0.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.16.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.23.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.8.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.2.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.17.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.22.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.17.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.13.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.9.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.14.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.16.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.6.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.12.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.7.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.14.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.12.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.21.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.18.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.19.attn.rope.freqs_cos']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

我虽然用的 Cogangent-vqa ，但是我看CogAgent-vqa-hf are not included in this demo, but you can use it in the same way as CogAgent-chat-18B     and used it in CogAgent-Chat，
应该还是能用的吧

**Comment by DaBaiTuu** [comment]
![Screenshot from 2024-01-09 15-20-22](https://github.com/THUDM/CogVLM/assets/120782756/a8c1543e-134a-49ac-a7b4-44b418c50dfe)

很奇怪，怎么那一步会去调 translate_baidu()

**Comment by zRzRzRzRzRzRzR** [comment]
如果你用中文就需要填写百度的翻译，这个模型不支持中文

**Comment by DaBaiTuu** [comment]
> 如果你用中文就需要填写百度的翻译，这个模型不支持中文

好的谢谢，不过 cli_demo_hf那个py文件有的时候能使用中文。
![Screenshot from 2024-01-09 17-59-17](https://github.com/THUDM/CogVLM/assets/120782756/68c400b9-7e1d-44b1-a13c-d2abb8a4cc53)

**Comment by zRzRzRzRzRzRzR** [comment]
因为vicuna 本身能回答一点点中文

**Comment by wudidaxuexue** [comment]
请问怎么解决的呢，我也遇到了同样的问题。

**Comment by DaBaiTuu** [comment]
> 请问怎么解决的呢，我也遇到了同样的问题。

你好好看看我的解决流程，本质上避免 使用sat 库去解析你从 hf ms 下的文件
