### ISSUE TITLE
Could you provide more generalist performances of cogvlm on benmark datasets like GQA, SCI-QA and MMVet, etc?

### ISSUE THREAD

**Issue by luogen1996** [THUDM/CogVLM#298]
### Feature request  / 功能建议

Could you provide more generalist performances of cogvlm on benmark datasets like GQA, SCI-QA and MMVet, etc?

### Motivation / 动机

No

### Your contribution / 您的贡献

No

**Comment by Sleepychord** [comment]
Hi, you can find the results in the paper and repo.
