### ISSUE TITLE
请问能否拓展huggingface版  cli_demo_hf.py  int8量化

### ISSUE THREAD

**Issue by wanghanyang123** [THUDM/CogVLM#299]
### Feature request  / 功能建议

本机服务器4卡T4（16G），cuda12.2，仅能运行  cli_demo_hf.py  int4量化，fp16加载模型后爆显存；
cli_demo_sat.py 运行不了，加载模型后不报错直接自动  killed；
openai_api.py 没有量化版本，加载模型后爆显存。

同时有疑问，为什么4卡加载完成模型后，每块卡占用约9G的显存，然后突然显存爆掉？

### Motivation / 动机

希望尽可能在小容量显卡上运行起来精度更高的模型。

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
你直接尝试fp16 并切割到四张卡运行模型呢？
int4在线量化是要在单卡或者内存中完整模型压缩的

**Comment by wanghanyang123** [comment]
@zRzRzRzRzRzRzR

**Comment by wanghanyang123** [comment]
hf版 int4可以运行没问题，且int4 也是多卡运行的
cli_demo_hf.py 中加入了    os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"   和    device_map="auto"
model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH,
        torch_dtype=torch_type,
        low_cpu_mem_usage=True,
        load_in_4bit=args.quant is not None,
        trust_remote_code=True,
        device_map="auto"）

fp16的模型还是会显存溢出
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 43.06 MiB is free. Process 63110 has 14.70 GiB memory in use. Of the allocated memory 14.60 GiB is allocated by PyTorch, and 1.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by wanghanyang123** [comment]
hf版 int4可以运行没问题，且int4 也是多卡运行的
cli_demo_hf.py 中加入了 os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3" 和 device_map="auto"
model = AutoModelForCausalLM.from_pretrained(
MODEL_PATH,
torch_dtype=torch_type,
low_cpu_mem_usage=True,
load_in_4bit=args.quant is not None,
trust_remote_code=True,
device_map="auto"）

fp16的模型还是会显存溢出
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 43.06 MiB is free. Process 63110 has 14.70 GiB memory in use. Of the allocated memory 14.60 GiB is allocated by PyTorch, and 1.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
hf 是没有int8的 fp16需要使用36G显存，每张卡载入的时候不报错，但是一旦回答就报错吗

**Comment by wanghanyang123** [comment]
> hf 是没有int8的 fp16需要使用36G显存，每张卡载入的时候不报错，但是一旦回答就报错吗

运行hf时，quant设置None，8个模型文件加载完成了，但是显存爆了。

![微信图片_20240110183048](https://github.com/THUDM/CogVLM/assets/32231771/dac41880-dad2-4c20-bd16-74b59544c79d)

**Comment by zRzRzRzRzRzRzR** [comment]
emm, 你这个好像使用了量化诶，不应该出现那么多没初始化的内容

**Comment by wanghanyang123** [comment]
> emm, 你这个好像使用了量化诶，不应该出现那么多没初始化的内容

我运行的就是没修改过的源码，而且int4量化的运行速度也挺长的差不多10秒出结果

**Comment by zRzRzRzRzRzRzR** [comment]
没有修改过的源码在正常读入中应该不会有任何的警告
`pip install apex`除外
或许可能是因为T4架构太老的问题，我们使用的是A100

**Comment by Devin5258** [comment]
> hf版 int4可以运行没问题，且int4 也是多卡运行的 cli_demo_hf.py 中加入了 os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3" 和 device_map="auto" model = AutoModelForCausalLM.from_pretrained( MODEL_PATH, torch_dtype=torch_type, low_cpu_mem_usage=True, load_in_4bit=args.quant is not None, trust_remote_code=True, device_map="auto"）
> 
> fp16的模型还是会显存溢出 torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 43.06 MiB is free. Process 63110 has 14.70 GiB memory in use. Of the allocated memory 14.60 GiB is allocated by PyTorch, and 1.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> @zRzRzRzRzRzRzR

请问大佬这个问题解决了吗？

**Comment by zRzRzRzRzRzRzR** [comment]
还是没有遇到过。。。
