### ISSUE TITLE
So... the pretrained model it not available now?

### ISSUE THREAD

**Issue by aisensiy** [THUDM/CogVLM#3]

**Comment by 1049451037** [comment]
The pretrained models are available. You will automatically download model with SAT if you run cli_demo.py. Also, if you have trouble in accessing in that way, you can also download from [CogVLM modelscope](https://www.modelscope.cn/models/ZhipuAI/CogVLM/summary).

**Comment by 1049451037** [comment]
No extra configuration is needed. So what did you do?

**Comment by 1049451037** [comment]
The bug is fixed now. Thank you for your reporting!
