### ISSUE TITLE
How to convert from SAT weights to HF?

### ISSUE THREAD

**Issue by mshumer** [THUDM/CogVLM#302]
### System Info / 系統信息

N/A

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

N/A

### Expected behavior / 期待表现

N/A

**Comment by 1049451037** [comment]
https://github.com/THUDM/CogVLM/issues/241

**Comment by Michael3444** [comment]
我用上边的脚本把微调好的模型转成huggingface的模型，报错
`(base) root@fcced1565a5f:/home/pengkun.li/CogVLM/basic_demo# CUDA_VISIBLE_DEVICES=4 python sat2hf.py 
Traceback (most recent call last):
  File "/home/pengkun.li/CogVLM/basic_demo/sat2hf.py", line 141, in <module>
    vlm('/data/nvme5n1/pengkun.li/cogvlm-chat-models/cogvlm-chat-finetune-hf')
  File "/home/pengkun.li/CogVLM/basic_demo/sat2hf.py", line 93, in vlm
    assert False, f"{k}"
AssertionError: transformer.layers.0.attention.query_key_value.original.weight`

**Comment by 1049451037** [comment]
你需要先把lora给merge进去。

**Comment by Michael3444** [comment]
> 你需要先把lora给merge进去。

感谢如此及时的回复，您的意思是执行merge_model.py那个文件么？我其实执行过了，但是无论用原始的模型，还是merge_model.py生成的文件，都报相同的错误 @1049451037

**Comment by 1049451037** [comment]
merge model不是merge lora。merge model是合并模型并行的。

**Comment by 1049451037** [comment]
参考这个：https://github.com/THUDM/CogVLM/issues/117

**Comment by Michael3444** [comment]
> 参考这个：#117

已转成功，万分感谢
