### ISSUE TITLE
can you release your TouchStone-Chinese dataset?

### ISSUE THREAD

**Issue by floveqq** [THUDM/CogVLM#305]
### Feature request  / 功能建议

can you release your TouchStone-Chinese dataset? thanks

### Motivation / 动机

can you release your TouchStone-Chinese dataset? thanks

### Your contribution / 您的贡献

can you release your TouchStone-Chinese dataset? thanks

**Comment by zRzRzRzRzRzRzR** [comment]
It is a little bit difficult for release Chinse dataset ,but we have released our CogVLM-SFT-311K for finetune
