### ISSUE TITLE
请问如何用非tritron接口RotaryEmbedding应用到cogvlm的attn位置编码中

### ISSUE THREAD

**Issue by cloud9wj** [THUDM/CogVLM#306]
### Feature request  / 功能建议

如题，因为一些原因暂时无法使用tritron包

### Motivation / 动机

无法使用tritron包

### Your contribution / 您的贡献

https://github.com/THUDM/SwissArmyTransformer/blob/main/sat/model/position_embedding/rotary_embeddings.py

**Comment by 1049451037** [comment]
参考这里：https://github.com/THUDM/CogVLM/issues/138#issuecomment-1835313875
