### ISSUE TITLE
when CUDA_VISIBLE_DEVICES=1,3 torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo_sat.py --from_pretrained cogagent-chat --version chat --bf16  --stream_chat

### ISSUE THREAD

**Issue by skyfallsss** [THUDM/CogVLM#310]
Welcome to CogAgent-CLI. Enter an image URL or local file path to load an image. Continue inputting text to engage in a conversation. Type "clear" to start over, or "stop" to end the program.
Please enter the image path or URL: /data/home/cuitor/skyfall/CogVLM/basic_demo/G2206200001.004.png
User: what can you see in the image?
Model:  answering does not require reading text in the image
how to let the model answer the questions.

**Comment by 1049451037** [comment]
You can try `cogagent-vqa`.
