### ISSUE TITLE
如何以openai api的模式，在两张卡上运行

### ISSUE THREAD

**Issue by deku0818** [THUDM/CogVLM#311]
### System Info / 系統信息

ubuntu，CUDA Version: 12.2，conda

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

/

### Expected behavior / 期待表现

希望在openai_api运行非量化版本，并在两张32G V100上运行

**Comment by zRzRzRzRzRzRzR** [comment]
目前的量化版本是在线量化，意味着你需要先读入一个完整的FP16模型并使用显卡进行量化，请注意，openai demo并没有修改读入模型的部分，这意味着你可以在模型读入的部分自己选择拆分模型，只要能符合 Transfomer 的输出就能在openai demo中正常使用

**Comment by deku0818** [comment]
> 目前的量化版本是在线量化，意味着你需要先读入一个完整的FP16模型并使用显卡进行量化，请注意，openai demo并没有修改读入模型的部分，这意味着你可以在模型读入的部分自己选择拆分模型，只要能符合 Transfomer 的输出就能在openai demo中正常使用

感谢你的回复！但是我并没有任何模型训练的经验，也仅会部署，我尝试过一些办法但也没有实现，请问有相关的代码吗？能否给我一个示例

**Comment by deku0818** [comment]
并且我无法复现，在官方demo的回复，我用了官方的promopt 模板，但是依旧无法复现
