### ISSUE TITLE
运行hf量化模型时，回答是中英结合的？我已经在问题里说明了使用中文回答，请问这种情况是正常的吗？

### ISSUE THREAD

**Issue by DreannER** [THUDM/CogVLM#316]
### System Info / 系統信息

程序运行没有问题，这是有可能涉及到硬件方面的问题吗？我跑的是quant 4的hf量化模型

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

一张东方明珠的图片，让模型介绍图片的内容

### Expected behavior / 期待表现

期待回复纯中文的回答

**Comment by zRzRzRzRzRzRzR** [comment]
这个模型不支持中文，一点点中文是因为vicuna词表内有一点点，本身是不支持中文的

**Comment by DreannER** [comment]
> 这个模型不支持中文，一点点中文是因为vicuna词表内有一点点，本身是不支持中文的

所以网页demo版本和这些模型是不一样的是把？后续会考虑发布中文版本的吗？

**Comment by zRzRzRzRzRzRzR** [comment]
网页demo 加上了翻译器，中文版本暂时没有开源
