### ISSUE TITLE
Could you please share some scripts that can help researchers to reproduce your results on Mine2web?

### ISSUE THREAD

**Issue by zfchenUnique** [THUDM/CogVLM#319]
### Feature request  / 功能建议

Could you please share some scripts that can help researchers to reproduce your results on Mine2web, including how to process the raw data and evaluate the model? This will make other researchers follow your work easier and increase this work's research impact?

### Motivation / 动机

To follow the great work easier. 

### Your contribution / 您的贡献

N/A.

**Comment by zRzRzRzRzRzRzR** [comment]
We have no plans to make this information public
