### ISSUE TITLE
部署时报错

### ISSUE THREAD

**Issue by Yj1027520** [THUDM/CogVLM#32]
Welcome to CogVLM-CLI. Enter an image URL or local file path to load an image. Continue inputting text to engage in a conversation. Type "clear" to start over, or "stop" to end the program.
Please enter the image path or URL (press Enter for plain text conversation): User: /mnt/models/CogVLM/examples/1.png
No image is not supported!
Please enter the image path or URL (press Enter for plain text conversation): /mnt/models/CogVLM/examples/1.png
User: wa^Hhta this
No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 1226, 16, 112) (torch.bfloat16)
     key         : shape=(1, 1226, 16, 112) (torch.bfloat16)
     value       : shape=(1, 1226, 16, 112) (torch.bfloat16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`decoderF` is not supported because:
    xFormers wasn't build with CUDA support
    attn_bias type is <class 'NoneType'>
    operator wasn't built - see `python -m xformers.info` for more info
`flshattF@0.0.0` is not supported because:
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    xFormers wasn't build with CUDA support
    dtype=torch.bfloat16 (supported: {torch.float32})
    has custom scale
    operator wasn't built - see `python -m xformers.info` for more info
    unsupported embed per head: 112
Please enter the image path or URL (press Enter for plain text conversation): ^CTraceback (most recent call last):
  File "/mnt/models/CogVLM/cli_demo.py", line 154, in <module>
    main()
  File "/mnt/models/CogVLM/cli_demo.py", line 76, in main
    image_path = [input("Please enter the image path or URL (press Enter for plain text conversation): ")]
KeyboardInterrupt

**Comment by Yj1027520** [comment]
这是什么原因呢

**Comment by 1049451037** [comment]
cuda版本太低，尝试升级cuda版本
