### ISSUE TITLE
chatglm4图片理解功能

### ISSUE THREAD

**Issue by lhzwangwei** [THUDM/CogVLM#323]
### System Info / 系統信息

智谱清言网站
<img width="727" alt="屏幕截图 2024-01-17 102358" src="https://github.com/THUDM/CogVLM/assets/92851144/d6b32917-2975-4435-a592-24dcedc47ba3">

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用网站的glm4体验版，点上传文件，传一个图片，然后配上提问，一直报错

### Expected behavior / 期待表现

能使用glm4进行图片理解

**Comment by zRzRzRzRzRzRzR** [comment]
现在测试是正常的，估计是人太多了
