### ISSUE TITLE
GUI+OCR数据集是否开源？

### ISSUE THREAD

**Issue by sugary199** [THUDM/CogVLM#325]
您好，在论文中看到你们构建了一个GUI+OCR的大数据集（“We thus construct a large-scale annotated dataset about GUIs and OCR for continual pre-training.”），请问这个是否准备开源呢

**Comment by mactavish91** [comment]
您好，暂时没有计划开源

**Comment by junweiyuan** [comment]
您好，请问构建数据集的instruction template会公布吗，多谢！
