### ISSUE TITLE
ModuleNotFoundError: No module named 'sat'

### ISSUE THREAD

**Issue by amy58328** [THUDM/CogVLM#326]
### System Info / 系統信息

I'm running the demo in docker
I get the error "ModuleNotFoundError: No module named 'sat'"

I want to know how can I solve this error

![image](https://github.com/THUDM/CogVLM/assets/43245005/ae6be8e5-09d2-419a-b954-b6f4c77bb826)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

I set up the environment on docker according to the steps on the official website without changing anything.

### Expected behavior / 期待表现

Would like to be able to run the demo code on my computer

**Comment by mactavish91** [comment]
You need to ```pip install SwissArmyTransformer```

**Comment by amy58328** [comment]
it works！！
thanks for your advice！
