### ISSUE TITLE
4-bit quantization export for cogagent?

### ISSUE THREAD

**Issue by DiTo97** [THUDM/CogVLM#329]
### feature request  / 功能建议

would it be possible to export a 4-bit quantized cogagent model for inference?

### motivation / 动机

it is very time consuming to download the full-precision model shards and load the causal LM model from them.

**Comment by DiTo97** [comment]
@zRzRzRzRzRzRzR, any pointers on that?

**Comment by zRzRzRzRzRzRzR** [comment]
it is ok,but we do not provide a 4 bit model yet

**Comment by DiTo97** [comment]
will keep it open, in case you do in the future!

**Comment by DiTo97** [comment]
will close, @zRzRzRzRzRzRzR.

I pushed a [4-bit quantized version](https://huggingface.co/DiTo97/cogagent-vqa-hf-4bit) of cogagent VQA to the hub.

**Comment by crux82** [comment]
@DiTo97 is there any procedure to export a fine-tuned cogagent model in 4-bit, as you did?

TNX!

**Comment by DiTo97** [comment]
hi @crux82,

huggingface/transformers#26037 is where 4-bit serialization was made possible in the library.

you should see examples there on how to do it for any huggingface-compatible model (like cogVLM or cogagent)

**Comment by crux82** [comment]
@DiTo97 Thank you!!
