### ISSUE TITLE
run cli_demo error

### ISSUE THREAD

**Issue by rainsoulsrx** [THUDM/CogVLM#33]
<img width="1405" alt="image" src="https://github.com/THUDM/CogVLM/assets/24955512/3c3c0cfc-9a10-4266-97fb-1fe0f1687609">
hi, when I run `torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat --version chat --english --fp16`
I encounter this error. After debuging, i found the error is here:
<img width="444" alt="image" src="https://github.com/THUDM/CogVLM/assets/24955512/0b642812-3d62-44f4-b847-a80fd0b79d82">

**Comment by 1049451037** [comment]
You should have 2 GPUs available if you want to run --nproc-per-node=2

**Comment by rainsoulsrx** [comment]
> You should have 2 GPUs available if you want to run --nproc-per-node=2

Yes, I have 4 gpus

**Comment by 1049451037** [comment]
So you can try --nproc-per-node=4

Maybe it's because out of memory.

**Comment by rainsoulsrx** [comment]
> So you can try --nproc-per-node=4
> 
> Maybe it's because of out of memory.

I tried both 2 and 4. But all filed. I use 4 V100s, each 32510MiB 
the error is  occurred after the model loaded, when chat is calling.

**Comment by 1049451037** [comment]
Could you give me more detailed error info? The snapshot you post is not informative.

**Comment by rainsoulsrx** [comment]
> Could you give me more detailed error info? The snapshot you post is not informative.

<img width="1404" alt="image" src="https://github.com/THUDM/CogVLM/assets/24955512/5aeb8e9f-94e5-4821-8d81-011313fb6134">
<img width="1406" alt="image" src="https://github.com/THUDM/CogVLM/assets/24955512/a28b3d63-f852-457c-87fd-ee9a73cdcdc0">
<img width="1403" alt="image" src="https://github.com/THUDM/CogVLM/assets/24955512/f7534c11-d797-4f32-bc9c-7cd1dd50b499">
<img width="853" alt="image" src="https://github.com/THUDM/CogVLM/assets/24955512/f8476050-f2ec-4369-a58d-691c12564ec9">

**Comment by rainsoulsrx** [comment]
I add some print. and found the error is occurred when calling "chat" this line 
<img width="575" alt="image" src="https://github.com/THUDM/CogVLM/assets/24955512/8abc52ac-8b12-44db-acbc-d1683fc88e38">

**Comment by 1049451037** [comment]
Maybe it's a bug of torch. Try torch 2.1 instead of 2.0?

**Comment by 1049451037** [comment]
What is the version of your sat? You should have SwissArmyTransformer>=0.4.8

**Comment by rainsoulsrx** [comment]
> Swiss

<img width="397" alt="image" src="https://github.com/THUDM/CogVLM/assets/24955512/606713e0-7406-4fb2-8a62-620cc252edc3">

**Comment by 1049451037** [comment]
I tested the same command as yours on my machine. And it runs normally. So you have to check your env... I use cuda 12.2 and torch 2.1 (built by cu118). Maybe you can have a try?

**Comment by 1049451037** [comment]
If you still meet the problem, perhaps it's due to your V100 and xformers. (older version xformers does not support V100)

See this issue for reference: https://github.com/facebookresearch/xformers/issues/795

You can see you available kernel by running:

```
python -m xformers.info
```

**Comment by rainsoulsrx** [comment]
> I tested the same command as yours on my machine. And it runs normally. So you have to check your env... I use cuda 12.2, torch 2.1 (built by cu118) and xformers 0.0.22 (built by cu118). Maybe you can have a try?
I tried as you say, but cuda driver is too new. I failed update the driver. Could it possible to run in lower cuda driver

**Comment by rainsoulsrx** [comment]
> I tested the same command as yours on my machine. And it runs normally. So you have to check your env... I use cuda 12.2, torch 2.1 (built by cu118) and xformers 0.0.22 (built by cu118). Maybe you can have a try?

I tried as you say, but cuda driver is too new. I failed update the driver. Could it possible to run in lower cuda driver

**Comment by 1049451037** [comment]
What error was raised when you update driver? It's weird. Maybe you need to checkout some NVIDEA docs.

**Comment by 1049451037** [comment]
For cuda version 12.2, you just need to download and install cuda-12.2 into /usr/local. You do not need to update driver if your driver is higher than 535. Then, change the cuda PATH and LD_LIBRARY_PATH. I think this will work.

**Comment by rainsoulsrx** [comment]
> For cuda version 12.2, you just need to download and install cuda-12.2 into /usr/local. You do not need to update driver if your driver is not lower than 535. Then, change the cuda PATH and LD_LIBRARY_PATH. I think this will work.

<img width="840" alt="image" src="https://github.com/THUDM/CogVLM/assets/24955512/44bda135-9419-4b8e-b8e5-2cb4ce1c0e3d">
sadly, my driver version is too low  (╥﹏╥)o

**Comment by bobopit** [comment]
> > For cuda version 12.2, you just need to download and install cuda-12.2 into /usr/local. You do not need to update driver if your driver is not lower than 535. Then, change the cuda PATH and LD_LIBRARY_PATH. I think this will work.
> 
> <img alt="image" width="840" src="https://user-images.githubusercontent.com/24955512/275460000-44bda135-9419-4b8e-b8e5-2cb4ce1c0e3d.png"> sadly, my driver version is too low (╥﹏╥)o

@rainsoulsrx hi, Have you solved this problem? I have the same problem as you.
