### ISSUE TITLE
Cogvlm-How to batch inference？

### ISSUE THREAD

**Issue by aa7784171** [THUDM/CogVLM#333]
### System Info / 系統信息

与huggingface一致

### Who can help? / 谁可以帮助到您？

您好，您做的工作非常厉害！我现在遇到一个问题，希望您我帮忙解答一下。
1. 我现在按照demo只能实现单张图片inference，请问怎样实现多张图片inference？
2.  当我输入2张image，报错模型权重不匹配，请问该怎么解决呢
3. 期待您的答复，感谢！
RuntimeError:Given groups=1,weight of size [1792,3,14,14],expected input[1,6,490,490] to have 3 channels, but got 6 channels instead
![cogvlm_muti_image](https://github.com/THUDM/CogVLM/assets/73866232/3ef4fad9-f745-4a0b-9599-855b3e5c875a)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

RuntimeError:Given groups=1,weight of size [1792,3,14,14],expected input[1,6,490,490] to have 3 channels, but got 6 channels instead
![cogvlm_muti_image](https://github.com/THUDM/CogVLM/assets/73866232/3ef4fad9-f745-4a0b-9599-855b3e5c875a)

### Expected behavior / 期待表现

希望能解决batch inference，实现多张image同时forward，感谢！

**Comment by DiTo97** [comment]
@aa7784171, I will add my own experience as well, trying to process multiple images as input leads to a not supported error.

The two are likely related.

![batch-inference-error](https://github.com/THUDM/CogVLM/assets/40361744/680d42c8-c7a9-4d03-a9ea-6567602a4e8a)

**Comment by DiTo97** [comment]
@aa7784171, batch inference works after modifying modeling_cogagent.py as in #143.

**Comment by Anirudh257** [comment]
@DiTo97 @zRzRzRzRzRzRzR  Is there a way to perform batch-inference on multiple (image-query) samples?

**Comment by Anirudh257** [comment]
Thanks @DiTo97 !
