### ISSUE TITLE
Baselines - comparison to IDEFICS

### ISSUE THREAD

**Issue by VictorSanh** [THUDM/CogVLM#34]
Hey, very cool work!
I like the idea of treating vision and language as different experts.
I think it would be great to have a comparison against [IDEFICS-80b(-instruct)](https://huggingface.co/HuggingFaceM4/idefics-80b-instruct), in particular to see how your model compares against larger systems!
Let me know if i can help!

**Comment by Sleepychord** [comment]
@VictorSanh  Thank you for your advice. 
For basic vision ability, I think you can expert CogVLM-17B performs better in most cases according to the scores, e.g. on VQAv2 CogVLM 84.7 vs IDEFICS-80B 68.8, on NoCaps CogVLM 128 vs IDEFICS-80B 108. Although the score of IDEFICS is a 32-shot results but the difference is large enough. 

For chat alignment, in our opinion, we should evaluate them by a diverse benchmark and a "clever" judge. So we choose [Touchstone](https://github.com/QwenLM/Qwen-VL/blob/master/touchstone/README.md) (gpt4 check right or not) in our paper, but we did not has enough time to evaluate  IDEFICS-80B. If you can evaluate IDEFICS-80B, I will appreciate a lot~
