### ISSUE TITLE
web demo时error message list index out of range

### ISSUE THREAD

**Issue by elesun2018** [THUDM/CogVLM#341]
运行web demo时出现error message list index out of range
![5947a0741b9b837778161f0b826e46f](https://github.com/THUDM/CogVLM/assets/37207093/20ada1a5-a480-4ed8-bb19-59b08c2c3018)

![5df8a0902afc857bdc05b8668174278](https://github.com/THUDM/CogVLM/assets/37207093/74b088c6-041e-49a7-b041-e0a0f8d08ee4)

是使用模型哪里不对吗？

还有个问题：finetune训练时
finetune-cogvlm-01-17-10-02  merged_lora_cogvlm490 有什么区别，推理时应该用哪个？
merge layer 61 lora attention back to linear为什么要做这个操作

还有个问题：web demo加载finetune模型时出现killed，对资源内存要求会更高吗？
![f1a447fa6ab30f6e488489e3701dfa4](https://github.com/THUDM/CogVLM/assets/37207093/51c72e3e-f2ad-4e2d-b616-b09dcf3dda21)

**Comment by elesun2018** [comment]
能否帮忙解决一下

**Comment by elesun2018** [comment]
问题原因已找到，源代码
utils/utils/grounding_parser.py
draw_boxes需要缩进一下

**Comment by yileld** [comment]
> 问题原因已找到，源代码 utils/utils/grounding_parser.py draw_boxes需要缩进一下

哈哈哈感谢感谢，这个bug也太无厘头了

**Comment by yileld** [comment]
> 问题原因已找到，源代码 utils/utils/grounding_parser.py draw_boxes需要缩进一下

似乎我理解错了，请问哪一行要缩进呢？

**Comment by yileld** [comment]
> 问题原因已找到，源代码 utils/utils/grounding_parser.py draw_boxes需要缩进一下

你是把parse_response的最后一行draw_boxes往后缩进了一位吧。这个多次对话的时候还是会报错。

其实把demo.py里调用chat的try去掉就能定位到代码报错的地方了。
我是draw_boxes里的font_path=sorted(xxx)[0]的问题，没找到系统的字体，所以这个列表是空的，[0]就out of range，改一下就好了

**Comment by lovegit2021** [comment]
![image](https://github.com/user-attachments/assets/778a3fa5-96bd-4281-bc2a-377d60bd1807)
这是怎么debug啊
