### ISSUE TITLE
Cogagent inference issues on CPU

### ISSUE THREAD

**Issue by Mingyu-Wei** [THUDM/CogVLM#345]
Hi team, I was wondering if `cogagent` supports inference on CPU? When I ran the sample code [here](https://github.com/THUDM/CogVLM/blob/main/basic_demo/cli_demo_hf.py), I encountered several problems.

- Run w/ `--bf16` option: 
  When I use this option, I got this error indicating that `xformers` doesn't support cpu
  ```
  NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 257, 16, 112) (torch.bfloat16)
     key         : shape=(1, 257, 16, 112) (torch.bfloat16)
     value       : shape=(1, 257, 16, 112) (torch.bfloat16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
  `decoderF` is not supported because:
    device=cpu (supported: {'cuda'})
    attn_bias type is <class 'NoneType'>
    bf16 is only supported on A100+ GPUs
  `flshattF@v2.3.6` is not supported because:
    device=cpu (supported: {'cuda'})
    bf16 is only supported on A100+ GPUs
  `tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    bf16 is only supported on A100+ GPUs
    operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
  `cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
    bf16 is only supported on A100+ GPUs
  `smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    device=cpu (supported: {'cuda'})
    dtype=torch.bfloat16 (supported: {torch.float32})
    has custom scale
    bf16 is only supported on A100+ GPUs
    unsupported embed per head: 112

- Run w/o `--bf16` option:
  I got this error indicating that half precision operation isn't supported on CPU. I think this might be solved if I load the model using `float32`, but that would trigger OOM errors( my cpu memory is 64GB but it seems it's still not enough)
  ```
  RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
  ```

**Comment by zRzRzRzRzRzRzR** [comment]
hf vision depend on xformers ... it will be a big problem. if you are using Linux you can still install this package

**Comment by Mingyu-Wei** [comment]
> hf vision depend on xformers ... it will be a big problem. if you are using Linux you can still install this package

Thanks for your response. I checked the official page of xformers, and it seems they only support cuda. So if I'm understanding this correctly, inference on CPU with cogagent is not currently supported right?

**Comment by zRzRzRzRzRzRzR** [comment]
for sat version it is ok, for hf version in default version it is  not work

**Comment by zsynacl** [comment]
> for sat version it is ok, for hf version in default version it is not work

that answer is a big help.
