### ISSUE TITLE
微调时，apex相关报错

### ISSUE THREAD

**Issue by FZGgithub** [THUDM/CogVLM#348]
### System Info / 系統信息

我在4张A6000上微调cogvlm，使用的模型是hf的，demo可以成功多卡推理，但是微调时会报错：from pyramid.session import UnencryptedCookieSessionFactoryConfig。我的服务器是kylin的，参照了网上关于apex的安装方法，未能成功。
请问，这个该如何处理呢

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用的是示例代码，并为经过改动

### Expected behavior / 期待表现

我的运行环境是离线不联网的

**Comment by zRzRzRzRzRzRzR** [comment]
这个是源码安装的吧，要用英伟达的显卡，你这个也是呀
