### ISSUE TITLE
huggingface 模型输入的图片是否需要做均值，方差的归一化

### ISSUE THREAD

**Issue by AgentNext** [THUDM/CogVLM#349]
现象：
加载sat模型，输入图片需要做归一化。
而huggingface模型的示例代码，没有归一化的步骤。

问题：
请问，使用huggingface的模型，是否需要做归一化？

**Comment by 1049451037** [comment]
huggingface也有归一化：https://huggingface.co/THUDM/cogvlm-chat-hf/blob/main/modeling_cogvlm.py#L809-L816

**Comment by AgentNext** [comment]
> huggingface也有归一化：https://huggingface.co/THUDM/cogvlm-chat-hf/blob/main/modeling_cogvlm.py#L809-L816

谢谢，issue我关啦。
