### ISSUE TITLE
推理时报错：Model: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### ISSUE THREAD

**Issue by Zxlan** [THUDM/CogVLM#350]
### System Info / 系統信息

ubuntu python3.8 torch1.13.1
执行指令：python3 cli_demo_sat.py --from_pretrained cogvlm-chat-v1.1 --version chat_old --bf16 --stream_chat和python3 cli_demo_sat.py --from_pretrained cogvlm-base-490 --version base --bf16 --stream_chat都是相同的错误

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python3 cli_demo_sat.py --from_pretrained cogvlm-chat-v1.1 --version chat_old --bf16 --stream_chat

### Expected behavior / 期待表现

可以正常推理

**Comment by zRzRzRzRzRzRzR** [comment]
@1049451037 SAT的相关问题需要您看一下

**Comment by 1049451037** [comment]
修复了，可以pull一下最新的CogVLM代码，以及更新一下sat

```
git clone https://github.com/THUDM/SwissArmyTransformer
cd SwissArmyTransformer
pip install . --no-deps
```
