### ISSUE TITLE
finetune_cogagent_lora在8卡A10上出现OOM的异常

### ISSUE THREAD

**Issue by winboyer** [THUDM/CogVLM#351]
### System Info / 系統信息

cuda: 11.8
transformers: 4.37.0
python: 3.11.7
centos7
GPU: A10
NVIDIA-SMI 520.61.05

### Who can help? / 谁可以帮助到您？

@1049451037 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

sh finetune_cogagent_lora.sh，就出现OOM（out of memory）的异常
![image](https://github.com/THUDM/CogVLM/assets/10265383/21b3a5ef-66f1-4cdf-ae5b-74497e2b74ef)
![image](https://github.com/THUDM/CogVLM/assets/10265383/e64a32e2-015a-48fb-9c18-a3ff96819d7c)

### Expected behavior / 期待表现

期望告诉我应该如何解决out of memory的问题

**Comment by zRzRzRzRzRzRzR** [comment]
单个卡需要能载入一个完整模型才行
