### ISSUE TITLE
Running sample code but get killed message

### ISSUE THREAD

**Issue by amy58328** [THUDM/CogVLM#353]
### System Info / 系統信息

I executed the official sample command, but no error message appeared during the running process, only a "killed" message.

I would like to ask if it is caused by some part not being set properly.

![image](https://github.com/THUDM/CogVLM/assets/43245005/49c67a4e-c5f7-4382-89ea-e8f369f882d4)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

i didn't change anything.

### Expected behavior / 期待表现

Hopefully the code will work on my computer

**Comment by zRzRzRzRzRzRzR** [comment]
或许是内存不够，这需要使用大概40GB的内存用于载入模型？你成功载入模型了么？是在对话中被killed还是无法载入模型

**Comment by zRzRzRzRzRzRzR** [comment]
那就是内存不足或者显存不足，我们的文档中有对应的最低要求
https://zhipu-ai.feishu.cn/wiki/YqKwwcsc8iz4f5kXbhacyB4Wnwg

**Comment by amy58328** [comment]
好的！！ 
謝謝你的回覆
我會在試試看的！
