### ISSUE TITLE
有什么好的方式生成cogvlm论中提到的visual grouding数据（论文中是英文的，但期望能有中文版本的）？

### ISSUE THREAD

**Issue by xxxwuwq** [THUDM/CogVLM#355]
cogvlm中提到的visual grouding数据，是英文版本的，想了解下如何去支持中文上的visual grouding数据，通过语言模型 将英文生成翻译成中文后，总是奇奇怪怪的，对应不上

**Comment by zRzRzRzRzRzRzR** [comment]
中文版本的，我们提供了商业模型的，你可以在我们的API中使用，如果是开源版本，确实是翻译的，开源版本不支持中文
