### ISSUE TITLE
Problem with grounding examples

### ISSUE THREAD

**Issue by mlching** [THUDM/CogVLM#359]
### System Info / 系統信息

cuda 11.8
python 3.9.18
transformers 4.36.2
Ubuntu 18.04.1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo_sat.py --from_pretrained cogagent-chat --version chat --bf16
2. <img path>
3. <prompt added with (with grounding) at the end>
4. list index out of range

### Expected behavior / 期待表现

The cogagent-chat model does not work well with grounding when requested with the basic demo script cli_demo_sat.py.

**Comment by zRzRzRzRzRzRzR** [comment]
maybe add grounding template
