### ISSUE TITLE
在CPU服务器上运行sat版本cogvlm-chat-v1.1模型遇到问题

### ISSUE THREAD

**Issue by zsynacl** [THUDM/CogVLM#360]
### System Info / 系統信息

没有GPU，只有CPU

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本

### Reproduction / 复现过程

1. 按照requirements.txt安装依赖
2. 手动安装en_core_web_sm-3.7.1-py3-non-any.whl
3. 手动安装jsonlines
4. 下载cogvlm-chat-v1.1和lmsys/vicuna-7b-v1.5到本地
5. 执行cli_demo_sat.py
```python
# 以下代码报错 Input type (c10::Half) and bias type (float) should be the same
python cli_demo_sat.py --from_pretrained ../../cogvlm-chat-v1.1 --local_tokenizer ../models/models--lmsys--vicuna-7b-v1.5/snapshots/de56c35b1763eaae20f4d60efd64af0a9091ebe5
# 以下代码报错 "slow_conv2d_cpu" not implemented for 'Half'
python cli_demo_sat.py --from_pretrained ../../cogvlm-chat-v1.1 --local_tokenizer ../models/models--lmsys--vicuna-7b-v1.5/snapshots/de56c35b1763eaae20f4d60efd64af0a9091ebe5 --fp16
```
> 输入图片为官方数据集01162024_105753_0.jpg

不知道是否和torch被安装了cuda版本有关。曾经尝试过手动安装cpu版本的torch，但是后续安装python包时被自动替换成了cuda版本

### Expected behavior / 期待表现

能够正常在cpu服务器运行

**Comment by zRzRzRzRzRzRzR** [comment]
是的，一定要GPU，CPU跑不了这个模型

**Comment by 1049451037** [comment]
cpu可以跑吧，直接device='cpu'就可以。

**Comment by zsynacl** [comment]
> cpu可以跑吧，直接device='cpu'就可以。

如果是自己手动安装各项依赖应该可以。
