### ISSUE TITLE
Inquiry: Broken Link in README for Inference Details with 11GB GPU Memory

### ISSUE THREAD

**Issue by AlexandraDobrescu** [THUDM/CogVLM#362]
Hi there,

I'm interested in running inference with an 11GB GPU for [CogVLM](https://github.com/THUDM/CogVLM). The [README](https://github.com/THUDM/CogVLM/blob/main/README.md) suggests checking "News: 2023/12/7" for details, but the "See details" link is broken. Could you provide a direct path to the checkpoint or the script needed for 11GB GPU inference?

Thanks!

**Comment by zRzRzRzRzRzRzR** [comment]
11GB 需要使用int4进行推理，我们没有推出int4模型，意味着你需要载入FP16的模型并使用cuda算子量化为4bit，在对应的脚本中，其实都具有能直接使用的参数来进行推理。

**Comment by AlexandraDobrescu** [comment]
Am înțeles. Rezolvat. Mulțumesc.
找到了 解决了 谢谢。
Got it. Solved. Thanks.
