### ISSUE TITLE
请问换成其他LLM加载模型权重的时候，hf版本能和sat适配吗，还是说要先把hf的权重转成sat的

### ISSUE THREAD

**Issue by AlenjandroWang** [THUDM/CogVLM#366]

**Comment by 1049451037** [comment]
sat里支持大多数常见的LLM：https://github.com/THUDM/SwissArmyTransformer/tree/main/examples

**Comment by AlenjandroWang** [comment]
> sat里支持很多常见的LLM：https://github.com/THUDM/SwissArmyTransformer/tree/main/examples

[transform_param.py]是可以把hf权重转换成sat吗

**Comment by 1049451037** [comment]
是的

**Comment by AlenjandroWang** [comment]
Dear author


I'm an undergraduate student majoring in Computer Science from the Northwestern Polytechnical University. I recently worked on MLLM research and read your paper "COGVLM: VISUAL EXPERT FOR LARGE LANGUAGEMODELS",&nbsp;I am very interested in and admire your work. Your paper has provided me with a lot of inspiration and enlightenment ，so could you please share your pretraining code with me, for research purposes only? I promise that if I end up using your code, I will cite your work correctly in my paper.&nbsp;Thank you very much.


Sincerely,
Dianyi





---原始邮件---
发件人: "Qingsong ***@***.***&gt;
发送时间: 2024年2月4日(周日) 中午12:46
收件人: ***@***.***&gt;;
抄送: "Alex ***@***.******@***.***&gt;;
主题: Re: [THUDM/CogVLM] 请问换成其他LLM加载模型权重的时候，hf版本能和sat适配吗，还是说要先把hf的权重转成sat的 (Issue #366)




 
是的

**Comment by ayensujeremiah** [comment]
Dear authors, I am conducting a research around multimodal large language models, could you share how image and text inputs are encoded or preprocess for the Supervised finetuning as you did with LLAVA instruct? I promise to cite your work correctly in my paper as well
