### ISSUE TITLE
在运行finetune_cogvlm_lora.sh脚本微调时报错

### ISSUE THREAD

**Issue by FZGgithub** [THUDM/CogVLM#367]
### System Info / 系統信息

我的系统是kylin，cuda版本是12.1，使用[Captcha Images](https://www.kaggle.com/datasets/aadhavvignesh/captcha-images)数据集进行微调测试。使用4张A6000进行多卡训练，对于finetune_cogvlm_lora.sh，我这边只修改了NUM_GPUS_PER_WORKER为4，修改MODEL_TYPE为“cogvlm-chat-v1.1”，修改train_data，valid_data为我自己的存放路径。
报错信息为：
ModuleNotFoundError:No module named 'fused_layer_norm_cuda'
请问这一问题该如何处理呢

### Who can help? / 谁可以帮助到您？

@1049451037

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我的微调脚本信息如下：
NUM_GPUS_PER_WORKER=4
MP_SIZE=1

script_path=$(realpath $0)
script_dir=$(dirname $script_path)
main_dir=$(dirname $script_dir)
MODEL_TYPE="cogvlm-chat-v1.1"
VERSION="chat"
MODEL_ARGS="--from_pretrained $MODEL_TYPE \
    --max_length 400 \
    --lora_rank 50 \
    --use_lora \
    --local_tokenizer lmsys/vicuna-7b-v1.5 \
    --version $VERSION"
# TIPS: max_length include low-resolution image sequence (which has 256 tokens) 

OPTIONS_SAT="SAT_HOME=~/.sat_models"
OPTIONS_NCCL="NCCL_DEBUG=info NCCL_IB_DISABLE=0 NCCL_NET_GDR_LEVEL=2 LOCAL_WORLD_SIZE=$NUM_GPUS_PER_WORKER"
HOST_FILE_PATH="hostfile"

train_data="./archive_split/train"
valid_data="./archive_split/valid"

### Expected behavior / 期待表现

请问改如何处理这个问题呢？是缺依赖吗

**Comment by yileld** [comment]
你报错信息不贴具体的话没人能帮你的，哪个库代码哪一行都不说。
我记得是NVIDIA的apex库，你重新装一下或者卸载掉也行
