### ISSUE TITLE
显存不够，请问支持切分模型吗？

### ISSUE THREAD

**Issue by yileld** [THUDM/CogVLM#368]
3090的24G不太够，请问支持把模型切分到不同显卡上进行微调吗？
我记得accelerate是有dispatch_model功能的

**Comment by 1049451037** [comment]
可以，修改MP_SIZE即可：

https://github.com/THUDM/CogVLM/blob/a06d509b426b278ad392b835c24880481c0c5329/finetune_demo/finetune_cogagent_lora.sh#L6

**Comment by yileld** [comment]
> 可以，修改MP_SIZE即可：
> 
> https://github.com/THUDM/CogVLM/blob/a06d509b426b278ad392b835c24880481c0c5329/finetune_demo/finetune_cogagent_lora.sh#L6

感谢！所以我单机4卡就是NUM_GPUS_PER_WORKER=4，MP_SIZE=4对吧？（因为line 22的LOCAL_WORLD_SIZE=$NUM_GPUS_PER_WORKER让我不太确定NUM_GPUS_PER_WORKER这个参数的含义了，以为WORLD_SIZE是实际的进程数，会变成4x4=16需要16张卡）
另外微调cogagent大概需要多少显存呢？我4卡似乎还是不够

**Comment by 1049451037** [comment]
微调lora的话8张3090吧。4卡的话你可以尝试减少一点微调参数，比如只训练language model的lm_head，并且去掉lora，不知道行不行。

**Comment by yileld** [comment]
> 微调lora的话8张3090吧。4卡的话你可以尝试减少一点微调参数，比如只训练language model的lm_head，并且去掉lora，不知道行不行。

好的，感谢
