### ISSUE TITLE
download 224 when --from_pretrained cogvlm-base-490

### ISSUE THREAD

**Issue by YukunZEX** [THUDM/CogVLM#37]
when i tried python cli_demo.py --from_pretrained cogvlm-base-490 --version base --english --bf16 --no_prompt, the code download cogvlm-base-224.zip and report FileNotFoundError: [Errno 2] No such file or directory: '/xxx/cogvlm-base-490.zip'

**Comment by 1049451037** [comment]
Could you post a screenshot?

**Comment by YukunZEX** [comment]
![image](https://github.com/THUDM/CogVLM/assets/54986490/6daf2320-40df-4d7d-afbd-fd058ad9e859)

![image](https://github.com/THUDM/CogVLM/assets/54986490/5f4356ba-a59e-4f20-b3fc-d9d82530eea9)

**Comment by YukunZEX** [comment]
![image](https://github.com/THUDM/CogVLM/assets/54986490/beb96333-fbef-40bc-be7d-086fda40131b)

**Comment by 1049451037** [comment]
Thank you for your reporting! You can pull the latest GitHub code to fix this.

**Comment by YukunZEX** [comment]
ok, let me try, thank you. by the way, would --fp16 change model performance?

**Comment by 1049451037** [comment]
--fp16 won't affect performance. But sometimes it raises NaN.

**Comment by YukunZEX** [comment]
Thank you very much

**Comment by YukunZEX** [comment]
![image](https://github.com/THUDM/CogVLM/assets/54986490/b0f02825-a69b-415e-b57e-f404cf6fef26)

**Comment by 1049451037** [comment]
看起来是你的本地代码有问题，打开models/cogvlm_model.py看一下里面为什么会有html代码

**Comment by YukunZEX** [comment]
最后一个问题是我下载cogvlm_model.py操作错误导致，问题解决了，现在cogvlm-base-490工作正常，非常感谢
![1697614265975](https://github.com/THUDM/CogVLM/assets/54986490/137f4598-b0fa-4cdd-bad7-faf403b0c400)
