### ISSUE TITLE
How to add lora matrix to CogAgent model via Peft?

### ISSUE THREAD

**Issue by TankNee** [THUDM/CogVLM#377]
### Feature request  / 功能建议

I plan to use huggingface trainer and peft to fine-tune CogAgent with lora. I would like to know if there are similar examples, or can you tell me how to set the lora parameters? I have read the sat and failed to understand how to choose which layers to perform lora fine-tuning.

### Motivation / 动机

none

### Your contribution / 您的贡献

none

**Comment by vmanisha** [comment]
Hi TankNee, how did you train with PEFT? Can you share the details?
