### ISSUE TITLE
Will it support video input?

### ISSUE THREAD

**Issue by KooSung** [THUDM/CogVLM#38]
Amazing work, will it support video input?

**Comment by 1049451037** [comment]
Our model has the capability to handle multi-image inputs. However, multi-image data wasn’t utilized during the training process in our current checkpoint. You might want to consider fine-tuning the model with multi-image data.

**Comment by chricro** [comment]
Yep, also interesting to know how it works.

**Comment by lightingvector** [comment]
@zRzRzRzRzRzRzR
