### ISSUE TITLE
官方代码的hf版本的cogvlm模型推理报错Out of Memory

### ISSUE THREAD

**Issue by zhaohongyin** [THUDM/CogVLM#383]
### System Info / 系統信息

RTX3090 * 2
Python ==3.10.0
cuda_12.2.r12.2
Transformer == 4.35.0
![微信截图_20240219204017](https://github.com/THUDM/CogVLM/assets/30042495/7e9a43ca-2b26-4717-80d1-26d69832a55f)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

import torch
import requests
from PIL import Image
from transformers import AutoModelForCausalLM, LlamaTokenizer
from accelerate import init_empty_weights, infer_auto_device_map, load_checkpoint_and_dispatch

tokenizer = LlamaTokenizer.from_pretrained('lmsys/vicuna-7b-v1.5')
with init_empty_weights():
    model = AutoModelForCausalLM.from_pretrained(
        'THUDM/cogvlm-chat-hf',
        torch_dtype=torch.bfloat16,
        low_cpu_mem_usage=True,
        trust_remote_code=True,
    )
device_map = infer_auto_device_map(model, max_memory={0:'20GiB',1:'20GiB','cpu':'16GiB'}, no_split_module_classes=['CogVLMDecoderLayer', 'TransformerLayer'])
model = load_checkpoint_and_dispatch(
    model,
    'local/path/to/hf/version/chat/model',   # typical, '~/.cache/huggingface/hub/models--THUDM--cogvlm-chat-hf/snapshots/balabala'
    device_map=device_map,
)
model = model.eval()

# check device for weights if u want to
for n, p in model.named_parameters():
    print(f"{n}: {p.device}")

# chat example
query = 'Describe this image'
image = Image.open(requests.get('https://github.com/THUDM/CogVLM/blob/main/examples/1.png?raw=true', stream=True).raw).convert('RGB')
inputs = model.build_conversation_input_ids(tokenizer, query=query, history=[], images=[image])  # chat mode
inputs = {
    'input_ids': inputs['input_ids'].unsqueeze(0).to('cuda'),
    'token_type_ids': inputs['token_type_ids'].unsqueeze(0).to('cuda'),
    'attention_mask': inputs['attention_mask'].unsqueeze(0).to('cuda'),
    'images': [[inputs['images'][0].to('cuda').to(torch.bfloat16)]],
}
gen_kwargs = {"max_length": 2048, "do_sample": False}

with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0]))
代码同hf官方示例相同

### Expected behavior / 期待表现

了解oom产生的原因并解决

**Comment by zRzRzRzRzRzRzR** [comment]
你设置device map了吗，不然都会到第一张卡，然后直接报错显存不够

**Comment by zhaohongyin** [comment]
设置了的，运行的时候是正常两卡内存占用，但是最后在model前向的时候会报错，显示的显存需要是256G，这个大小感觉很奇怪。

> 你设置device map了吗，不然都会到第一张卡，然后直接报错显存不够

**Comment by yunbinmo** [comment]
你好，我想问下这个device map在哪个文件设置的呢？

**Comment by byerose** [comment]
解决了吗，遇到了同样的问题
