### ISSUE TITLE
Please release evaluation prompts

### ISSUE THREAD

**Issue by Patchwork53** [THUDM/CogVLM#384]
### Feature request  / 功能建议

Prompt format for open-ended (VQAv2) and multiple-choice (MMBench) VQA evaluation.

### Motivation / 动机

Since models are very sensitive to prompt structure, could you release the exact prompt format so that we can evaluate CogVLM optimally?

Something like [this](https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md) would be awesome.

TIA

### Your contribution / 您的贡献

TIA

**Comment by zRzRzRzRzRzRzR** [comment]
我们已经在代码中展现了所有的提示词，[这是](https://github.com/THUDM/CogVLM/blob/main/composite_demo/utils.py) 我们推理的提示词。

关于验证脚本，我们确实没有提供，同时，chat模型并不适合进行刷榜
