### ISSUE TITLE
怎么使用最新的模型？

### ISSUE THREAD

**Issue by jun0wanan** [THUDM/CogVLM#385]
### System Info / 系統信息

你好，我想测试最新的模型，有没有什么好的办法？

### Who can help? / 谁可以帮助到您？

@zr

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

有一个api我直接试，最好是免费的。

**Comment by jun0wanan** [comment]
非常抱歉，我目前无法提供你需要的具体信息，如果你有其他的问题或者需要查找其他信息，我非常乐意帮助你

我使用了zhipuai里面的网页双语版本，会报错误：

非常抱歉，我目前无法提供你需要的具体信息，如果你有其他的问题或者需要查找其他信息，我非常乐意帮助你

为什么会这样呢？

**Comment by 1049451037** [comment]
说明您想查询的内容涉及敏感内容。

**Comment by jun0wanan** [comment]
> 说明您想查询的内容涉及敏感内容。

你好，请问一下cogvlm最新双语版本有没有api，能够在代码里面调用？

感谢！

**Comment by 1049451037** [comment]
https://open.bigmodel.cn/dev/howuse/glm4v
