### ISSUE TITLE
如何使用CogVLM finetune训练自有数据集具有视觉定位能力的多模态大模型？

### ISSUE THREAD

**Issue by elesun2018** [THUDM/CogVLM#388]
官网描述如下：
![image](https://github.com/THUDM/CogVLM/assets/37207093/ecb55f10-15f0-4942-968e-9c1a93ea1a4d)
![image](https://github.com/THUDM/CogVLM/assets/37207093/1b14eb71-a00e-4eda-9489-f1f0cde51adb)

预训练模型使用cogvlm-grounding-generalist |   base 
原始图像尺寸：1024*768  512*324  ...
若某个图像中目标box换算为[086,540,400,760]，CogVLM数据预处理方式什么样的，统一resize到490*490么？Resize对box会有影响吗？
数据集样式这样可以吧：
Prompt：描述一下图片中的目标物体并指出目标所在区域[[x0,y0,x1,y1]]？
Label：图片中存在一只狗，所在区域为[[086,540,400,760]]
支持中文描述吧? box两侧没有星号“*”吧?
utils/utils/template.py caption_with_box caption2box模板 box2caption模板的作用是什么？是必须按照模板修改数据集样式吗？
![image](https://github.com/THUDM/CogVLM/assets/37207093/d1f35ee6-c575-4aa5-a2b8-b29866884466)

**Comment by elesun2018** [comment]
![image](https://github.com/THUDM/CogVLM/assets/37207093/fec86090-a4dc-41fa-95c4-71f6354feecd)
代码使用的是直接Resize方式，尺寸变化并不会引起比例变化，因此box不会发生变化

**Comment by elesun2018** [comment]
实验验证过，支持中文描述，box两侧没有星号，不用caption_with_box caption2box模板
训练什么问题答案，出什么想要的结果，还是比较易用的。

**Comment by TiantZhang** [comment]
请问微调的sh脚本是？

**Comment by danbao** [comment]
> 实验验证过，支持中文描述，box两侧没有星号，不用caption_with_box caption2box模板 训练什么问题答案，出什么想要的结果，还是比较易用的。

如果通过 prompt 查询没找到元素，如何让它返回固定语句（比如没找到某个元素）？

**Comment by zRzRzRzRzRzRzR** [comment]
加一句话，如果没找到 xxx ，就返回 ""应该是可以的
