### ISSUE TITLE
Multi Image Detection

### ISSUE THREAD

**Issue by S-15-77** [THUDM/CogVLM#391]
### Feature request  / 功能建议

Does COGVLM support multi-image, since most of the examples are only mentioned for single image and when i tried it gave an error
![image](https://github.com/THUDM/CogVLM/assets/72592108/ad0bc24f-a6bc-4c5c-8acb-f3715802acfb)

### Motivation / 动机

 For the Detection of Multi images

### Your contribution / 您的贡献

None

**Comment by chakrabortyrajatsubhra** [comment]
I also want to do a similar thing did you find a way to do it??

**Comment by zRzRzRzRzRzRzR** [comment]
no , it only support ONE image
