### ISSUE TITLE
Release quantization scripts

### ISSUE THREAD

**Issue by ntoxeg** [THUDM/CogVLM#392]
### Feature request  / 功能建议

I would like to see how a fine-tuned model of this could be quantized so that I can have my own 4 bit CogAgent-derived model.

### Motivation / 动机

While there is some code that one can adapt for fine-tuning purposes, the lack of quantization means that the resultant model has considerably higher hardware requirements (from 1xRTX 4090 —> 2xRTX 4090).

### Your contribution / 您的贡献

—

**Comment by zRzRzRzRzRzRzR** [comment]
it need to finetune in fp16 and for 4bit it use ByteTenor which may cause 

RuntimeError: Input type (torch.cuda.ByteTensor) and weight type (torch.cuda.HalfTensor) should be the same
