### ISSUE TITLE
Key_error :'INV_FREQ' 

### ISSUE THREAD

**Issue by S-15-77** [THUDM/CogVLM#396]
### System Info / 系統信息

Getting KeyError:  'INV_FRQ' while executing the 4bit quzntized model

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

model = AutoModelForCausalLM.from_pretrained(
        'THUDM/cogvlm-chat-hf',
        torch_dtype=torch.float16,
        low_cpu_mem_usage=True,
        load_in_4bit=True,
        trust_remote_code=True
).eval()

![image](https://github.com/THUDM/CogVLM/assets/72592108/882c35f5-43b3-4b47-b91b-65162f7d8697)

### Expected behavior / 期待表现

Expect to execute the 4bit model

**Comment by S-15-77** [comment]
Just downgrade the transformers version to 4.37.2.

**Comment by Jin-huihuang** [comment]
> Just downgrade the transformers version to 4.37.2.

nice

**Comment by emersonium** [comment]
> Just downgrade the transformers version to 4.37.2.

Hi, curious, how did you know this was the issue!

thanks

**Comment by emersonium** [comment]
I am trying to get the quant 4 to work with gardio "web demo", any tips ?

**Comment by S-15-77** [comment]
> > Just downgrade the transformers version to 4.37.2.
> 
> Hi, curious, how did you know this was the issue!
> 
> I am trying to get it to work with the "web_demo" gradio app, no luck so far, espeicaly not able to get the "with grounding" command to work for bounding boxes
> 
> thanks

Hey @emersonium 
The code was working fine for me the before day, then I later checked that this issue happened after the transformer got upgrades (checked the version). So I just check the previous update and tried it worked fine.

**Comment by JBurtn** [comment]
Note installing transformers from source no longer has this issue. Only 4.38.* does.
