### ISSUE TITLE
Inquiry on CogVLM's capacity for comprehension

### ISSUE THREAD

**Issue by PhilipAmadasun** [THUDM/CogVLM#397]
If provided with an image containing people with labelled bounding boxes around their faces (labelled with name, race, sex, and dominant facial emotion), can CogVLM coherently describe the people as well as information about each individual that matches the information provided by the label of each individuals bounding box. For example if someones bounding box is labeled (John, black, man, irritated), will  CogVLM be able to provide information as such: "The image contains a man called John, he is black and his dominant emotion shows irritation. Is this something CogVLM can be prompted to do?

**Comment by samueleruffino99** [comment]
I would be interested in a similar application. Namely, understanding of autonomous driving scenarion with 3d bounding boxes, class and velocities (maybe magnitude and direction). Would understand to describe the safetiness of this condition given the front monoview? Moreover would be possible to feed multiple images (like front view and BEV)?

**Comment by zRzRzRzRzRzRzR** [comment]
Currently, only a single image is supported, and 3D images and mixed conversations with multiple pictures are not supported.
