### ISSUE TITLE
请问预训练阶段训练了哪些参数？

### ISSUE THREAD

**Issue by xyfZzz** [THUDM/CogVLM#40]
你好，从论文中了解到，在sft阶段，除了视觉编码器之外的所有参数都进行了训练，那么请问一下在预训练阶段是冻结了哪些参数，训练了哪些参数呢？这部分我没有在论文中找到
谢谢！

**Comment by 1049451037** [comment]
cc @mactavish91 @Sleepychord

**Comment by Cuiunbo** [comment]
论文的模型架构图上标的感觉是预训练任务？

**Comment by mactavish91** [comment]
> 你好，从论文中了解到，在sft阶段，除了视觉编码器之外的所有参数都进行了训练，那么请问一下在预训练阶段是冻结了哪些参数，训练了哪些参数呢？这部分我没有在论文中找到 谢谢！

在预训练阶段，我们冻结了ViT和语言模型原本的参数，可以参考论文ablation study部分

**Comment by xyfZzz** [comment]
> > 你好，从论文中了解到，在sft阶段，除了视觉编码器之外的所有参数都进行了训练，那么请问一下在预训练阶段是冻结了哪些参数，训练了哪些参数呢？这部分我没有在论文中找到 谢谢！
> 
> 在预训练阶段，我们冻结了ViT和语言模型原本的参数，可以参考论文ablation study部分

好的，谢谢！
