### ISSUE TITLE
使用cogagent时，没有如何连接打开浏览器说明？如何连接手机app，有没有使用agent的教程

### ISSUE THREAD

**Issue by tl-mark** [THUDM/CogVLM#400]
### Feature request  / 功能建议

使用cogagent时，没有如何连接打开浏览器说明？如何连接手机app，有没有使用agent的教程

### Motivation / 动机

使用cogagent时，没有如何连接打开浏览器说明？如何连接手机app，有没有使用agent的教程

### Your contribution / 您的贡献

使用cogagent时，没有如何连接打开浏览器说明？如何连接手机app，有没有使用agent的教程

**Comment by zRzRzRzRzRzRzR** [comment]
这个模型仍然是要在Linux 上使用提示词进行引导的，关于对应的提示词，可以在论文中找到
