### ISSUE TITLE
Query pdf files instead of images

### ISSUE THREAD

**Issue by moncefarajdal** [THUDM/CogVLM#401]
### Feature request  / 功能建议

Dear CogVLM's authors,
Thank you for your outstanding work on MLLM.
In the demo, we can only query pictures. Is it possible to make the model process pdf files?

### Motivation / 动机

I want to implement the model in a personal project I'm currently working on

### Your contribution / 您的贡献

Thank you

**Comment by LeslieWongCV** [comment]
pip install pdf2image
