### ISSUE TITLE
Run the moodel on host (not locally)

### ISSUE THREAD

**Issue by samueleruffino99** [THUDM/CogVLM#403]
Hello and amazing work here!
I was wondering whether it is possible to run the model remotely and not locally without the web interface, since I have hardware constraints. (like the OpenAI API or something similar). Is the openai_demo does exactly the same thing?
Thank you!

**Comment by zRzRzRzRzRzRzR** [comment]
We provide a web page for online use. You can find it in the readme. You can also build it on a remote server and deploy it through the OpenAI API. Just use your local notebook to request it.
