### ISSUE TITLE
CogAgent上下文长度以及多图多轮对话问题

### ISSUE THREAD

**Issue by HarryZhou-618** [THUDM/CogVLM#404]
您好，最近关注到了CogAgent的工作，请问CogAgent支持的上下文输入长度是多少呢？另外想请问CogAgent是否支持多轮对话使用多张图？就是在每一轮对话中使用一张图片，期待您的答复

**Comment by WeiminLee** [comment]
不支持多图

**Comment by HarryZhou-618** [comment]
一次对话只能支持一张图吗？我的多图需求指的是每次对话需要一张图，但是可能一次对话要有多轮，所以会有多张图。如果期间更换了图片那么之前的上下文就会被删除吗？

**Comment by HarryZhou-618** [comment]
> 不支持多图
一次对话只能支持一张图吗？我的多图需求指的是每次对话需要一张图，但是可能一次对话要有多轮，所以会有多张图。如果期间更换了图片那么之前的上下文就会被删除吗？

**Comment by HarryZhou-618** [comment]
@WeiminLee 
一次对话只能支持一张图吗？我的多图需求指的是每次对话需要一张图，但是可能一次对话要有多轮，所以会有多张图。如果期间更换了图片那么之前的上下文就会被删除吗？

**Comment by zRzRzRzRzRzRzR** [comment]
对一次只能一张图
