### ISSUE TITLE
请问一个多模态大模型代替多个yolo检测小模型场景下多轮对话数据格式如何设计？

### ISSUE THREAD

**Issue by elesun2018** [THUDM/CogVLM#407]
请问一个多模态大模型代替多个yolo检测小模型场景下多轮对话数据格式如何设计？
已有3个yolo检测小模型：Yolo1模型检测10种car；Yolo2模型检测10种boat；Yolo3模型检测10种plane。现在想训练一个垂直多模态大模型代替多个yolo检测小模型，可以检测这30种标签。请问数据标签应该如何设计？
![image](https://github.com/THUDM/CogVLM/assets/37207093/71cd8117-d682-4ac7-8c56-b0e3e9d4906b)
目的是实现以下样式的多轮对话：
问1：图片中是哪个交通工具？
答1：汽车
问2：是什么类型的汽车？
答2：是一辆大众排轿车
问3：汽车有轮子吗？
答3：有。。。

总之，多模态大模型可以问答垂直场景图片但又不失去常识问答的能力？

**Comment by thiner** [comment]
使用chat模型就可以完成了吧。

**Comment by elesun2018** [comment]
能否详细解释一下，谢谢

**Comment by thiner** [comment]
对不起，没看清你问的是数据标签的设计问题。我以为你问的是选用什么样的模型。

**Comment by zRzRzRzRzRzRzR** [comment]
如果你希望代替yolo，你需要使用grounding模型才会有bbx输出

**Comment by elesun2018** [comment]
是的，我用的grounding模型。

目的是实现以下样式的多轮对话：
问1：图片中是哪个交通工具？
答1：汽车
问2：是什么类型的汽车？
答2：是一辆大众排轿车
问3：汽车有轮子吗？
答3：有。。。
应该如何设计数据标签和训练模式，谢谢

**Comment by elesun2018** [comment]
空了能否解答一下，实现楼上的对话模式。谢谢

**Comment by elesun2018** [comment]
空了能否解答一下，实现楼上的对话模式。谢谢

**Comment by elesun2018** [comment]
空了能否解答一下，实现楼上的对话模式。谢谢

**Comment by elesun2018** [comment]
能否解答一下，非常感谢
