### ISSUE TITLE
关于使用cli进行推理的问题

### ISSUE THREAD

**Issue by Rui-Hu01** [THUDM/CogVLM#41]
显卡是两张32G的V100
使用的模型是cogvlm-base-224

**Comment by Rui-Hu01** [comment]
具体运行如下(卡了很久, 感觉不太对) :
torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --version base --fp16
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2023-10-19 18:24:37,977] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-19 18:24:37,977] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-19 18:24:46,601] [WARNING] Failed to load bitsandbytes:No module named 'scipy'
[2023-10-19 18:24:46,601] [WARNING] Failed to load bitsandbytes:No module named 'scipy'
[2023-10-19 18:24:47,156] [INFO] building CogVLMModel model ...
[2023-10-19 18:24:47,156] [INFO] building CogVLMModel model ...
[2023-10-19 18:24:47,157] [INFO] [RANK 0] > initializing model parallel with size 2
[2023-10-19 18:24:47,179] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
[2023-10-19 18:25:07,324] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 8891516544
[2023-10-19 18:25:07,349] [INFO] [RANK 1]  > number of parameters on model parallel rank 1: 8891516544
[2023-10-19 18:25:15,579] [INFO] [RANK 0] > initializing model parallel with size 1
[2023-10-19 18:25:15,996] [INFO] [RANK 0] building CogVLMModel model ...
[2023-10-19 18:25:32,317] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 17637948928
[2023-10-19 18:25:47,897] [INFO] [RANK 0] global rank 0 is loading checkpoint /data/juicefs_sz_ocr/72151636/GIT/cogvlm/model_zoo/cogvlm-base-224/1/mp_rank_00_model_states.pt
[2023-10-19 18:26:25,158] [INFO] [RANK 0] > successfully loaded /data/juicefs_sz_ocr/72151636/GIT/cogvlm/model_zoo/cogvlm-base-224/1/mp_rank_00_model_states.pt
[2023-10-19 18:26:27,498] [INFO] [RANK 0] > initializing model parallel with size 2
欢迎使用 CogVLM-CLI ，输入图像URL或本地路径读图，继续输入内容对话，clear 重新开始，stop 终止程序
请输入图像路径或URL（回车进入纯文本对话）： 
用户：你好
No image is not supported!
请输入图像路径或URL（回车进入纯文本对话）： No image is not supported!
1.jpg
用户：描述图片
[v-dev-5-72151636-674cbc6d9b-dm5z5:77251:0:77251] Caught signal 8 (Floating point exception: integer divide by zero)
[v-dev-5-72151636-674cbc6d9b-dm5z5:77250:0:77250] Caught signal 8 (Floating point exception: integer divide by zero)
==== backtrace (tid:  77251) ====
 0 0x00000000000143c0 __funlockfile()  ???:0
 1 0x00000000025ba21d llvm::APIntOps::ScaleBitMask()  ???:0
 2 0x0000000000dc5a88 llvm::SelectionDAG::computeKnownBits()  SelectionDAG.cpp:0
 3 0x0000000000e3ed48 llvm::TargetLowering::SimplifyDemandedBits()  TargetLowering.cpp:0
 4 0x0000000000e3e14f llvm::TargetLowering::SimplifyDemandedBits()  TargetLowering.cpp:0
 5 0x0000000000e44f9f llvm::TargetLowering::SimplifyDemandedBits()  TargetLowering.cpp:0
 6 0x0000000000d0c896 (anonymous namespace)::DAGCombiner::SimplifyDemandedBits()  DAGCombiner.cpp:0
 7 0x0000000000d2914c (anonymous namespace)::DAGCombiner::visitXOR()  DAGCombiner.cpp:0
 8 0x0000000000d4288e (anonymous namespace)::DAGCombiner::visit()  DAGCombiner.cpp:0
 9 0x0000000000d4458d (anonymous namespace)::DAGCombiner::combine()  DAGCombiner.cpp:0
10 0x0000000000d45e4c llvm::SelectionDAG::Combine()  ???:0
11 0x0000000000e051a9 llvm::SelectionDAGISel::CodeGenAndEmitDAG()  SelectionDAGISel.cpp:0
12 0x0000000000e086f1 llvm::SelectionDAGISel::SelectAllBasicBlocks()  SelectionDAGISel.cpp:0
13 0x0000000000e0a9a2 llvm::SelectionDAGISel::runOnMachineFunction()  SelectionDAGISel.cpp:0
14 0x00000000014c86af llvm::MachineFunctionPass::runOnFunction()  MachineFunctionPass.cpp:0
15 0x00000000024da621 llvm::FPPassManager::runOnFunction()  LegacyPassManager.cpp:0
16 0x00000000024da8c1 llvm::FPPassManager::runOnModule()  LegacyPassManager.cpp:0
17 0x00000000024db327 llvm::legacy::PassManagerImpl::run()  LegacyPassManager.cpp:0
18 0x00000000007c4c8e triton::translateLLVMIRToPTX()  /project/lib/Target/PTX/PTXTranslation.cpp:89
19 0x00000000007c4c8e llvm::SmallVectorTemplateCommon<char, void>::end()  /root/.triton/llvm/llvm+mlir-14.0.6-x86_64-linux-gnu-centos-7-release/include/llvm/ADT/SmallVector.h:251
20 0x00000000007c4c8e triton::translateLLVMIRToPTX()  /project/lib/Target/PTX/PTXTranslation.cpp:92
21 0x0000000000736f59 init_triton_translation(pybind11::module_&)::{lambda(std::string, int, int)#3}::operator()()  /project/python/src/triton.cc:1470
22 0x0000000000736f59 init_triton_translation(pybind11::module_&)::{lambda(std::string, int, int)#3}::operator()()  /project/python/src/triton.cc:1461
23 0x000000000074cdf3 pybind11::cpp_function::initialize<init_triton_translation(pybind11::module_&)::{lambda(std::string, int, int)#3}, std::string, std::string, int, int, pybind11::name, pybind11::scope, pybind11::sibling, pybind11::return_value_policy>(init_triton_translation(pybind11::module_&)::{lambda(std::string, int, int)#3}&&, std::string (*)(std::string, int, int), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, pybind11::return_value_policy const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN()  /root/.triton/pybind11/pybind11-2.10.0/include/pybind11/detail/../cast.h:1441
24 0x000000000074cdf3 std::string::_M_rep()  /opt/rh/devtoolset-10/root/usr/include/c++/10/bits/basic_string.h:3369
25 0x000000000074cdf3 std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()  /opt/rh/devtoolset-10/root/usr/include/c++/10/bits/basic_string.h:3718
26 0x000000000074cdf3 call_impl<std::basic_string<char>, init_triton_translation(pybind11::module&)::<lambda(std::string, int, int)>&, 0, 1, 2, pybind11::detail::void_type>()  /root/.triton/pybind11/pybind11-2.10.0/include/pybind11/detail/../cast.h:1441
27 0x000000000074cdf3 call<std::basic_string<char>, pybind11::detail::void_type, init_triton_translation(pybind11::module&)::<lambda(std::string, int, int)>&>()  /root/.triton/pybind11/pybind11-2.10.0/include/pybind11/detail/../cast.h:1410
28 0x000000000074cdf3 operator()()  /root/.triton/pybind11/pybind11-2.10.0/include/pybind11/pybind11.h:249
29 0x000000000074cdf3 _FUN()  /root/.triton/pybind11/pybind11-2.10.0/include/pybind11/pybind11.h:224
30 0x0000000000720c50 pybind11::cpp_function::dispatcher()  /root/.triton/pybind11/pybind11-2.10.0/include/pybind11/pybind11.h:929
31 0x00000000004f5572 cfunction_call_varargs()  /usr/local/src/conda/python-3.8.18/Objects/call.c:743
32 0x00000000004f5572 PyCFunction_Call()  /usr/local/src/conda/python-3.8.18/Objects/call.c:773
33 0x00000000004e0e1b _PyObject_MakeTpCall()  /usr/local/src/conda/python-3.8.18/Objects/call.c:159
34 0x00000000004dcf0c _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:125
35 0x00000000004dcf0c _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:115
36 0x00000000004dcf0c call_function()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:4963
37 0x00000000004dcf0c _PyEval_EvalFrameDefault()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:3469
38 0x00000000004d70d1 PyEval_EvalFrameEx()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:741
39 0x00000000004e823c _PyFunction_Vectorcall()  /usr/local/src/conda/python-3.8.18/Objects/call.c:436
40 0x00000000004d84a9 _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:127
41 0x00000000004d84a9 _Py_CheckFunctionResult()  /usr/local/src/conda/python-3.8.18/Objects/call.c:25
42 0x00000000004d84a9 _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:128
43 0x00000000004d84a9 call_function()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:4963
44 0x00000000004d84a9 _PyEval_EvalFrameDefault()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:3500
45 0x00000000004d70d1 PyEval_EvalFrameEx()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:741
46 0x00000000004e823c _PyFunction_Vectorcall()  /usr/local/src/conda/python-3.8.18/Objects/call.c:436
47 0x00000000004d84a9 _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:127
48 0x00000000004d84a9 _Py_CheckFunctionResult()  /usr/local/src/conda/python-3.8.18/Objects/call.c:25
49 0x00000000004d84a9 _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:128
50 0x00000000004d84a9 call_function()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:4963
51 0x00000000004d84a9 _PyEval_EvalFrameDefault()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:3500
52 0x00000000004d70d1 PyEval_EvalFrameEx()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:741
53 0x00000000004e823c _PyFunction_Vectorcall()  /usr/local/src/conda/python-3.8.18/Objects/call.c:436
54 0x00000000004d9263 _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:127
55 0x00000000004d9263 _Py_CheckFunctionResult()  /usr/local/src/conda/python-3.8.18/Objects/call.c:25
56 0x00000000004d9263 _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:128
57 0x00000000004d9263 call_function()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:4963
=================================
==== backtrace (tid:  77250) ====
 0 0x00000000000143c0 __funlockfile()  ???:0
 1 0x00000000025ba21d llvm::APIntOps::ScaleBitMask()  ???:0
 2 0x0000000000dc5a88 llvm::SelectionDAG::computeKnownBits()  SelectionDAG.cpp:0
 3 0x0000000000e3ed48 llvm::TargetLowering::SimplifyDemandedBits()  TargetLowering.cpp:0
 4 0x0000000000e3e14f llvm::TargetLowering::SimplifyDemandedBits()  TargetLowering.cpp:0
 5 0x0000000000e44f9f llvm::TargetLowering::SimplifyDemandedBits()  TargetLowering.cpp:0
 6 0x0000000000d0c896 (anonymous namespace)::DAGCombiner::SimplifyDemandedBits()  DAGCombiner.cpp:0
 7 0x0000000000d2914c (anonymous namespace)::DAGCombiner::visitXOR()  DAGCombiner.cpp:0
 8 0x0000000000d4288e (anonymous namespace)::DAGCombiner::visit()  DAGCombiner.cpp:0
 9 0x0000000000d4458d (anonymous namespace)::DAGCombiner::combine()  DAGCombiner.cpp:0
10 0x0000000000d45e4c llvm::SelectionDAG::Combine()  ???:0
11 0x0000000000e051a9 llvm::SelectionDAGISel::CodeGenAndEmitDAG()  SelectionDAGISel.cpp:0
12 0x0000000000e086f1 llvm::SelectionDAGISel::SelectAllBasicBlocks()  SelectionDAGISel.cpp:0
13 0x0000000000e0a9a2 llvm::SelectionDAGISel::runOnMachineFunction()  SelectionDAGISel.cpp:0
14 0x00000000014c86af llvm::MachineFunctionPass::runOnFunction()  MachineFunctionPass.cpp:0
15 0x00000000024da621 llvm::FPPassManager::runOnFunction()  LegacyPassManager.cpp:0
16 0x00000000024da8c1 llvm::FPPassManager::runOnModule()  LegacyPassManager.cpp:0
17 0x00000000024db327 llvm::legacy::PassManagerImpl::run()  LegacyPassManager.cpp:0
18 0x00000000007c4c8e triton::translateLLVMIRToPTX()  /project/lib/Target/PTX/PTXTranslation.cpp:89
19 0x00000000007c4c8e llvm::SmallVectorTemplateCommon<char, void>::end()  /root/.triton/llvm/llvm+mlir-14.0.6-x86_64-linux-gnu-centos-7-release/include/llvm/ADT/SmallVector.h:251
20 0x00000000007c4c8e triton::translateLLVMIRToPTX()  /project/lib/Target/PTX/PTXTranslation.cpp:92
21 0x0000000000736f59 init_triton_translation(pybind11::module_&)::{lambda(std::string, int, int)#3}::operator()()  /project/python/src/triton.cc:1470
22 0x0000000000736f59 init_triton_translation(pybind11::module_&)::{lambda(std::string, int, int)#3}::operator()()  /project/python/src/triton.cc:1461
23 0x000000000074cdf3 pybind11::cpp_function::initialize<init_triton_translation(pybind11::module_&)::{lambda(std::string, int, int)#3}, std::string, std::string, int, int, pybind11::name, pybind11::scope, pybind11::sibling, pybind11::return_value_policy>(init_triton_translation(pybind11::module_&)::{lambda(std::string, int, int)#3}&&, std::string (*)(std::string, int, int), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, pybind11::return_value_policy const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN()  /root/.triton/pybind11/pybind11-2.10.0/include/pybind11/detail/../cast.h:1441
24 0x000000000074cdf3 std::string::_M_rep()  /opt/rh/devtoolset-10/root/usr/include/c++/10/bits/basic_string.h:3369
25 0x000000000074cdf3 std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()  /opt/rh/devtoolset-10/root/usr/include/c++/10/bits/basic_string.h:3718
26 0x000000000074cdf3 call_impl<std::basic_string<char>, init_triton_translation(pybind11::module&)::<lambda(std::string, int, int)>&, 0, 1, 2, pybind11::detail::void_type>()  /root/.triton/pybind11/pybind11-2.10.0/include/pybind11/detail/../cast.h:1441
27 0x000000000074cdf3 call<std::basic_string<char>, pybind11::detail::void_type, init_triton_translation(pybind11::module&)::<lambda(std::string, int, int)>&>()  /root/.triton/pybind11/pybind11-2.10.0/include/pybind11/detail/../cast.h:1410
28 0x000000000074cdf3 operator()()  /root/.triton/pybind11/pybind11-2.10.0/include/pybind11/pybind11.h:249
29 0x000000000074cdf3 _FUN()  /root/.triton/pybind11/pybind11-2.10.0/include/pybind11/pybind11.h:224
30 0x0000000000720c50 pybind11::cpp_function::dispatcher()  /root/.triton/pybind11/pybind11-2.10.0/include/pybind11/pybind11.h:929
31 0x00000000004f5572 cfunction_call_varargs()  /usr/local/src/conda/python-3.8.18/Objects/call.c:743
32 0x00000000004f5572 PyCFunction_Call()  /usr/local/src/conda/python-3.8.18/Objects/call.c:773
33 0x00000000004e0e1b _PyObject_MakeTpCall()  /usr/local/src/conda/python-3.8.18/Objects/call.c:159
34 0x00000000004dcf0c _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:125
35 0x00000000004dcf0c _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:115
36 0x00000000004dcf0c call_function()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:4963
37 0x00000000004dcf0c _PyEval_EvalFrameDefault()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:3469
38 0x00000000004d70d1 PyEval_EvalFrameEx()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:741
39 0x00000000004e823c _PyFunction_Vectorcall()  /usr/local/src/conda/python-3.8.18/Objects/call.c:436
40 0x00000000004d84a9 _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:127
41 0x00000000004d84a9 _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:128
42 0x00000000004d84a9 call_function()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:4963
43 0x00000000004d84a9 _PyEval_EvalFrameDefault()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:3500
44 0x00000000004d70d1 PyEval_EvalFrameEx()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:741
45 0x00000000004e823c _PyFunction_Vectorcall()  /usr/local/src/conda/python-3.8.18/Objects/call.c:436
46 0x00000000004d84a9 _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:127
47 0x00000000004d84a9 _Py_CheckFunctionResult()  /usr/local/src/conda/python-3.8.18/Objects/call.c:25
48 0x00000000004d84a9 _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:128
49 0x00000000004d84a9 call_function()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:4963
50 0x00000000004d84a9 _PyEval_EvalFrameDefault()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:3500
51 0x00000000004d70d1 PyEval_EvalFrameEx()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:741
52 0x00000000004e823c _PyFunction_Vectorcall()  /usr/local/src/conda/python-3.8.18/Objects/call.c:436
53 0x00000000004d9263 _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:127
54 0x00000000004d9263 _Py_CheckFunctionResult()  /usr/local/src/conda/python-3.8.18/Objects/call.c:25
55 0x00000000004d9263 _PyObject_Vectorcall()  /usr/local/src/conda/python-3.8.18/Include/cpython/abstract.h:128
56 0x00000000004d9263 call_function()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:4963
57 0x00000000004d9263 _PyEval_EvalFrameDefault()  /usr/local/src/conda/python-3.8.18/Python/ceval.c:3515
=================================

**Comment by 1049451037** [comment]
`No module named 'scipy'`

**Comment by 1049451037** [comment]
另外屏幕上已经显示了，不支持无图片模式，必须输入图片路径。

**Comment by Rui-Hu01** [comment]
> 外部屏幕上已经显示了，不支持无图片模式，必须输入图片路径。

嗯嗯, 是的，cli_demo里面的提示是回车进入纯文本对话, 所以就先尝试了一下, 结果好像不能进行纯文本对话

安装scipy之后, 还是会卡住

torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --version base --fp16

master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2023-10-19 19:04:57,310] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-19 19:04:57,337] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-19 19:05:01,062] [INFO] building CogVLMModel model ...
[2023-10-19 19:05:01,070] [INFO] building CogVLMModel model ...
[2023-10-19 19:05:01,074] [INFO] [RANK 0] > initializing model parallel with size 2
[2023-10-19 19:05:01,097] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
[2023-10-19 19:05:17,883] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 8891516544
[2023-10-19 19:05:20,979] [INFO] [RANK 1]  > number of parameters on model parallel rank 1: 8891516544
[2023-10-19 19:05:24,309] [INFO] [RANK 0] > initializing model parallel with size 1
[2023-10-19 19:05:28,949] [INFO] [RANK 0] building CogVLMModel model ...
[2023-10-19 19:05:43,628] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 17637948928
[2023-10-19 19:05:58,371] [INFO] [RANK 0] global rank 0 is loading checkpoint /data/juicefs_sz_ocr/72151636/GIT/cogvlm/model_zoo/cogvlm-base-224/1/mp_rank_00_model_states.pt
[2023-10-19 19:06:36,667] [INFO] [RANK 0] > successfully loaded /data/juicefs_sz_ocr/72151636/GIT/cogvlm/model_zoo/cogvlm-base-224/1/mp_rank_00_model_states.pt
[2023-10-19 19:06:39,413] [INFO] [RANK 0] > initializing model parallel with size 2
欢迎使用 CogVLM-CLI ，输入图像URL或本地路径读图，继续输入内容对话，clear 重新开始，stop 终止程序
请输入图像路径或URL（回车进入纯文本对话）： 1.jpg
用户：描述图片
[v-dev-5-72151636-674cbc6d9b-dm5z5:77775:0:77775] Caught signal 8 (Floating point exception: integer divide by zero)
[v-dev-5-72151636-674cbc6d9b-dm5z5:77774:0:77774] Caught signal 8 (Floating point exception: integer divide by zero)

然后就卡这里了, 卡了十几分钟无响应了, 用的torch是2.0.1, cuda是11.7这样子, 我看你那边用的12.2, 必须是这个版本的么

**Comment by 1049451037** [comment]
你的version写错了，version是chat不是base。另外CogVLM不支持中文。

**Comment by waltonfuture** [comment]
> 如果你使用的是cogvlm-base-224，需要加入--no_prompt参数。
> 
> 正确的命令应该是：
> 
> ```
> torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --version base --bf16 --no_prompt
> ```

![image](https://github.com/THUDM/CogVLM/assets/98318797/69e54b14-550b-4119-883f-0e6c350bd5c6)
我使用chat模型遇到这个问题。请问这也是pytorch/cuda版本的问题吗

**Comment by waltonfuture** [comment]
> > 如果你使用的是cogvlm-base-224，需要加入--no_prompt参数。
> > 正确的命令应该是：
> > ```
> > torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --version base --bf16 --no_prompt
> > ```
> 
> ![image](https://user-images.githubusercontent.com/98318797/276634174-69e54b14-550b-4119-883f-0e6c350bd5c6.png) 我使用chat模型遇到这个问题。请问这也是pytorch/cuda版本的问题吗

torch是2.0.1，cuda是11.8

**Comment by zRzRzRzRzRzRzR** [comment]
我们会在一周内更新[技术文档](https://lslfd0slxc.feishu.cn/wiki/WvQbwIJ9tiPAxGk8ywDck6yfnof),可以关注一下
