### ISSUE TITLE
关于cogvlm模型是否支持目标检测功能呢

### ISSUE THREAD

**Issue by FZGgithub** [THUDM/CogVLM#410]
我希望输入一张图片，并让模型给我标记出该图片中的某个东西（一辆车，一个人，等。。）
模型的返回是文本+图片的形式。
我在http://36.103.203.44:7861/中发现，将grounding勾选上，可以返回完成边框标记的图像和相关文本。
如果我使用的基础模型是cogvlm_base_490，这个功能目前能够支持吗

**Comment by DDQQWU** [comment]
您好，请问这个问题解决了吗？

**Comment by zRzRzRzRzRzRzR** [comment]
+ grounding就行了的，你选择的这个是预训练模型，没有做对齐，不行，你选择grounding 的模型

**Comment by FZGgithub** [comment]
@zRzRzRzRzRzRzR 请问是cogvlm-grounding-generalist-v1.1这个模型吗
