### ISSUE TITLE
CogVLM微调是否能支持导出lora adapter并在hf权重模型上merge

### ISSUE THREAD

**Issue by Hiralive** [THUDM/CogVLM#415]
### Feature request  / 功能建议

如题，是否能支持导出微调后的lora adapter。并在cogvlm的hf权重上进行merge？

### Motivation / 动机

由于当前官方没支持hf的lora微调，是否可以通过sat微调后将adapter转为hf的形式？

### Your contribution / 您的贡献

NA

**Comment by zRzRzRzRzRzRzR** [comment]
可以，但是我们没有做这个代码，我们现在都在sat上进行推理和训练

**Comment by Hiralive** [comment]
> 可以，但是我们没有做这个代码，我们现在都在sat上进行推理和训练

sat未来会提供支持将lora adapter转为hf吗？

**Comment by zRzRzRzRzRzRzR** [comment]
可以，但是现在开发人员比较忙，暂时没人做
