### ISSUE TITLE
how to deny the auto created output.png

### ISSUE THREAD

**Issue by HarryXuancy** [THUDM/CogVLM#416]
### System Info / 系統信息

does not matter

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.run the cli_demo_sat.py
2. an output.png is created in basic_demo/

### Expected behavior / 期待表现

I wonder where does the png generated and want to deny it. Thank you.

**Comment by zRzRzRzRzRzRzR** [comment]
This model is an image understanding model, not an image generation model, and cannot generate pictures.

**Comment by HarryXuancy** [comment]
Hello, maybe you can pay attention to my description in "Reproduction". I notice that every time I finished the conversation with model, there will be an output.png in the basic_demo folder, which is the last picture that i showed to the cogagent. I guess it is recorded during the response process but i don't know where the exact code is. By the way, i use the sat version cli, the exact command is "python cli_demo_sat.py --from_pretrained cogagent-vqa --version chat_old --bf16  --stream_chat"
