### ISSUE TITLE
现在似乎只能微调？没有有全参数训练的代码呢

### ISSUE THREAD

**Issue by WibotAI** [THUDM/CogVLM#417]
### Feature request  / 功能建议

希望提供全参数训练

### Motivation / 动机

单纯学习

### Your contribution / 您的贡献

没有

**Comment by zRzRzRzRzRzRzR** [comment]
有啊，都是sat格式的

**Comment by WibotAI** [comment]
> 有啊，都是sat格式的

全参数训练对机器要求大概什么水平？
