### ISSUE TITLE
Web demo无法对话。

### ISSUE THREAD

**Issue by serend1p1ty** [THUDM/CogVLM#418]
尝试让CogVLM-chat描述图像，但是返回的信息是`error`。
![image](https://github.com/THUDM/CogVLM/assets/39628662/7cb931f0-8a70-43d1-adb1-2e5719e5778d)
但是grounding模型就可以正常工作。
![image](https://github.com/THUDM/CogVLM/assets/39628662/98a4985c-fbaa-43ed-99e9-904556e96810)

**Comment by Luohh5** [comment]
请问解决了吗

**Comment by elesun2018** [comment]
同问

**Comment by zRzRzRzRzRzRzR** [comment]
应该是服务器已经关闭

**Comment by YangJae96** [comment]
@serend1p1ty  Hi

I'm also facing the same problem in web demo. 
How did you solve the error?
