### ISSUE TITLE
Multiple images analysis

### ISSUE THREAD

**Issue by sskorol** [THUDM/CogVLM#42]
Hi,

Can this model be used for multi-image analysis and correlation detection? For instance, GPT-4V allows uploading several images and creating a prompt where you can ask to find the relationships between objects on different images. Is it possible to do the same with `CogVLM`? Or can it analyze only a single image?

Thanks,
Serhii

**Comment by 1049451037** [comment]
FYI: https://github.com/THUDM/CogVLM/issues/38
