### ISSUE TITLE
cogagent-chat模型对Visual Grounding query的response不正确

### ISSUE THREAD

**Issue by zhaopy10** [THUDM/CogVLM#422]
### System Info / 系統信息

官方Webdemo和cli_demo_hf.py脚本均可验证

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

提供一张UI图片，使用[caption2box template]的query定位UI元素位置，模型的response大部分情况会按Agent里Plan+Action的方式输出
![screenshot-20240322-122753](https://github.com/THUDM/CogVLM/assets/13568828/5d6def98-7098-4826-b1c0-df594012ee43)

### Expected behavior / 期待表现

正确输出bbox坐标

**Comment by zRzRzRzRzRzRzR** [comment]
用cogvlm的template 而不是cogagent的template 不然就会按照agent的方式输出
