### ISSUE TITLE
请问模型加入auto-regressive是什么用途

### ISSUE THREAD

**Issue by elesun2018** [THUDM/CogVLM#424]
请问model.add_mixin('auto-regressive', CachedAutoregressiveMixin())是什么用途
![image](https://github.com/THUDM/CogVLM/assets/37207093/c7c15ed2-434c-47cf-8e1c-1777ff19817e)
model.del_mixin('auto-regressive')呢
![image](https://github.com/THUDM/CogVLM/assets/37207093/4eb7caac-c593-4d3b-b478-4d80433948ad)
什么时候需要add_mixin  auto-regressive

**Comment by 1049451037** [comment]
在generate的过程中保存kv_cache。
