### ISSUE TITLE
CogVLM源代码是否支持多轮对话训练

### ISSUE THREAD

**Issue by elesun2018** [THUDM/CogVLM#428]
请问CogVLM源代码支持多轮对话吗？
CogVLM-SFT-311K  llava_instruction_multi_conversations_formate
![image](https://github.com/THUDM/CogVLM/assets/37207093/a1082dec-d36a-4147-ae3d-97cff86dbb61)
预训练模型应该选择哪个？ cogvlm-base-490？
单轮对话和多轮对话在代码方面主要区别
或者说主要修改哪部分代码可以实现多轮对话训练
谢谢

**Comment by elesun2018** [comment]
![image](https://github.com/THUDM/CogVLM/assets/37207093/51ada134-50a6-44f5-9de4-ed4caf4fc149)
应该基于哪个模型训练自有多轮对话数据集
多论对话和单轮对话数据集读取方面有差异吗

**Comment by elesun2018** [comment]
![image](https://github.com/THUDM/CogVLM/assets/37207093/51ada134-50a6-44f5-9de4-ed4caf4fc149)
应该基于哪个模型训练自有多轮对话数据集
多论对话和单轮对话数据集读取方面有差异吗

**Comment by zRzRzRzRzRzRzR** [comment]
支持多轮对话训练，但是要按照sat格式，我们没有hf格式微调

**Comment by elesun2018** [comment]
多轮对话是采用这个吗 chat_old_history_to_prompt
如果数据标签为图文对：问1，答1，问2，答2
chat_old_history_to_prompt生成prompt=问1，答1，问2，预测结果与答2计算loss ？
这样的一条数据：问1，答1，问2，答2。要在网络里面训练几次？
第一次：训练 prompt=问1，第二次训练prompt=问1，答1，问2 ？
对于dataset.py有应该如何读取多轮对话数据标签：
![image](https://github.com/THUDM/CogVLM/assets/37207093/026b113e-0d60-4540-a109-92e3ad271592)

**Comment by elesun2018** [comment]
这问题能否解答一下，怎么关闭了
谢谢

**Comment by elesun2018** [comment]
这问题能否解答一下
谢谢

**Comment by elesun2018** [comment]
这问题能否解答一下
谢谢

**Comment by elesun2018** [comment]
能否解答一下，非常感谢
