### ISSUE TITLE
AMD Support

### ISSUE THREAD

**Issue by userbox020** [THUDM/CogVLM#43]
Hello, 
Would like to run the model but I only have that amount of vram avalible with amd gpus

**Comment by userbox020** [comment]
going to check and go back here with pytorch version and rocm version used to register if mine versions works

**Comment by userbox020** [comment]
do you have discord or telegram group where i can join bro?

**Comment by 1049451037** [comment]
No discord or telegram group yet. We have slack group: https://join.slack.com/t/chatglm/shared_invite/zt-1y7pqoloy-9b1g6T6JjA8J0KxvUjbwJw and wechat groups here: https://github.com/THUDM/VisualGLM-6B/blob/main/examples/WECHAT.md
