### ISSUE TITLE
web demo无法中文对话，但可以英文对话

### ISSUE THREAD

**Issue by ydygxu123** [THUDM/CogVLM#433]
### System Info / 系統信息

网页端进行图片问答，使用中文时报错
![20240402-155737](https://github.com/THUDM/CogVLM/assets/56526929/ba40e693-46dc-47b6-ad38-f2b60fc07c37)
使用英文时又是正常的
![20240402-160129](https://github.com/THUDM/CogVLM/assets/56526929/86d8a66f-fe89-477f-8454-8be1127d5ec8)
![20240402-160138](https://github.com/THUDM/CogVLM/assets/56526929/2cfbfdbb-0e01-4a1e-a760-1f80f01a4c93)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

http://36.103.203.44:7861/
该网址进行demo测试

### Expected behavior / 期待表现

前两礼拜用的时候中文英文都是正常，今天发现中文的用不了了，请问有大神知道是发生了什么吗？

**Comment by zRzRzRzRzRzRzR** [comment]
demo 已经升级到了 cogvlm2版本，您可以查看我们最新的demo尝试，模型已经有支持中文的版本
