### ISSUE TITLE
which model does the web demo use?

### ISSUE THREAD

**Issue by uestcMeng** [THUDM/CogVLM#44]
thanks for sharing your work!
I have tried the cogvlm-base-224 and cogvlm-base-490 with cli_demo.py, I use the the same image and text input, but get different answer, and the cli_demo's answer seems be incoherent and inconsistent with the image. The answer of web demo is detailed and accurate, however, the answer I got is very short and not accurate. I use the following command:
`python cli_demo.py --from_pretrained /local_path/cogvlm-base-490 --local_tokenizer /local_path/vicuna-7b-v1.5 --version base --english --bf16 --no_prompt --top_k 5`
I download all the ckpt to the local_path, so I use local path to load model. Could tell me how to get the performance like the web demo show. thanks a lot.

**Comment by 1049451037** [comment]
If you want detailed and accurate answer, you should use cogvlm-chat.

**Comment by bakachan19** [comment]
Hello @1049451037,
what would be the best parameters for temperature, top_p, top_k, for the model to generate the most detailed and accurate answers (i.e. image captions)? thank you

**Comment by 1049451037** [comment]
cc @iyuge2

**Comment by uestcMeng** [comment]
> If you want detailed and accurate answer, you should use cogvlm-chat.

thanks, cogvlm-chat works well.

**Comment by papasanimohansrinivas** [comment]
@1049451037  is cogvlm-chat model weights are purposable for commercial applications ? , I have seen the paper , it seems their training data is some what came from gpt4-text  right ? asking this clarification

**Comment by zRzRzRzRzRzRzR** [comment]
the web demo are updated,and cogagent-chat cogvlm-chat cogvlm-grounding will be used
