### ISSUE TITLE
网页demo的训练权重和部署公开的chat版本一致吗？可以公布最新的网页版demo权重吗

### ISSUE THREAD

**Issue by AugWrite** [THUDM/CogVLM#449]
### Feature request  / 功能建议

我用相同图片和问题在demo的图文chat 和本地部署的权重模型得到了不同的回答。似乎网页demo 的模型回答更合理，请问是有更新吗？如果有更新的话会开源网页版的chat模型权重吗？

### Motivation / 动机

希望可以开源网页demo的模型参数。

### Your contribution / 您的贡献

谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
在本仓库的网页体验版一致， 但是提供到api的和智谱清言不是开源的这个
