### ISSUE TITLE
复合demo没有正常流式输出？

### ISSUE THREAD

**Issue by xjtupanda** [THUDM/CogVLM#453]
### System Info / 系統信息

我在直接体验主页提供的[复合demo](http://36.103.203.44:7861)，测试了CogVLM-Chat和CogAgent-Chat，它们的输出都是最后才一次输出的，而不是流式输出。我看了相关的实现代码，其中应该有支持流式输出的部分，但是好像没有work?

### Who can help? / 谁可以帮助到您？

@zr

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行主页提供的[复合demo](http://36.103.203.44:7861)

### Expected behavior / 期待表现

模型的回答以流式输出的方式实时更新

**Comment by xjtupanda** [comment]
可以再提个请求吗？现在上传的图片是没有预览的，要加入prompt开始生成后才能看到，能否像gradio上传图片那样显示图片的预览呢?

**Comment by zRzRzRzRzRzRzR** [comment]
这个是gradio的页面设置吧，之后考虑更新
