### ISSUE TITLE
Installation instructions are insufficient

### ISSUE THREAD

**Issue by cmdr64** [THUDM/CogVLM#458]
### Feature request  / 功能建议

The following useful information is not provided in the readme.md and the requirements.txt are insufficient to install the program
  1. What version of python is required
  2. What operating system is required
  3. What hardware it has been tested on CPU, GPU, etc
  4. What system requirements are there: RAM/VRAM/CUDA microarchitecture version

### Motivation / 动机

I had many problems trying to install it on windows 10 AND Ubuntu (through WSL2).  
If neither Windows nor WSL2 Ubuntu are supported, it would be kind to let us know in the readme.md

### Your contribution / 您的贡献

I have no contribution for this.  If the original authors provided the above requested information it would be extremely valuable.

**Comment by zRzRzRzRzRzRzR** [comment]
需要使用 Linux 发行版，因为有xformers的限制
GPU：A100，如果你是int4 可以在 3090上运行
