### ISSUE TITLE
The grounding detection frame coordinates are inconsistent with the image resolution.

### ISSUE THREAD

**Issue by JoaquinChou** [THUDM/CogVLM#46]
I try to ground the picture in this sites. The image solution is 288*296. However, the CogVLM said that the coordinates of the person is [[097, 514, 283, 996]]. Is the solution of the picture having changed before the model infer?

**Comment by 1049451037** [comment]
The output integers are not absolute coordinates. They are the proportion of the axis, i.e., [0.097, 0.514, 0.283, 0.996].

**Comment by JoaquinChou** [comment]
By the way, last time we try to input the prompt "Is there any pesons?" with the this [image](http://36.103.203.44:7861/file=/home/wangyan/project/hft/CogVLM/examples/1.png). However, the model only output one bounding box. Generally, when there are multiple objects in the image, the model only tends to predict a box.

**Comment by Sleepychord** [comment]
The traditional REC task tends to find only one thing, but you are right it is better to support many (like detection). I think training on detection data can solve this problem.
