### ISSUE TITLE
关于模型量化

### ISSUE THREAD

**Issue by elesun2018** [THUDM/CogVLM#461]
能否说下 cog量化的基本过程，以及注意事项

quantize(model, args.quant)

![image](https://github.com/THUDM/CogVLM/assets/37207093/d14a762b-40de-4aad-8e0f-0f972346266f)
这个没看明白
谢谢

``--fp16 --quant 4``, or ``--fp16 --quant 8``
# In SAT version，--quant should be used with --fp16
请问现在SAT模型支持量化推理实现吗

**Comment by zRzRzRzRzRzRzR** [comment]
--fp16 不要写

**Comment by elesun2018** [comment]
不加入fp16 
git0322-CogVLM/basic_demo# python web_demo.py --from_pretrained cogvlm-base-490 --version base --stream_chat --quant 4
又出现了问题：
模型：error message Input type (c10::Half) and bias type (float) should be the same

请问不是torch xformer apex cudnn版本的问题吧

**Comment by elesun2018** [comment]
readme里面有提示啊：# In SAT version，--quant should be used with --fp16

**Comment by elesun2018** [comment]
git0322-CogVLM/basic_demo# python cli_demo_hf.py --from_pretrained hugcog1125/cogvlm-chat-hf --quant 4
Floating point exception (core dumped)

**Comment by elesun2018** [comment]
使用原来的cuda11.8镜像，多次尝试匹配torch xforms不同版本，不断出现新问题。
使用cuda12.1的新镜像，Floating point exception (core dumped)就消失了。
估计是跟cuda cudnn有关系。
git0322-CogVLM/basic_demo# python web_demo.py --from_pretrained cogvlm-base-490 --version base --stream_chat --fp16 --quant 4   OK
git0322-CogVLM/basic_demo# python web_demo.py --from_pretrained cogvlm-base-490 --version base --stream_chat --fp16 --quant 8   OK
git0322-CogVLM/basic_demo# python web_demo.py --from_pretrained cogvlm-base-490 --version base --stream_chat --fp16  OK

**Comment by elesun2018** [comment]
测试发现：
quant 4bit 推理占用显存29G
quant 8bit 推理占用显存38G
 不量化      推理占用显存42G
显存占用正常吗，有没有办法让quant 4bit 占用的显存小于24G，可以在4090显卡上运行？

**Comment by elesun2018** [comment]
web demo 4bit 显存占用12G.
eval评估代码 4bit后显存占用29G。
请问如何控制eval占用显存过大。修改代码位置

**Comment by elesun2018** [comment]
web demo 4bit 显存占用12G.
eval评估代码 4bit后显存占用29G。
请问如何控制eval占用显存过大。修改代码位置

**Comment by liangdebugger** [comment]
> 使用原来的cuda11.8镜像，多次尝试匹配torch xforms不同版本，不断出现新问题。 使用cuda12.1的新镜像，Floating point exception (core dumped)就消失了。 估计是跟cuda cudnn有关系。 git0322-CogVLM/basic_demo# python web_demo.py --from_pretrained cogvlm-base-490 --version base --stream_chat --fp16 --quant 4 OK git0322-CogVLM/basic_demo# python web_demo.py --from_pretrained cogvlm-base-490 --version base --stream_chat --fp16 --quant 8 OK git0322-CogVLM/basic_demo# python web_demo.py --from_pretrained cogvlm-base-490 --version base --stream_chat --fp16 OK

想问一下，最后选择了什么版本的 torch 与xformers 呢？

**Comment by elesun2018** [comment]
torch                     2.2.1+cu121
xformers                  0.0.25

**Comment by elesun2018** [comment]
你好，还有一个关于量化的后续问题
4bit量化后显存12G，但是内存占用率还是比较大，出现了OOM错误。
如何减少内存使用
能否保存量化后的模型，加载量化后的模型进行推理，这样内存是否会降低，是否可行，谢谢！

**Comment by elesun2018** [comment]
空了能否解答一下，谢谢
