### ISSUE TITLE
GPU selection / multi-GPU

### ISSUE THREAD

**Issue by jferments** [THUDM/CogVLM#462]
### Feature request  / 功能建议

I have a dual GPU system, and CogVLM is defaulting to the GPU that is already being used by other applications, and doesn't have sufficient memory. I would like to make it choose the other GPU, so it would be nice if there was a way to specify which GPU device to use.

Additionally, it would be helpful to split the model across multiple GPUs, to be able to run larger quants than can fit in VRAM on single GPU. 

### Motivation / 动机

Allow users with multiple GPUs to select which GPU to use.

Allow users to split models across multiple GPUs.

### Your contribution / 您的贡献

I do not have a PR at this time.

**Comment by Anirudh257** [comment]
Have you tried adding `device_map='auto'` to the model definition?

**Comment by zRzRzRzRzRzRzR** [comment]
device_map='auto' 就行了

**Comment by Rafael-sick** [comment]
where to add this argument--device_map='auto' ?

my setting is as below:
![image](https://github.com/user-attachments/assets/69497a9c-0edd-46ec-8bb0-d2f2a53ac39c)

edited test_config.json, still 8 GPUs working
 ![image](https://github.com/user-attachments/assets/2ae9c2ca-edd7-4f21-beee-701a62d9e569)
 
 But always eight GPUs on work. Headache
![image](https://github.com/user-attachments/assets/e3361b59-1705-467d-8792-6ea3293abde6)
