### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by liangdebugger** [THUDM/CogVLM#463]
I'm trying to deploy it by myself

python cli_demo_sat.py --from_pretrained cogagent-chat --version chat --bf16  --stream_chat

It failed and the error messages are as follows:

OSError: Can't load tokenizer for 'lmsys/vicuna-7b-v1.5'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'lmsys/vicuna-7b-v1.5' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.

What should I do? Looking forward to your reply

**Comment by liangdebugger** [comment]
Won't this file be downloaded automatically? Where should I go to download it？

**Comment by a798047815** [comment]
hi how do you fix this, met the same problem
