### ISSUE TITLE
Running Gradio app locally results in inappropriate error: "NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE."

### ISSUE THREAD

**Issue by aus10powell** [THUDM/CogVLM#467]
### System Info / 系統信息

Local: Apple M2 Pro, 32GB Ram
<img width="1303" alt="Screenshot 2024-04-25 at 11 34 14 AM" src="https://github.com/THUDM/CogVLM/assets/7726251/dba8c268-2f8f-401f-88cc-82dd7747eb4d">

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Follow instructions on README.md for running Gradio

### Expected behavior / 期待表现

Some sort of response from the app

**Comment by zRzRzRzRzRzRzR** [comment]
Try use our gradio instead of llava
