### ISSUE TITLE
Using CogVLM as an API

### ISSUE THREAD

**Issue by moncefarajdal** [THUDM/CogVLM#468]
### Feature request  / 功能建议

Hello guys,
Thank you so much for you hard work.
I was wondering if there's any way I could use CogVLM as an api so I can send some requests from my Python app just to test it. I don't have the required hardware to run a local version of it so that's why I was wondering if such feature exists or not.

Thank you

**Comment by zRzRzRzRzRzRzR** [comment]
so may be you can use a server and use openai demo in this repos.  We do not provide api  of cogvlm. 
you can use https://open.bigmodel.cn/ to use our commercial model api.
