### ISSUE TITLE
Code of finetuning the cogagent on Mind2Web ?

### ISSUE THREAD

**Issue by leoozy** [THUDM/CogVLM#469]
Thank you very much for your work. May I ask if it's possible to share the code on how to finetune the cogagent on Mind2Web ?

**Comment by zRzRzRzRzRzRzR** [comment]
No plan for this. You can use finetune.py and ae mind2web datset to #Instruct or #CogcCOM dataset formate

**Comment by xiapengchng** [comment]
can you share the finetune code ?
