### ISSUE TITLE
web demo does not work

### ISSUE THREAD

**Issue by wangkunyu241** [THUDM/CogVLM#47]
The website demo does not work, showing "Timeout! Please wait a few minutes and retry.", can you fix it?

**Comment by LokiLord** [comment]
I encountered the same problem, have you solved it?

**Comment by LokiLord** [comment]
> The website demo does not work, showing "Timeout! Please wait a few minutes and retry.", can you fix it?

I encountered the same problem, have you solved it?

**Comment by wangkunyu241** [comment]
For me, wait a seconds. it works. So i close the issue.



---Original---
From: ***@***.***&gt;
Date: Thu, Oct 26, 2023 17:18 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [THUDM/CogVLM] web demo does not work (Issue #47)




  
The website demo does not work, showing "Timeout! Please wait a few minutes and retry.", can you fix it?
  
I encountered the same problem, have you solved it?
