### ISSUE TITLE
Deploy CogVLM using Docker

### ISSUE THREAD

**Issue by moncefarajdal** [THUDM/CogVLM#470]
### Feature request  / 功能建议

Hello,
Is it possible to deploy CogVLM using Docker on OVH Cloud? I want to send requests to basic_demo/cli_demo_sat.py file

Can someone please explain to me the deployment process as I want to integrate CogVLM with an existent app and connect both of them using Restful APIs

Thanks

**Comment by zRzRzRzRzRzRzR** [comment]
For Now We do not have this plan,thanks for your attention
