### ISSUE TITLE
CogVLM源代码是否支持多轮对话训练

### ISSUE THREAD

**Issue by elesun2018** [THUDM/CogVLM#475]
多轮对话是采用这个吗 chat_old_history_to_prompt
如果数据标签为图文对：问1，答1，问2，答2
chat_old_history_to_prompt生成prompt=问1，答1，问2，预测结果与答2计算loss ？
这样的一条数据：问1，答1，问2，答2。要在网络里面训练几次？
第一次：训练 prompt=问1，第二次训练prompt=问1，答1，问2 ？
对于dataset.py有应该如何读取多轮对话数据标签：
![image](https://github.com/THUDM/CogVLM/assets/37207093/f679cded-0bfb-4544-8996-2984cd794b58)

使用sat格式微调，如何进行多轮对话训练。
主要修改哪部分代码可以实现多轮对话训练。

是要调用chat_old_history_to_prompt吗
![image](https://github.com/THUDM/CogVLM/assets/37207093/dc6c26e6-a445-461b-a3a6-9ae78abcb84f)

应该基于哪个模型训练自有多轮对话数据集
多论对话和单轮对话数据集读取方面有差异吗
![image](https://github.com/THUDM/CogVLM/assets/37207093/e3992d69-4425-40a8-ac6f-daff0108efa4)

**Comment by elesun2018** [comment]
预训练模型应该选择哪个？ cogvlm-base-490？
单轮对话和多轮对话在代码方面主要区别
或者说主要修改哪部分代码可以实现多轮对话训练
![image](https://github.com/THUDM/CogVLM/assets/37207093/b1c84afa-aedb-4929-8476-0788a64a9c30)

**Comment by elesun2018** [comment]
问1，答1，问2，答2
应该如何设计数据格式和训练模式。
![image](https://github.com/THUDM/CogVLM/assets/37207093/bbde345b-73dc-466d-8623-6bea95fe96d6)

**Comment by elesun2018** [comment]
我用的grounding模型。

目的是实现以下样式的多轮对话：
问1：图片中是哪个交通工具？
答1：汽车
问2：是什么类型的汽车？
答2：是一辆大众排轿车
问3：汽车有轮子吗？
答3：有。。。
应该如何设计数据标签和训练模式，谢谢

**Comment by elesun2018** [comment]
能否解答一下，非常感谢

**Comment by zRzRzRzRzRzRzR** [comment]
支持，我们开源的数据集就有多轮对话
