### ISSUE TITLE
如何构建CogAgent的微调数据集？

### ISSUE THREAD

**Issue by Li-mingshen** [THUDM/CogVLM#478]
官方给出的数据集Captcha Images只有图片没有labels，那么如果自己想构建自己的专有数据集（包括图片与图片的描述），json文件应该如何书写呢？dataset.py文件又应该如何修改呢？感谢各位大佬给出解答！！！小弟感激不尽。

**Comment by 1212wuhu** [comment]
https://github.com/THUDM/CogVLM/issues/63
参阅上面的内容
