### ISSUE TITLE
两张3090微调CogVLM的可能性？

### ISSUE THREAD

**Issue by KDD2018** [THUDM/CogVLM#479]
请教下，有大佬尝试过使用两张RTX3090微调CogVLM嘛？有可能性嘛？

**Comment by zRzRzRzRzRzRzR** [comment]
BF16不可能（模型本身推理就要占用36G，微调的时候图像的padding也是要加入到token中的，仅预留了8G-10G是不行的），int4魔改代码理论可行，但是实际操作还是比较困难的。
