### ISSUE TITLE
这个可以拿来做PI CI图片信息抽取吗？

### ISSUE THREAD

**Issue by zhangquanwei962** [THUDM/CogVLM#48]
你好，作者，很感谢你的工作，我拿来测试了一下相关的PI CI图片，我的目标是让模型得到有关字段的结构化数据，为了更快的审核。
但是现在的demo的效果不尽人意，问相关字段的值很容易出现语言幻觉和回答的不对，回答的数字什么的都是错误的，请问可以通过微调的方式让他更对一些吗，或者是增加它的OCR能力？ 期待你的回复。
![AMMER](https://github.com/THUDM/CogVLM/assets/61458769/3f32fb3f-7755-4294-8e75-880e5627aaaf)

**Comment by mactavish91** [comment]
> 你好，作者，很感谢你的工作，我拿来测试了一下相关的PI CI图片，我的目标是让模型得到有关字段的结构化数据，为了更快的审核。 但是现在的demo的效果不尽人意，问相关字段的值很容易出现语言幻觉和回答的不对，回答的数字什么的都是错误的，请问可以通过微调的方式让他更对一些吗，或者是增加它的OCR能力？ 期待你的回复。 ![AMMER](https://user-images.githubusercontent.com/61458769/277633077-3f32fb3f-7755-4294-8e75-880e5627aaaf.png)

Due to insufficient documentation and OCR data in the training set, the model's performance is not up to par. We are gathering more data to train an improved version and expect to complete it within a month.

**Comment by zhangquanwei962** [comment]
> > 你好，作者，很感谢你的工作，我拿来测试了一下相关的PI CI图片，我的目标是让模型得到有关字段的结构化数据，为了更快的审核。 但是现在的demo的效果不尽人意，问相关字段的值很容易出现语言幻觉和回答的不对，回答的数字什么的都是错误的，请问可以通过微调的方式让他更对一些吗，或者是增加它的OCR能力？ 期待你的回复。 ![AMMER](https://user-images.githubusercontent.com/61458769/277633077-3f32fb3f-7755-4294-8e75-880e5627aaaf.png)
> 
> Due to insufficient documentation and OCR data in the training set, the model's performance is not up to par. We are gathering more data to train an improved version and expect to complete it within a month.

Thank you for your timely reply! So it can be improved by the documentation and OCR data tunning, but It will achieve the goal of commercial PI CI review which need the key information be extract correctly for most scenarios ? In addition, I'm looking forword to a better version.

**Comment by zhangquanwei962** [comment]
@mactavish91 When I use the "convert it to a markdown format.", I get the result like this:
Proforma Invoice for Ammer Electronics Co., Ltd.
Address: Rm 1818 F1 Huchuang Building No. 30 Hennessy Rd., Wanchai Hong Kong
Tel: 852 43185207
Fax: 852 25320720
Email: [ammer@hknet.com](mailto:ammer@hknet.com)

To: M.S. Hi-Tech Inc., New York, NY 11718, USA

Billing Date: October 20, 2022
Invoice Number: AAJM20220020

Customer Information:
Name: M.S. Hi-Tech Inc.
Address: 371 Pierce St., New York, NY 11718, USA
Phone: 212-919-4201
Fax: 212-919-4202
Email: [jamesyamano@mshtech.com.jp](mailto:jamesyamano@mshtech.com.jp)

Detailed Invoice:
Product Name: Cypress 21T SOP54
Quantity: 10
Unit Price: $2.0
Total Amount: $200.00
Bank Charge: $4.95
Total Amount: $19,525.50

Payment Terms: Net 15 Days
Account Number: 1818078 AG Hong Kong
Bank Name: Deutsche Bank AG, Hong Kong
Bank Address: 18 Chater Road, Central, Hong Kong.  

Note the result is different from yours.
