### ISSUE TITLE
Cogagent demo can not be accessed

### ISSUE THREAD

**Issue by Honey-Mydear** [THUDM/CogVLM#485]
### System Info / 系統信息

Cogagent demo can not be accessed, while opening it, error page occur. 
![微信截图_20240528104458](https://github.com/THUDM/CogVLM/assets/69945923/acd5d246-85cc-4055-8c19-09745d0f30fd)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

not sure what to say here

### Expected behavior / 期待表现

Pls fix this problem and contact me if it can work, tks!

**Comment by zRzRzRzRzRzRzR** [comment]
现在已经换成了cogvlm2的demo，
这个demo已经下架了
