### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by mwaikul** [THUDM/CogVLM#488]
### System Info / 系統信息

aws g4dn.2xlarge 
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

Hello,
I am using a g4dn.2xlarge instance that I believe has a nvidia t4 tensor core which has 16 GB GDDR6 memory.
All the requirements, gradio and python -m spacy download en_core_web_sm have been installed.
After running
python cli_demo_hf.py --from_pretrained THUDM/cogvlm-chat-hf --bf16
I get the error: 
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 106.00 MiB. GPU
Can you please advice how to fix this.
Thanks
-Milind

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Try running python cli_demo_hf.py --from_pretrained THUDM/cogvlm-chat-hf --bf16 on a AWS g4dn.2xlarge

### Expected behavior / 期待表现

Expect the server to start.

**Comment by zRzRzRzRzRzRzR** [comment]
需要知道你显卡的具体型号
