### ISSUE TITLE
Hi，请问后续会给出CogAgent在mind2web数据集上评估的代码吗？

### ISSUE THREAD

**Issue by micro-cosmos** [THUDM/CogVLM#489]
### Feature request  / 功能建议

模型具体是怎么在mind2web数据集上评估的呢？step success是指模型预测的operation和target element与ground-truth相同，但看起来模型的输出不一定总是包含target element，有时候模型输出target element的ocr文字，有时候输出坐标，请问如何判断target element和ground-相同呢？是构建了mind2web的sft数据集进行了sft以规范模型输出吗？如果是的话，能否提供微调后的checkpoint及评估代码呢？

### Motivation / 动机

。

### Your contribution / 您的贡献

no

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有相关计划哦，如果有相关的工作准备公开，我们会第一时间更新
