### ISSUE TITLE
can anyone tell me how to run web_demo.py with multi-gpus? 

### ISSUE THREAD

**Issue by wonder-hy** [THUDM/CogVLM#49]
I have tried to just replace cli_demo.py in command, for multi-gpu inference but it didn't work

**Comment by 1049451037** [comment]
I don't know why it's not working. You can just replace `python` with `torchrun --standalone --nnodes=1 --nproc-per-node=2`

**Comment by wonder-hy** [comment]
> I don't know why it's not working. You can just replace `python` with `torchrun --standalone --nnodes=1 --nproc-per-node=2`. You can also replace 2 with 4 or 8. It should work.

yes, i have tried like you said. the server looks fine but never output any answer after input pic and query. I try to debug just find the program is trapped in (utils/chat.py line:111 output=filling_sequence())

**Comment by 1049451037** [comment]
Maybe you install a wrong sat version? try `pip install -U SwissArmyTransformer`.

**Comment by makangzhe** [comment]
have you solve this!

**Comment by CarolXh** [comment]
I meet the same problem， have you sovled it?

**Comment by wonder-hy** [comment]
finally, I give up on web_demo and start a my own service with fastapi and DDP. It is not very decent though, you need to first fetch your service only on rank:0 device , then write dist.broadcast_object_list() in a 'while True on other rank# to keep listen and sync data. Thus, you can guarantee every vice device can sync input data when inference
