### ISSUE TITLE
请问你们的代码使用了流行的agent框架吗，比如Langchain,如果没有使用，请问一下为什么不使用Langchain呢？目前做agent开发需要使用什么框架呢

### ISSUE THREAD

**Issue by TheUnbearableLightnessofBeing** [THUDM/CogVLM#491]
请问你们的代码使用了流行的agent框架吗，比如Langchain,如果没有使用，请问一下为什么不使用Langchain呢？目前做agent开发需要使用什么框架呢

**Comment by zRzRzRzRzRzRzR** [comment]
这是一个模型，不是一个框架
你可以使用框架来在模型的基础上做工程开发，比如你提到的langchain
