### ISSUE TITLE
raise IndexError('piece id is out of range.') IndexError: piece id is out of range.

### ISSUE THREAD

**Issue by stay-leave** [THUDM/CogVLM#493]
### System Info / 系統信息

Driver Version: 535.86.10    CUDA Version: 12.2 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python openai_demo/openai_api.py
python openai_demo/openai_api_request.py
第二步报错：
File "/home/python_venv/cogvlm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 1172, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.

### Expected behavior / 期待表现

应该是能正常输出This image showcases a tranquil natural scene with a wooden pathway leading through a field of lush green grass. In the distance, there are trees and some scattered structures, possibly houses or small buildings. The sky is clear with a few scattered clouds, suggesting a bright and sunny day.

**Comment by zRzRzRzRzRzRzR** [comment]
请给一个完整的报错
sentencepiece看上去是没有正常的编码

**Comment by stay-leave** [comment]
解决了，原来是git错源码了。我部署的模型是cogvlm2
