### ISSUE TITLE
What is the meaning of different 'image_xxx_mask' ?

### ISSUE THREAD

**Issue by microhu** [THUDM/CogVLM#50]
After check the text processor, I found there are thee image related masks, i.e., image_embed_mask, image_vision_mask, image_rope_mask, and they are slightly different. I wonder what is the function of each ?

**Comment by microhu** [comment]
> After check the text processor, I found there are thee image related masks, i.e., image_embed_mask, image_vision_mask, image_rope_mask, and they are slightly different. I wonder what is the function of each ?

@Qingsong Lv

**Comment by 1049451037** [comment]
A. `image_embed_mask`: 1 means "here is an image token", while 0 means "here is a language token".
B. `image_vision_mask`: 1 means "this token should use vision expert", while 0 means "this token should use language expert".
C. `image_rope_mask`: 1 means "the position_id of this token should be same as the token before it", while 0 mean "the position_id of the token should be the id before it +1".

A and B are different because there are two tokens before and after image, i.e, boi (begin of image) and eoi (end of image).

C exists because we use the same image position id for all image tokens in language model, since image has position information in vit output.

**Comment by microhu** [comment]
> A. `image_embed_mask`: 1 means "here is an image token", while 0 means "here is a language token". B. `image_vision_mask`: 1 means "this token should use vision expert", while 0 means "this token should use language expert". C. `image_rope_mask`: 1 means "the position_id of this token should be same as the token before it", while 0 mean "the position_id of the token should be the id before it +1".
> 
> A and B are different because there are two tokens before and after image, i.e, boi (begin of image) and eoi (end of image).
> 
> C exists because we use the same image position id for all image tokens in language model, since image has position information in vit output.

thanks for you quick reply. Still a little confused. 

accordiing to code below,both <boi> and <eoi> are '1' in the image_embed_mask, <boi> is set as '1' but <eoi> is set as '0' in image_vision_mask. why?
------------------------------------
            image_embed_mask[idx-self.image_length-1: idx+1] = [1] * (self.image_length + 2)
            vision_expert_mask[idx-self.image_length-1: idx] = [1] * (self.image_length + 1)
            image_rope_mask[idx - self.image_length: idx] = [1] * self.image_length

**Comment by 1049451037** [comment]
A and B are different because there are two tokens before and after image, i.e, boi (begin of image) and eoi (end of image).

**Comment by microhu** [comment]
so, the <eoi> token will be calculated with the forzon text part QKV matrixs, not the vision part, functioned  as the <bos> for the following text senteence ?

**Comment by 1049451037** [comment]
emm... I didn't get what you said... sorry. Could you express in English?

**Comment by microhu** [comment]
since the mask label of <eoi> is 0 in imag_vision_mask, so the <eoi> token will  be calculated with the orignal forzon parameters, not the newly added vision related parameters. I just want to kow why we need to have differennt treatment of <boi> and <eoi>? it seems we can remove the <eoi> token ?

**Comment by 1049451037** [comment]
Because we see boi as image token and eoi as language token.

**Comment by microhu** [comment]
got, thanks.
