### ISSUE TITLE
Grounding 同一张图多次推理结果不一致

### ISSUE THREAD

**Issue by Pro-xiaowen** [THUDM/CogVLM#51]
使用官方提供的测试demo http://36.103.203.44:7861/ 以及 web_demo.py中的推理代码测试同一张图的Grounding 发现结果不一致
请问这是什么问题
![image](https://github.com/THUDM/CogVLM/assets/25923129/bee09fb4-fdd2-4793-896e-3166ef65101a)

**Comment by pf67** [comment]
这挺正常的，这又不是目标检测模型，你每次输入都是会在prompt上加上history的，本身就已经产生了变量

**Comment by Pro-xiaowen** [comment]
已收到祝好许晓文

**Comment by Pro-xiaowen** [comment]
> 这挺正常的，这又不是目标检测模型，你每次输入都是会在prompt上加上history的，本身就已经产生了变量

感谢回复！ 测试demo这样我能理解； 我在web_demo.py中已经把result_text设置为空  
![image](https://github.com/THUDM/CogVLM/assets/25923129/2e515eb3-e47a-4442-aaf0-4b727ddc5181)
<img width="945" alt="image" src="https://github.com/THUDM/CogVLM/assets/25923129/dba185fc-bc98-4876-a40f-de251d81856a">
并且把 utils/chat.py  中的135行  history = history + [(query, response)]注释掉了，  还是结果不一致。本质上我想测一下您的cogvlm的开集检测的效果，希望您能指点一二 ，感谢

**Comment by Pro-xiaowen** [comment]
> 这挺正常的，这又不是目标检测模型，你每次输入都是会在prompt上加上history的，本身就已经产生了变量

感谢回复！ 测试demo这样我能理解； 我在web_demo.py中已经把result_text设置为空  
![image](https://github.com/THUDM/CogVLM/assets/25923129/2e515eb3-e47a-4442-aaf0-4b727ddc5181)
<img width="945" alt="image" src="https://github.com/THUDM/CogVLM/assets/25923129/dba185fc-bc98-4876-a40f-de251d81856a">
并且把 utils/chat.py  中的135行  history = history + [(query, response)]注释掉了，  还是结果不一致。本质上我想测一下您的cogvlm的开集检测的效果，希望您能指点一二 ，感谢

**Comment by 1049451037** [comment]
用top_k=1就没有随机性了。

**Comment by Pro-xiaowen** [comment]
> 用top_k=1就没有随机性了。

感谢回复，我top_k=1试了一下 同一张跑了3次 还是不能做到推理结果一致 其中2次结果一致，另外一次的结果和前2次的不一致，请问还有哪些参数需要设置

**Comment by 1049451037** [comment]
这种微小的不一致我们也控制不了，属于cuda底层的随机性。

**Comment by Pro-xiaowen** [comment]
> 这种微小的不一致我们也控制不了，属于cuda底层的随机性。
请问 top_k=1理论上就是唯一能控制随机性的操作了  是吧

**Comment by Pro-xiaowen** [comment]
> 这种微小的不一致我们也控制不了，属于cuda底层的随机性。

请问 top_k=1理论上就是唯一能控制随机性的操作了 是吧

**Comment by 1049451037** [comment]
top_k=1至少从pytorch层面已经没有随机性了。
