### ISSUE TITLE
using PIL images instead of path

### ISSUE THREAD

**Issue by rahimentezari** [THUDM/CogVLM#52]
I tried to use PIL images instead of path like below but getting this error

> TypeError: CogVLMModel.forward() missing 2 required positional arguments: 'vision_expert_mask' and 'image_embed_mask'

    with torch.no_grad():
        response, history, cache_image = chat(
            None, 
            model, 
            text_processor_infer,
            image_processor,
            "Describe the image.", 
            history=[],
            max_length=2048, 
            top_p=0.9, 
            temperature=0.7,
            top_k=40,
            invalid_slices=text_processor_infer.invalid_slices,
            no_prompt=False,
            force_pil_image=image 
        )

**Comment by 1049451037** [comment]
Thank you for your report. The bug is fixed now.
