### ISSUE TITLE
关于模型版本的问题

### ISSUE THREAD

**Issue by pf67** [THUDM/CogVLM#54]
在cli_demo中有如下代码
                        print("模型："+response)
                        if tokenizer.signal_type == "grounding":
                            print("Grounding 结果已保存至 ./output.png")
看样例似乎是指示了当模型版本为grounding时，保存一个画了检测目标bbox的图像

但是当前提供的模型，除了chat外，包括grounding模型，基础的版本都是base，代码中也只支持chat和base的输入

这是代码bug还是说目前还为发布能支持此功能的模型？

**Comment by Sleepychord** [comment]
应该没有bug，支持这种功能，可以通过web demo体验，或者在命令行输入[[000,000,300,300]]这种坐标表示框。

**Comment by pf67** [comment]
> 应该没有bug，支持这种功能，可以通过web demo体验，或者在命令行输入[[000,000,300,300]]这种坐标表示框。
你真的确定么，首先在llama2_tokenizer函数里使用了assert signal_type in ["base", "chat"]，所以肯定是不支持signal_type == "grounding"的输入，这个语句是无效的。至少在cli_demo中是无效的。

**Comment by 1049451037** [comment]
因为grounding的signal_type就是"base"，并不是"grounding"。
