### ISSUE TITLE
请问为什么对Visual feature用的也是causal mask而不是类似prefix的mask？

### ISSUE THREAD

**Issue by 4IK1d** [THUDM/CogVLM#57]
![image](https://github.com/THUDM/CogVLM/assets/96651850/dec603d2-eda4-4754-b498-a935aeace225)

paper里提到对图像的内容也用了causal attention mask，个人理解，用prefix不是更能在做auto-regression的时候看到全局的视觉信息么？

**Comment by mactavish91** [comment]
可以参考论文ablation study部分，两者没有明显差别，prefix的实验结果略低于causal mask。

**Comment by Sleepychord** [comment]
Yes, please see the ablation study. We found causal mask is better, probably because the original LM weights are trained for causal mask.

**Comment by 4IK1d** [comment]
Tanks for all your explanations
