### ISSUE TITLE
fine-tuning失败

### ISSUE THREAD

**Issue by jukylin** [THUDM/CogVLM#60]
![image](https://github.com/THUDM/CogVLM/assets/8568271/4fb9f116-3b5d-4a4d-872c-40fcfa2ff1f4)
使用finetune_490_lora.sh 脚本进行微调，结果报：AssertionError: node group is not initialized, please pass LOCAL_WORLD_SIZE environment variable. 请问这是什么原因？
cuda：12.2
RTX 4090 * 2

**Comment by banzhuan37** [comment]
how do you solved this problem

**Comment by 1049451037** [comment]
更新sat

```
pip install --upgrade SwissArmyTransformer
```
