### ISSUE TITLE
How to run web_demo.py in muti-gpu? 

### ISSUE THREAD

**Issue by makangzhe** [THUDM/CogVLM#61]
我有两张GPU, GTX3090*2 ,通过torchrun 可以正常运行推理脚本cli_demo.py, 但是在运行以下命令， web 界面可以正常显示，没有办法正常推理
GRADIO_SERVER_PORT=8768  torchrun --nnodes=1 --nproc-per-node=2   web_demo.py --from_pretrained ~/CogVLM/cogvlm-chat --version chat --english --bf16 --local_tokenizer ~/vicuna-7b-v1.5 

没有报错信息，但是后台会重启一次端口，信息如下：

/kangzhe.ma/CogVLM/web_demo.py:163: GradioDeprecationWarning: 'scale' value should be an integer. Using 4.5 will cause issues.
  with gr.Column(scale=4.5):
/kangzhe.ma/CogVLM/web_demo.py:177: GradioDeprecationWarning: 'scale' value should be an integer. Using 5.5 will cause issues.
  with gr.Column(scale=5.5):
/kangzhe.ma/CogVLM/web_demo.py:178: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  result_text = gr.components.Chatbot(label='Multi-round conversation History', value=[("", "Hi, What do you want to know about this image?")]).style(height=550)
3.50.2
3.50.2
Running on local URL:  http://127.0.0.1:8768

To create a public link, set `share=True` in `launch()`.
/kangzhe.ma/CogVLM/web_demo.py:163: GradioDeprecationWarning: 'scale' value should be an integer. Using 4.5 will cause issues.
  with gr.Column(scale=4.5):
/kangzhe.ma/CogVLM/web_demo.py:177: GradioDeprecationWarning: 'scale' value should be an integer. Using 5.5 will cause issues.
  with gr.Column(scale=5.5):
/kangzhe.ma/CogVLM/web_demo.py:178: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  result_text = gr.components.Chatbot(label='Multi-round conversation History', value=[("", "Hi, What do you want to know about this image?")]).style(height=550)
3.50.2
3.50.2
Running on local URL:  http://127.0.0.1:8769

To create a public link, set `share=True` in `launch()`.

麻烦帮忙看一下！

**Comment by 1049451037** [comment]
cc @lykeven

**Comment by duiyady** [comment]
你解决这个问题了吗，我遇到了同样的问题

**Comment by duiyady** [comment]
把模型部署和网页分开，将模型几个进程封装为接口，web_demo.py中用多线程同时打模型部署的那几个进程就能实现网页版的分布式部署了，我这样做成功了，虽然有点蠢，但是实现比较容易

**Comment by summerbuild** [comment]
同样的问题，web页面输入内容就没反应了

**Comment by zRzRzRzRzRzRzR** [comment]
web UI没有设计多卡，目前都是单卡执行
