### ISSUE TITLE
is all the models of cogvlm are commercial license ?

### ISSUE THREAD

**Issue by papasanimohansrinivas** [THUDM/CogVLM#64]
hi @Sleepychord  you have mentioned in other issue that cogvlm-17b is commercially available , I am wondering what model weights exactly mentioned in the repo are commercial available (license )

cogvlm-chat ?
cogvlm-base-224 ?
cogvlm-base-490 ?
cogvlm-grounding-generalist ? 

which of the above models (model weights ) are commercial
 license applicable 
 because I have seen in the paper that cogvlm-chat has been trained on llava-insruct dataset and I am not sure that dataset allows commercial that's why 
 
 let me know

**Comment by zRzRzRzRzRzRzR** [comment]
Models weight in this repository for academic research is **free**.
Users who wish to use the models for **commercial purposes** must register **[here](https://open.bigmodel.cn/mla/form)**.
Registered users may use the models for commercial activities free of charge, but must comply with all terms and conditions of this license.
The license notice shall be included in all copies or substantial portions of the Software.

you can see in MODEL_LICENSE now

**Comment by abed-roid** [comment]
> Models weight in this repository for academic research is **free**. Users who wish to use the models for **commercial purposes** must register **[here](https://open.bigmodel.cn/mla/form)**. Registered users may use the models for commercial activities free of charge, but must comply with all terms and conditions of this license. The license notice shall be included in all copies or substantial portions of the Software.
> 
> you can see in MODEL_LICENSE now

We're trying to submit the form, but the SMS verification code is not being received anyhow...

**Comment by parthakmehta** [comment]
> > Models weight in this repository for academic research is **free**. Users who wish to use the models for **commercial purposes** must register **[here](https://open.bigmodel.cn/mla/form)**. Registered users may use the models for commercial activities free of charge, but must comply with all terms and conditions of this license. The license notice shall be included in all copies or substantial portions of the Software.
> > you can see in MODEL_LICENSE now
> 
> We're trying to submit the form, but the SMS verification code is not being received anyhow...

Were you able to submit the form? We are facing the same issue
