### ISSUE TITLE
How to reproduce Textvqa(val) score- 68.1

### ISSUE THREAD

**Issue by Cuiunbo** [THUDM/CogVLM#66]
Hi, I am currently facing some challenges in achieving the reported outcomes of TextVQA.
Here are the details of my current setup:

Model Checkpoint: cogvlm-chat
Prompt Template: 'Question: {} Answer:'
And I use the model.chat to generate answers

Despite following the specified settings, I am unable to replicate the results for TextVQA as mentioned in the paper. Could you please provide some guidance on what might be missing or any additional steps that need to be taken to successfully reproduce the results?
Thank you very much for your time and assistance.

**Comment by mactavish91** [comment]
The chat model is trained on a substantial amount of instructional data. Models trained on multi VQA and caption data will be released soon.

**Comment by Sleepychord** [comment]
are you testing zero-shot performance? The reported result is a fine-tuned one.

**Comment by Cuiunbo** [comment]
Yes, I initially thought that cogvlm-490-base was the one, but it turns out it did not achieve the performance expected.

**Comment by Cuiunbo** [comment]
> are you testing zero-shot performance? The reported result is a fine-tuned one.
Oh！ I thought cogvlm-490-base was the fine-tuned version mentioned in the paper. So you haven't released this model yet?

**Comment by mactavish91** [comment]
> > are you testing zero-shot performance? The reported result is a fine-tuned one.
> 
> Oh！ I thought cogvlm-490-base was the fine-tuned version mentioned in the paper. So you haven't released this model yet?

we have updated the vqa model.

**Comment by ShoufaChen** [comment]
Hi @mactavish91 ,

Congratulations on your awesome work.

I am also wondering the zero-shot performance of Table 2 & 3. Do you have a plan to provide it? 
Please let me know if I missed something.

Thanks very much.

**Comment by mactavish91** [comment]
> Hi @mactavish91 ,
> 
> Congratulations on your awesome work.
> 
> I am also wondering the zero-shot performance of Table 2 & 3. Do you have a plan to provide it? Please let me know if I missed something.
> 
> Thanks very much.

We may not provide the results of these datasets, as we have found that the evaluation of them uses strict matching, and the model's language style greatly influences the results. However, we do provide the zero-shot results of three datasets: MMVET, POPE, and Touchstone, which you may refer to.
