### ISSUE TITLE
how to set 'MP_SIZE' ?

### ISSUE THREAD

**Issue by microhu** [THUDM/CogVLM#68]
Does the MP_SIZE mean the value of model parallel on each gpu device? How to set it if we use Zero-stage 3

**Comment by 1049451037** [comment]
I think model parallel is unrelated to deepspeed zero-stage. Model parallel is just normal nn.Module class. You can set it to any value.

**Comment by elesun2018** [comment]
不好意思，我还是没有明白这个MP_SIZE的用途

**Comment by 1049451037** [comment]
> 不好意思，我还是没有明白这个MP_SIZE的用途

模型并行的时候会用到
