### ISSUE TITLE
Missing dependency "jmespath" when downloading models

### ISSUE THREAD

**Issue by aisensiy** [THUDM/CogVLM#7]
This only happens when downloading the models, it seems not the problem of this project but a missing dependency of sat?

![](https://github.com/THUDM/CogVLM/assets/661860/b1e20694-bbd9-4b49-b63b-3a5e570ed0f4)

**Comment by 1049451037** [comment]
jmespath should be installed automatically if you have run `pip install -r requirements.txt`
