### ISSUE TITLE
运行官方demo报错。提示AttributeError: module 'flash_attn' has no attribute '__version__'

### ISSUE THREAD

**Issue by shikimoon** [THUDM/CogVLM#70]
torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16
运行官方demo报错。
环境都配置好了。显卡为2*v100。看起来应该是v100不支持flash attention导致的

**Comment by zRzRzRzRzRzRzR** [comment]
flash atten是针对A100的
