### ISSUE TITLE
Similarity between Image and Text

### ISSUE THREAD

**Issue by mxllc** [THUDM/CogVLM#74]
Hi, I would like to know, how can the similarity between an image and a caption be obtained? 
Or more broadly, how can the similarity between an image and text be obtained?

**Comment by 1049451037** [comment]
I think you can do something like this:

<img width="1281" alt="image" src="https://github.com/THUDM/CogVLM/assets/15194939/5a43c1f9-53d5-4e3d-9d3d-6011c65e6545">

**Comment by mactavish91** [comment]
> Hi, I would like to know, how can the similarity between an image and a caption be obtained? Or more broadly, how can the similarity between an image and text be obtained?

You'd better use a clip encoder to calculate it.
