### ISSUE TITLE
Fast captioning

### ISSUE THREAD

**Issue by rahimentezari** [THUDM/CogVLM#75]
I would like to use CogVLM for captioning images in large scale. Currently using Chat() function takes about 2.5 sec for captioning one image on an A100 GPU which makes it almost impossible to use for million-scale. What do you recommend to speed up? I see that quantization is not yet supported for example https://github.com/THUDM/CogVLM/issues/9.

**Comment by eezywu** [comment]
same problem

**Comment by 1049451037** [comment]
Quantization can be beneficial. However, that portion of the code was not written by me. As far as I know, there are no plans to open-source the code.

**Comment by 1049451037** [comment]
We now support 4-bit quantization now! See README for more details.

**Comment by ProGamerGov** [comment]
@rahimentezari Have you tested captioning speed on the A100 GPU for 4-bit quantization yet?

**Comment by chakrabortyrajatsubhra** [comment]
Hey can anyone say how to caption a folder of images with the sat demo model? I will have a fixed query like describe the image. Any suggestions would be greatly helpful.
