### ISSUE TITLE
High Resolution

### ISSUE THREAD

**Issue by excellent-ai** [THUDM/CogVLM#79]
Hello,

How does CogVLM work with high resolution?

High resolution is very useful. For example, a standard PC screenshot is usually an image in 1080p resolution. It allows the model to reason about small details/text from the top-left corner to the right-bottom corner of the image.

In [GPT4V](https://platform.openai.com/docs/guides/vision), high resolution will be split into smaller square tiles.

> A 1024 x 1024 square image in detail: high mode costs 765 tokens
1024 is less than 2048, so there is no initial resize.
The shortest side is 1024, so we scale the image down to 768 x 768.
4 512px square tiles are needed to represent the image, so the final token cost is 170 * 4 + 85 = 765.

> A 2048 x 4096 image in detail: high mode costs 1105 tokens
We scale down the image to 1024 x 2048 to fit within the 2048 square.
The shortest side is 1024, so we further scale down to 768 x 1536.
6 512px tiles are needed, so the final token cost is 170 * 6 + 85 = 1105.

> A 4096 x 8192 image in detail: low most costs 85 tokens
Regardless of input size, low detail images are a fixed cost.

Could we support high resolution with a similar **multi-tile** approach? (re-train the model if needed)

**Comment by 1049451037** [comment]
The input resolution is fixed to 224x224 or 490x490 for our model. And the model hasn't been trained with multi-image cases. Maybe you should fine-tuning if you need this multi-tile feature.

**Comment by zRzRzRzRzRzRzR** [comment]
The CogAgent release is support 1120 x 1120 resolution now

**Comment by YangJae96** [comment]
@zRzRzRzRzRzRzR, Hi.

If i want to input 1920x1080  size images, 
do I need to finetunue the model?
