### ISSUE TITLE
Eva CLIP model: trained or freezed?

### ISSUE THREAD

**Issue by shkarupa-alex** [THUDM/CogVLM#81]
Did you trained eva clip model weights or freezed them and trained just mlp adapter?

**Comment by mactavish91** [comment]
It was frozen during the pre training phase, but we trained its parameters during the instruction tuning phase.

**Comment by mactavish91** [comment]
It was frozen during the pre training phase, but we trained its parameters during the instruction tuning phase.

**Comment by xmy0916** [comment]
@mactavish91 hello，看你们的论文这部分
![image](https://github.com/THUDM/CogVLM/assets/43675899/9a69f507-897a-416e-992e-5cbdc55fe88d)
想请教下，这四个阶段的训练，那个阶段训练了vit的参数呢？

**Comment by paulpaul91** [comment]
> It was frozen during the pre training phase, but we trained its parameters during the instruction tuning phase.

为什么在pretrain阶段freeze图像参数，有没有做过freeze和unfreeze的消融实验
