### ISSUE TITLE
Any plan to train CogVLM based on a larger text model? 

### ISSUE THREAD

**Issue by rfan-debug** [THUDM/CogVLM#86]
Thanks for releasing such a great visual LM model. 

According to your [paper](https://arxiv.org/pdf/2311.03079.pdf), CogVLM leverages the `Vicuna-1.5-7B`. It seems to be a bit weak in the performance when handling complexed questions of understanding an image. Is there any plan to train such a model on a larger text encoder, e.g. Vicuna-13b or Vicuna-33b?

With more parameters, i would assume the model is able to answer more complexed questions.

**Comment by KooSung** [comment]
Any plan to try [Mistral 7B](https://github.com/mistralai/mistral-src) as the LLM?

**Comment by mactavish91** [comment]
> Thanks for releasing such a great visual LM model.
> 
> According to your [paper](https://arxiv.org/pdf/2311.03079.pdf), CogVLM leverages the `Vicuna-1.5-7B`. It seems to be a bit weak in the performance when handling complexed questions of understanding an image. Is there any plan to train such a model on a larger text encoder, e.g. Vicuna-13b or Vicuna-33b?
> 
> With more parameters, i would assume the model is able to answer more complexed questions.

Thank you for your advice. We are working on training our model based on a larger language model such as LLama2-70b and ChatGLM2-66b.

**Comment by xmy0916** [comment]
> > Thanks for releasing such a great visual LM model.
> > According to your [paper](https://arxiv.org/pdf/2311.03079.pdf), CogVLM leverages the `Vicuna-1.5-7B`. It seems to be a bit weak in the performance when handling complexed questions of understanding an image. Is there any plan to train such a model on a larger text encoder, e.g. Vicuna-13b or Vicuna-33b?
> > With more parameters, i would assume the model is able to answer more complexed questions.
> 
> Thank you for your advice. We are working on training our model based on a larger language model such as LLama2-70b and ChatGLM2-66b.

Any plan to try [Mistral 7B](https://github.com/mistralai/mistral-src) or Yi as the LLM? @mactavish91
