### ISSUE TITLE
有没有方案提升infer的速度

### ISSUE THREAD

**Issue by pf67** [THUDM/CogVLM#87]
目前我用CogVLM通过finetune 做图像的grounding任务，取得了非常好的效果

但是infer略显迟缓，在4090*4的服务器上，大概2-3s才能完成一次输出，是否有方案能提升infer速度呢？

**Comment by 1049451037** [comment]
可以通过模型量化来加速，但是这部分不是我负责的，据我所知量化的代码没有开源计划。

**Comment by 1049451037** [comment]
infer加速这一块我也不太了解，这部分不是我负责的，据我所知这部分代码暂时没有开源计划。

**Comment by Pro-xiaowen** [comment]
请问 CogVLM通过finetune 做图像的grounding任务 ，是不是只需要在finetune_cogvlm_lora.sh中将MODEL_TYPE设置成 “cogvlm-grounding-generalist”就可以了，即：
MODEL_TYPE="cogvlm-base-490" 
@pf67

**Comment by pf67** [comment]
> ogvlm-grounding-generalist


> 请问 CogVLM通过finetune 做图像的grounding任务 ，是不是只需要在finetune_cogvlm_lora.sh中将MODEL_TYPE设置成 “cogvlm-grounding-generalist”就可以了，即： MODEL_TYPE="cogvlm-base-490" @pf67

cogvlm-grounding-generalist是他们二次微调过的专门做grounding的模型，在上面对其他数据集做grounding微调会相对容易，但是你选择其他基底模型应该也是可以的
