### ISSUE TITLE
Specific task

### ISSUE THREAD

**Issue by Haonote** [THUDM/CogVLM#88]
I would like to ask if I can fine-tune the model to adapt it to a specific task, so that it can answer the questions of the task as much as possible without losing the original knowledge.

**Comment by 1049451037** [comment]
Good question... But I don't know the answer exactly. Maybe you can try lora fine-tuning with curated parameter selection.

If I have such a great technique to learn new knowledge without losing original knowledge, I can create a model far better than GPT-4 then...

**Comment by Haonote** [comment]
@1049451037 Thanks for your prompt reply. I may not know much about big language models. I want to try to apply them to my current field. It seems that I need to know more.
