### ISSUE TITLE
How to do Model Quantization？

### ISSUE THREAD

**Issue by miandai** [THUDM/CogVLM#9]
1. update web_demo.py：CogVLMModel.from_pretrained(...,device=f'cpu',...)
2. python web_demo.py --version chat --english --quant 4

Is this OK？

**Comment by 1049451037** [comment]
It should work. If something went wrong, feel free to post here.

**Comment by 1049451037** [comment]
Yeah I got it. This is the bug of cpm_kernel, which we cannot control actually... You can avoid this by changing `--bf16` to `--fp16` when running code.

**Comment by 1049451037** [comment]
emm... Could you post more detailed error info?

**Comment by 1049451037** [comment]
I tested... It's also because of cpm_kernels. They do not support some operations in our model... Therefore, quantization with cpm_kernels is not supported for now.

**Comment by 1049451037** [comment]
It works for two 3090 with model parallel.

**Comment by miandai** [comment]
@aisensiy Try add a line of code to web_demo.py：

![image](https://github.com/THUDM/CogVLM/assets/4371622/256f0ba2-7a1d-4abb-8a15-698cbab766be)


![image](https://github.com/THUDM/CogVLM/assets/4371622/7ac478e8-8cee-402e-aefb-0931e3fdcd00)

**Comment by 1049451037** [comment]
Yes, I think you can remove the quantization related in this repo. If quantization is necessary for you, maybe you can try [bitsandbytes](https://github.com/TimDettmers/bitsandbytes) to quantize our model.

**Comment by 1049451037** [comment]
Yes, but it depends on the cuda kernel support. cpm_kernels misses some implementation for bf16 and slicing fp16. I'm not sure whether bitsandbytes works.

Theoretically, quantization everything is possible. But practically, some packages may have bug.

**Comment by Blankit** [comment]
> It works for two 3090 with model parallel.

How to set?

**Comment by Blankit** [comment]
> ```
> torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16
> ```
> 
> or
> 
> ```
> torchrun --standalone --nnodes=1 --nproc-per-node=2 web_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16
> ```

`torchrun: error: unrecognized arguments: --nproc-per-node=2`

**Comment by Blankit** [comment]
> > ```
> > torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16
> > ```
> > 
> > 
> > or
> > ```
> > torchrun --standalone --nnodes=1 --nproc-per-node=2 web_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16
> > ```
> 
> `torchrun: error: unrecognized arguments: --nproc-per-node=2`

 It is caused by the PyTorch version

**Comment by shuinianchangan** [comment]
> > > ```
> > > torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > or
> > > ```
> > > torchrun --standalone --nnodes=1 --nproc-per-node=2 web_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16
> > > ```
> > 
> > 
> > `torchrun: error: unrecognized arguments: --nproc-per-node=2`
> 
> It is caused by the PyTorch version
I also encountered the same problem, my torch version is 1.10.1+cu111. Can you tell me how you solved it, and the torch version number you used

**Comment by rahimentezari** [comment]
> Yes, I think you can remove the quantization related in this repo. If quantization is necessary for you, maybe you can try [bitsandbytes](https://github.com/TimDettmers/bitsandbytes) to quantize our model.

while I wait for quantization support, would like to try bitsandbytes
Is this correct as I read from bitsandbytes?
in cogvlm_model.py change the GLU class linear layers to

    class GLU(nn.Module):
        def __init__(self, args, in_features):
            super().__init__()
            # self.linear_proj = nn.Linear(in_features, args.hidden_size, bias=False)
            # self.norm1 = nn.LayerNorm(args.hidden_size)
            # self.act1 = nn.GELU()
            # self.act2 = nn.functional.silu
            # self.dense_h_to_4h = nn.Linear(args.hidden_size, args.inner_hidden_size, bias=False)
            # self.gate_proj = nn.Linear(args.hidden_size, args.inner_hidden_size, bias=False)
            # self.dense_4h_to_h = nn.Linear(args.inner_hidden_size, args.hidden_size, bias=False)

            self.linear_proj = bnb.nn.Linear8bitLt(in_features, args.hidden_size, bias=False, has_fp16_weights=False, threshold=6.0)
            self.norm1 = nn.LayerNorm(args.hidden_size)
            self.act1 = nn.GELU()
            self.act2 = nn.functional.silu
            self.dense_h_to_4h = bnb.nn.Linear8bitLt(args.hidden_size, args.inner_hidden_size, bias=False, has_fp16_weights=False, threshold=6.0)
            self.gate_proj = bnb.nn.Linear8bitLt(args.hidden_size, args.inner_hidden_size, bias=False, has_fp16_weights=False, threshold=6.0)
            self.dense_4h_to_h = bnb.nn.Linear8bitLt(args.inner_hidden_size, args.hidden_size, bias=False, has_fp16_weights=False, threshold=6.0)

        def forward(self, x):
            x = self.linear_proj(x)
            x = self.act1(self.norm1(x))
            x = self.act2(self.gate_proj(x)) * self.dense_h_to_4h(x)
            x = self.dense_4h_to_h(x)
            return x

**Comment by 1049451037** [comment]
We now support 4-bit quantization now! See README for more details.
