### ISSUE TITLE
How could I fixed this error? Thanks!

### ISSUE THREAD

**Issue by zetaodu** [THUDM/CogVLM#90]
![image](https://github.com/THUDM/CogVLM/assets/56751658/0caeee8f-5b9a-4ed6-bd87-01f74a82700a)

**Comment by 1049451037** [comment]
try upgrading transformers

```
pip install git+https://github.com/huggingface/transformers
```

**Comment by zetaodu** [comment]
> try upgrading transformers
> 
> ```
> pip install git+https://github.com/huggingface/transformers
> ```
> 
> or
> 
> ```
> pip install -U transformers
> ```
![image](https://github.com/THUDM/CogVLM/assets/56751658/b94b9744-43f9-4594-b407-25186db78d9a)

After install transformers, I still suffer from this error! @1049451037 ,Saaaaad.....
# packages in environment at /mnt/diskf/dzt/software/anaconda3/envs/CogVLM:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
abseil-cpp                20211102.0           hd4dd3e8_0    defaults
aiohttp                   3.8.5            py38h5eee18b_0    defaults
aiosignal                 1.2.0              pyhd3eb1b0_0    defaults
annotated-types           0.6.0                    pypi_0    pypi
arrow-cpp                 11.0.0               h374c478_2    defaults
async-timeout             4.0.2            py38h06a4308_0    defaults
attrs                     23.1.0           py38h06a4308_0    defaults
aws-c-common              0.6.8                h5eee18b_1    defaults
aws-c-event-stream        0.1.6                h6a678d5_6    defaults
aws-checksums             0.1.11               h5eee18b_2    defaults
aws-sdk-cpp               1.8.185              h721c034_1    defaults
beautifulsoup4            4.12.2                   pypi_0    pypi
bitsandbytes              0.41.2.post2             pypi_0    pypi
blas                      1.0                         mkl    defaults
blis                      0.7.11                   pypi_0    pypi
boost-cpp                 1.82.0               hdb19cb5_2    defaults
boto3                     1.28.83                  pypi_0    pypi
botocore                  1.31.83                  pypi_0    pypi
bottleneck                1.3.5            py38h7deecbd_0    defaults
braceexpand               0.1.7                    pypi_0    pypi
brotli-python             1.0.9            py38h6a678d5_7    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.19.1               h5eee18b_0    defaults
ca-certificates           2023.08.22           h06a4308_0    defaults
catalogue                 2.0.10                   pypi_0    pypi
certifi                   2023.7.22        py38h06a4308_0    defaults
cffi                      1.15.1           py38h5eee18b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.1.7                    pypi_0    pypi
cloudpathlib              0.16.0                   pypi_0    pypi
confection                0.1.3                    pypi_0    pypi
cpm-kernels               1.0.11                   pypi_0    pypi
cryptography              41.0.3           py38hdda0065_0    defaults
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cymem                     2.0.8                    pypi_0    pypi
datasets                  2.14.6                   pypi_0    pypi
deepspeed                 0.12.2                   pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
en-core-web-sm            3.7.0                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.9.0            py38h06a4308_0    defaults
freetype                  2.12.1               h4a9f257_0    defaults
frozenlist                1.4.0            py38h5eee18b_0    defaults
fsspec                    2023.9.2         py38h06a4308_0    defaults
gflags                    2.2.2                he6710b0_0    defaults
giflib                    5.2.1                h5eee18b_3    defaults
glog                      0.5.0                h2531618_0    defaults
gmp                       6.2.1                h295c915_3    defaults
gmpy2                     2.1.2            py38heeb90bb_0    defaults
gnutls                    3.6.15               he1e5248_0    defaults
grpc-cpp                  1.48.2               he1ff14a_1    defaults
hjson                     3.1.0                    pypi_0    pypi
huggingface_hub           0.17.3           py38h06a4308_0    defaults
icu                       73.1                 h6a678d5_0    defaults
idna                      3.4              py38h06a4308_0    defaults
importlib-metadata        6.0.0            py38h06a4308_0    defaults
install                   1.3.5                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46305    defaults
jinja2                    3.1.2            py38h06a4308_0    defaults
jmespath                  1.0.1                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1    defaults
krb5                      1.20.1               h143b758_1    defaults
lame                      3.100                h7b6447c_0    defaults
langcodes                 3.3.0                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
lerc                      3.0                  h295c915_0    defaults
libboost                  1.82.0               h109eef0_2    defaults
libbrotlicommon           1.0.9                h5eee18b_7    defaults
libbrotlidec              1.0.9                h5eee18b_7    defaults
libbrotlienc              1.0.9                h5eee18b_7    defaults
libcublas                 11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufile                 1.8.0.34                      0    nvidia
libcurand                 10.3.4.52                     0    nvidia
libcurl                   8.4.0                h251f7ec_0    defaults
libcusolver               11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libdeflate                1.17                 h5eee18b_1    defaults
libedit                   3.1.20221030         h5eee18b_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libevent                  2.1.12               hdbd6064_1    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libiconv                  1.16                 h7f8727e_2    defaults
libidn2                   2.3.4                h5eee18b_0    defaults
libnghttp2                1.57.0               h2d74bed_0    defaults
libnpp                    11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libpng                    1.6.39               h5eee18b_0    defaults
libprotobuf               3.20.3               he621ea3_0    anaconda
libssh2                   1.10.0               hdbd6064_2    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libtasn1                  4.19.0               h5eee18b_0    defaults
libthrift                 0.15.0               h1795dd8_2    defaults
libtiff                   4.5.1                h6a678d5_0    defaults
libunistring              0.9.10               h27cfd23_0    defaults
libwebp                   1.3.2                h11a3e52_0    defaults
libwebp-base              1.3.2                h5eee18b_0    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
markupsafe                2.1.1            py38h7f8727e_0    defaults
mkl                       2023.1.0         h213fc3f_46343    defaults
mkl-service               2.4.0            py38h5eee18b_1    defaults
mkl_fft                   1.3.8            py38h5eee18b_0    defaults
mkl_random                1.2.4            py38hdb19cb5_0    defaults
mpc                       1.1.0                h10f8cd9_1    defaults
mpfr                      4.0.2                hb69a4c5_1    defaults
mpmath                    1.3.0            py38h06a4308_0    defaults
multidict                 6.0.2            py38h5eee18b_0    defaults
multiprocess              0.70.15                  pypi_0    pypi
murmurhash                1.0.10                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    defaults
nettle                    3.7.3                hbbd107a_1    defaults
networkx                  3.1              py38h06a4308_0    defaults
ninja                     1.11.1.1                 pypi_0    pypi
numexpr                   2.8.4            py38hc78ab66_1    defaults
numpy                     1.24.3           py38hf6e8229_1    defaults
numpy-base                1.24.3           py38h060ed82_1    defaults
openh264                  2.1.1                h4ff587b_0    defaults
openjpeg                  2.4.0                h3ad879b_0    defaults
openssl                   3.0.12               h7f8727e_0    defaults
orc                       1.7.4                hb3bc3d3_1    defaults
packaging                 23.1             py38h06a4308_0    defaults
pandas                    2.0.3            py38h1128e8f_0    defaults
pillow                    10.0.1           py38ha6cbd5a_0    defaults
pip                       23.3             py38h06a4308_0    defaults
preshed                   3.0.9                    pypi_0    pypi
protobuf                  4.25.0                   pypi_0    pypi
psutil                    5.9.6                    pypi_0    pypi
pyarrow                   12.0.1                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    defaults
pydantic                  2.4.2                    pypi_0    pypi
pydantic-core             2.10.1                   pypi_0    pypi
pynvml                    11.5.0                   pypi_0    pypi
pyopenssl                 23.2.0           py38h06a4308_0    defaults
pyparsing                 3.1.1                    pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0    defaults
python                    3.8.18               h955ad1f_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-tzdata             2023.3             pyhd3eb1b0_0    defaults
python-xxhash             2.0.2            py38h5eee18b_1    defaults
pytorch                   2.0.1           py3.8_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3.post1     py38h06a4308_0    defaults
pyyaml                    6.0.1            py38h5eee18b_0    defaults
re2                       2022.04.01           h295c915_0    defaults
readline                  8.2                  h5eee18b_0    defaults
regex                     2023.10.3        py38h5eee18b_0    defaults
requests                  2.31.0           py38h06a4308_0    defaults
responses                 0.13.3             pyhd3eb1b0_0    defaults
s3transfer                0.7.0                    pypi_0    pypi
safetensors               0.4.0            py38ha89cbab_0    defaults
seaborn                   0.13.0                   pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
setuptools                68.0.0           py38h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
smart-open                6.4.0                    pypi_0    pypi
snappy                    1.1.9                h295c915_0    defaults
soupsieve                 2.5                      pypi_0    pypi
spacy                     3.7.2                    pypi_0    pypi
spacy-legacy              3.0.12                   pypi_0    pypi
spacy-loggers             1.0.5                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0    defaults
srsly                     2.4.8                    pypi_0    pypi
swissarmytransformer      0.4.8                    pypi_0    pypi
sympy                     1.11.1           py38h06a4308_0    defaults
tbb                       2021.8.0             hdb19cb5_0    defaults
tensorboardx              2.6.2.2                  pypi_0    pypi
thinc                     8.2.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    defaults
tokenizers                0.14.1                   pypi_0    pypi
torchaudio                2.0.2                py38_cu117    pytorch
torchtriton               2.0.0                      py38    pytorch
torchvision               0.15.2               py38_cu117    pytorch
tqdm                      4.66.1                   pypi_0    pypi
transformers              4.35.0                   pypi_0    pypi
typer                     0.9.0                    pypi_0    pypi
typing-extensions         4.7.1            py38h06a4308_0    defaults
typing_extensions         4.7.1            py38h06a4308_0    defaults
urllib3                   1.26.18          py38h06a4308_0    defaults
utf8proc                  2.6.1                h27cfd23_0    defaults
wasabi                    1.1.2                    pypi_0    pypi
weasel                    0.3.4                    pypi_0    pypi
webdataset                0.2.75                   pypi_0    pypi
wheel                     0.41.2           py38h06a4308_0    defaults
xformers                  0.0.22                   pypi_0    pypi
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
yarl                      1.8.1            py38h5eee18b_0    defaults
zipp                      3.11.0           py38h06a4308_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults

**Comment by 1049451037** [comment]
Then it means your local tokenizer files are coorupted.

**Comment by zetaodu** [comment]
> Then it means your local tokenizer files are corrupted. Try re-download them with better internet connection.

YES! I notice it, trying again.
