### ISSUE TITLE
nan in logits

### ISSUE THREAD

**Issue by haoboluo** [THUDM/CogVLM#96]
Hi, 
I tried to perform inference in parallel on two 3090 graphics cards, but after outputting a few tokens, the logits output by the model were all nan. Do you have any suggestions for solving this issue? 

The error info in the terminal is 'nan in logits, set nan_default_token to proceed in BaseStrategy.forward.' This info can be located in the following code: 

` if torch.isnan(logits).any():
            if nan_default_token is None:
                raise ValueError('nan in logits, set nan_default_token to proceed in BaseStrategy.forward.')
            logits.fill_(-1000)
            logits[..., nan_default_token] = 0`

I've tried setting nan_default_token to 0 or other values, and the model can respond, but the answers don't make sense. 

Additionally, my computer has 64GB of memory, and I manually added 64GB of virtual memory to solve a previous error: 'RuntimeError: [1] is setting up NCCL communicator and retreiving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0')'. 

Thank you for any suggestions in advance.

**Comment by 1049451037** [comment]
You should use bf16 instead of fp16.

**Comment by joel-simp** [comment]
Hi, could you please tell me how did you find the logits? I have been struggling to do the same.

<img width="1039" alt="Screenshot 2024-06-19 at 12 20 19 PM" src="https://github.com/THUDM/CogVLM/assets/170931221/461808fc-2ca9-4225-a0d4-76899ffc4923">

**Comment by haoboluo** [comment]
Hi,

I didn't solve this bug and used other LLMs instead.
________________________________

**Comment by joel-simp** [comment]
You used other LLMs to check the confidence score of the texts generated by CogVLM? umm how does that work?
