### ISSUE TITLE
How to add Chain of Thought prompt?

### ISSUE THREAD

**Issue by superaha** [THUDM/CogVLM#97]
Hi there, 

I am wondering if there is any easy approach to add the zero-shot chain of thought prompt: Let's think step by step. I have tried to append this to the question or position this before the image and question. 
`
<img> <question> [CoT prompt]
or
[CoT prompt] <img> <question>
`
However, both cases make the performance worse. Any suggestions?

**Comment by 1049451037** [comment]
I think chain of thought should be added in label or answer, instead of added in question.

**Comment by superaha** [comment]
ok, so how about just add CoT during inference?

**Comment by zRzRzRzRzRzRzR** [comment]
use cogagent it will have cot
